-- BOND Assessment Content Seed
-- Requires schema.sql and 003_assessment_content_schema.sql first.

INSERT INTO assessments (
  id,
  name,
  framework,
  description,
  estimated_time,
  questions_count,
  icon,
  category,
  intro_title,
  intro_description,
  result_description,
  scoring_mode,
  content_version
) VALUES
  ('love-languages', 'Love Languages', 'Five Love Languages (Gary Chapman)', 'Discover how you and your partner prefer to give and receive love. Understanding these preferences can transform how you connect daily.', '8 min', 30, '❤️', 'connection', 'How do you experience love?', 'This assessment reveals your primary love language and helps you understand how you prefer to give and receive affection.', 'Your love language profile shows how you most naturally express and receive love.', 'preference', 'v2'),
  ('attachment-style', 'Attachment Style', 'Attachment Theory (Bowlby & Ainsworth)', 'Understand your attachment patterns and how they shape your relationship dynamics, emotional responses, and closeness with your partner.', '6 min', 20, '🔗', 'emotional', 'How do you connect emotionally?', 'Your attachment style influences how you seek closeness, handle anxiety, and maintain independence in relationships.', 'Your attachment style shapes how you bond and respond to intimacy.', 'quadrant', 'v2'),
  ('communication-style', 'Communication Style', 'Nonviolent Communication (Rosenberg)', 'Explore how you communicate needs, feelings, and boundaries. Learn patterns that strengthen or strain your connection.', '5 min', 15, '💬', 'communication', 'How do you express yourself?', 'Effective communication is the foundation of healthy relationships. Discover your strengths and growth areas.', 'Your communication profile reveals how you navigate conversations and connect with your partner.', 'profile', 'v2'),
  ('gottman-four-horsemen', 'Four Horsemen', 'Gottman Method', 'Identify destructive communication patterns that can damage your relationship. Learn to recognize and replace them with healthy alternatives.', '7 min', 20, '🐴', 'communication', 'Are there hidden patterns hurting your connection?', 'The Four Horsemen are criticism, contempt, defensiveness, and stonewalling. Learn if these patterns exist in your relationship.', 'Understanding these patterns helps you build healthier communication habits.', 'risk-profile', 'v2'),
  ('conflict-resolution', 'Conflict Resolution', 'Gottman Conflict Management', 'Discover your conflict resolution styles and learn how to navigate disagreements in ways that strengthen rather than strain your relationship.', '8 min', 25, '⚡', 'conflict', 'How do you handle disagreements?', 'Every couple conflicts, but it is how you navigate those moments that determines relationship health.', 'Your conflict style reveals strengths and strategies for healthier disagreements.', 'mixed-profile', 'v2'),
  ('values-alignment', 'Values Alignment', 'Acceptance & Commitment Therapy (ACT)', 'Explore shared values and life priorities. Understanding what matters most to both of you helps align your vision for the future.', '10 min', 30, '🎯', 'values', 'What truly matters to you both?', 'Shared values create shared purpose. This assessment explores where your values align and where they differ.', 'Your values profile shows areas of alignment and opportunities for deeper understanding.', 'profile', 'v2'),
  ('emotional-intelligence', 'Emotional Intelligence', 'Goleman EQ Model', 'Assess your emotional awareness, regulation, and responsiveness. High emotional intelligence is linked to stronger, more resilient relationships.', '8 min', 24, '🧠', 'emotional', 'How well do you understand and manage emotions?', 'Emotional intelligence includes recognizing your own feelings, understanding your partner, and responding thoughtfully rather than reactively.', 'Your EQ profile highlights emotional strengths and growth areas for deeper connection.', 'profile', 'v2'),
  ('intimacy-closeness', 'Intimacy & Closeness', 'Sternberg Triangular Theory', 'Measure emotional, physical, and intellectual intimacy levels. True intimacy combines all three dimensions for deep connection.', '9 min', 27, '💕', 'intimacy', 'How intimate is your connection?', 'Intimacy goes beyond physical closeness. Explore emotional vulnerability, intellectual connection, and physical affection.', 'Your intimacy profile shows the balance and depth of connection across all dimensions.', 'profile', 'v2'),
  ('trust-vulnerability', 'Trust & Vulnerability', 'Brené Brown Vulnerability Research', 'Evaluate trust levels and comfort with vulnerability. Trust is built through consistent vulnerability and emotional risk-taking.', '7 min', 18, '🛡️', 'trust', 'How safe do you feel being vulnerable?', 'Vulnerability is the foundation of deep connection. This assessment explores how comfortable you are being emotionally open.', 'Your trust profile reveals the safety and depth of emotional vulnerability in your relationship.', 'profile', 'v2'),
  ('financial-values', 'Financial Values', 'Financial Therapy Models', 'Understand your money beliefs, spending patterns, and financial communication. Financial stress is a leading cause of relationship tension.', '8 min', 22, '💰', 'values', 'How do your money values align?', 'Money is one of the most common sources of conflict in relationships. Understanding each other financial perspectives is key.', 'Your financial compatibility profile shows alignment and differences in money values and habits.', 'profile', 'v2'),
  ('sexual-compatibility', 'Sexual Compatibility', 'Sexual Health Models', 'Explore desires, boundaries, and sexual communication. Healthy sexual connection requires openness, understanding, and mutual satisfaction.', '10 min', 25, '🔥', 'intimacy', 'How aligned are your sexual needs and boundaries?', 'Sexual compatibility is about more than desire—it includes communication, comfort, and mutual respect for boundaries.', 'Your sexual compatibility profile helps identify areas of alignment and communication opportunities.', 'profile', 'v2'),
  ('shared-meaning', 'Shared Meaning', 'Gottman Sound Relationship House', 'Build shared rituals, goals, and life dreams. Creating shared meaning strengthens your bond and gives you a joint vision for the future.', '12 min', 30, '🏡', 'connection', 'What shared story are you building together?', 'Shared meaning encompasses your joint goals, traditions, and the legacy you are creating as a couple.', 'Your shared meaning profile shows the depth of your joint vision and connection.', 'profile', 'v2'),
  ('relationship-satisfaction', 'Relationship Satisfaction', 'RDAS (Revised Dyadic Adjustment Scale)', 'Overall relationship quality and satisfaction assessment. This validated scale measures consensus, satisfaction, and cohesion.', '6 min', 14, '⭐', 'general', 'How satisfied are you with your relationship?', 'This comprehensive assessment evaluates your overall relationship health across key dimensions.', 'Your satisfaction profile provides a complete picture of your relationship wellness.', 'profile', 'v2'),
  ('stress-coping', 'Stress & Coping', 'Lazarus & Folkman Stress Model', 'How you handle stress as a couple. External pressures can strain relationships or become opportunities for deeper connection.', '7 min', 20, '🌊', 'resilience', 'How do you navigate stress together?', 'Stress affects us all, and how couples support each other through challenges determines relationship resilience.', 'Your stress coping profile reveals how you and your partner handle pressure as a team.', 'profile', 'v2'),
  ('fun-personality', 'Fun & Personality', 'Leisure & Play Research', 'Explore how you enjoy time together and shared interests. Play and laughter are essential for long-term relationship satisfaction.', '6 min', 18, '🎉', 'connection', 'How do you have fun together?', 'Shared activities, humor, and play create positive experiences that strengthen your bond and create lasting memories.', 'Your fun and play profile shows how you create joy and connection through shared experiences.', 'profile', 'v2'),
  ('appreciation-gratitude', 'Appreciation & Gratitude', 'Positive Psychology', 'How you express and receive appreciation. Regular appreciation and gratitude are among the strongest predictors of relationship satisfaction.', '5 min', 15, '🙏', 'connection', 'Do you feel appreciated and grateful?', 'Expressing appreciation strengthens relationships. This assessment explores how you give and receive gratitude.', 'Your appreciation profile reveals how well gratitude and recognition flow in your relationship.', 'profile', 'v2')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  framework = EXCLUDED.framework,
  description = EXCLUDED.description,
  estimated_time = EXCLUDED.estimated_time,
  questions_count = EXCLUDED.questions_count,
  icon = EXCLUDED.icon,
  category = EXCLUDED.category,
  intro_title = EXCLUDED.intro_title,
  intro_description = EXCLUDED.intro_description,
  result_description = EXCLUDED.result_description,
  scoring_mode = EXCLUDED.scoring_mode,
  content_version = EXCLUDED.content_version;

INSERT INTO assessment_dimensions (assessment_id, dimension_key, label, direction, weight, sort_order) VALUES
  ('love-languages', 'words', 'Words of Affirmation', 'positive', 1, 1),
  ('love-languages', 'time', 'Quality Time', 'positive', 1, 2),
  ('love-languages', 'gifts', 'Receiving Gifts', 'positive', 1, 3),
  ('love-languages', 'acts', 'Acts of Service', 'positive', 1, 4),
  ('love-languages', 'touch', 'Physical Touch', 'positive', 1, 5),
  ('attachment-style', 'anxiety', 'Attachment Anxiety', 'risk', 1, 1),
  ('attachment-style', 'avoidance', 'Attachment Avoidance', 'risk', 1, 2),
  ('communication-style', 'expression', 'Expression', 'positive', 1, 1),
  ('communication-style', 'listening', 'Listening', 'positive', 1, 2),
  ('communication-style', 'validation', 'Validation', 'positive', 1, 3),
  ('communication-style', 'accountability', 'Accountability', 'positive', 1, 4),
  ('gottman-four-horsemen', 'criticism', 'Criticism', 'risk', 1, 1),
  ('gottman-four-horsemen', 'contempt', 'Contempt', 'risk', 1, 2),
  ('gottman-four-horsemen', 'defensiveness', 'Defensiveness', 'risk', 1, 3),
  ('gottman-four-horsemen', 'stonewalling', 'Stonewalling', 'risk', 1, 4),
  ('conflict-resolution', 'avoidance', 'Avoidance', 'risk', 1, 1),
  ('conflict-resolution', 'composure', 'Composure', 'positive', 1, 2),
  ('conflict-resolution', 'compromise', 'Compromise', 'positive', 1, 3),
  ('conflict-resolution', 'empathy', 'Empathy', 'positive', 1, 4),
  ('conflict-resolution', 'repair', 'Repair', 'positive', 1, 5),
  ('values-alignment', 'family', 'Family', 'positive', 1, 1),
  ('values-alignment', 'finance', 'Finance', 'positive', 1, 2),
  ('values-alignment', 'spirituality', 'Spirituality', 'positive', 1, 3),
  ('values-alignment', 'lifestyle', 'Lifestyle', 'positive', 1, 4),
  ('values-alignment', 'relationships', 'Relationships', 'positive', 1, 5),
  ('values-alignment', 'goals', 'Goals', 'positive', 1, 6),
  ('emotional-intelligence', 'selfAwareness', 'Self-awareness', 'positive', 1, 1),
  ('emotional-intelligence', 'selfRegulation', 'Self-regulation', 'positive', 1, 2),
  ('emotional-intelligence', 'empathy', 'Empathy', 'positive', 1, 3),
  ('emotional-intelligence', 'socialSkills', 'Social Skills', 'positive', 1, 4),
  ('intimacy-closeness', 'emotional', 'Emotional Intimacy', 'positive', 1, 1),
  ('intimacy-closeness', 'physical', 'Physical Intimacy', 'positive', 1, 2),
  ('intimacy-closeness', 'intellectual', 'Intellectual Intimacy', 'positive', 1, 3),
  ('trust-vulnerability', 'trust', 'Trust', 'positive', 1, 1),
  ('trust-vulnerability', 'vulnerability', 'Vulnerability', 'positive', 1, 2),
  ('trust-vulnerability', 'safety', 'Safety', 'positive', 1, 3),
  ('financial-values', 'attitudes', 'Money Attitudes', 'positive', 1, 1),
  ('financial-values', 'communication', 'Money Communication', 'positive', 1, 2),
  ('financial-values', 'goals', 'Financial Goals', 'positive', 1, 3),
  ('financial-values', 'habits', 'Money Habits', 'positive', 1, 4),
  ('sexual-compatibility', 'desire', 'Desire', 'positive', 1, 1),
  ('sexual-compatibility', 'communication', 'Sexual Communication', 'positive', 1, 2),
  ('sexual-compatibility', 'boundaries', 'Boundaries', 'positive', 1, 3),
  ('sexual-compatibility', 'satisfaction', 'Satisfaction', 'positive', 1, 4),
  ('shared-meaning', 'rituals', 'Rituals', 'positive', 1, 1),
  ('shared-meaning', 'goals', 'Goals', 'positive', 1, 2),
  ('shared-meaning', 'roles', 'Roles', 'positive', 1, 3),
  ('shared-meaning', 'legacy', 'Legacy', 'positive', 1, 4),
  ('shared-meaning', 'growth', 'Growth', 'positive', 1, 5),
  ('relationship-satisfaction', 'consensus', 'Consensus', 'positive', 1, 1),
  ('relationship-satisfaction', 'satisfaction', 'Satisfaction', 'positive', 1, 2),
  ('relationship-satisfaction', 'cohesion', 'Cohesion', 'positive', 1, 3),
  ('stress-coping', 'individual', 'Individual Coping', 'positive', 1, 1),
  ('stress-coping', 'partner', 'Partner Support', 'positive', 1, 2),
  ('stress-coping', 'team', 'Team Coping', 'positive', 1, 3),
  ('fun-personality', 'playfulness', 'Playfulness', 'positive', 1, 1),
  ('fun-personality', 'activities', 'Shared Activities', 'positive', 1, 2),
  ('fun-personality', 'humor', 'Humor', 'positive', 1, 3),
  ('fun-personality', 'adventure', 'Adventure', 'positive', 1, 4),
  ('appreciation-gratitude', 'expression', 'Expression', 'positive', 1, 1),
  ('appreciation-gratitude', 'recognition', 'Recognition', 'positive', 1, 2),
  ('appreciation-gratitude', 'positivity', 'Positivity', 'positive', 1, 3)
ON CONFLICT (assessment_id, dimension_key) DO UPDATE SET
  label = EXCLUDED.label,
  direction = EXCLUDED.direction,
  weight = EXCLUDED.weight,
  sort_order = EXCLUDED.sort_order;

INSERT INTO assessment_bands (assessment_id, band_key, min_score, max_score, title, summary, recommendation, sort_order) VALUES
  ('love-languages', 'needs-attention', 0, 39, 'Needs attention', 'This area needs more care, consistency, and conversation.', 'Pick one small habit and repeat it daily for the next week.', 1),
  ('love-languages', 'developing', 40, 59, 'Developing', 'You have some good foundations, but the pattern is still uneven.', 'Focus on one recurring moment where you can do a little better.', 2),
  ('love-languages', 'strong', 60, 79, 'Strong', 'This looks solid and generally healthy.', 'Protect what is working and keep practicing the habits that got you here.', 3),
  ('love-languages', 'exceptional', 80, 100, 'Exceptional', 'This is a genuine strength in your relationship.', 'Keep reinforcing it and use it as a model for the rest of your relationship.', 4)
ON CONFLICT (assessment_id, band_key) DO UPDATE SET
  min_score = EXCLUDED.min_score,
  max_score = EXCLUDED.max_score,
  title = EXCLUDED.title,
  summary = EXCLUDED.summary,
  recommendation = EXCLUDED.recommendation,
  sort_order = EXCLUDED.sort_order;

INSERT INTO assessment_questions (assessment_id, question_key, question_text, question_type, scale, category, reverse, options, sort_order) VALUES
  ('love-languages', 1, 'I feel most loved when my partner tells me they love me or compliments me', 'likert', 5, 'words', false, NULL, 1),
  ('love-languages', 2, 'Hearing encouraging words from my partner means more to me than any gift', 'likert', 5, 'words', false, NULL, 2),
  ('love-languages', 3, 'I appreciate it when my partner acknowledges my efforts, even for small things', 'likert', 5, 'words', false, NULL, 3),
  ('love-languages', 4, 'Written notes or text messages expressing love mean a lot to me', 'likert', 5, 'words', false, NULL, 4),
  ('love-languages', 5, 'When my partner criticizes me with harsh words, I feel deeply hurt', 'likert', 5, 'words', true, NULL, 5),
  ('love-languages', 6, 'I feel closest when my partner says kind things about me to others', 'likert', 5, 'words', false, NULL, 6),
  ('love-languages', 7, 'I feel most loved when my partner gives me their undivided attention', 'likert', 5, 'time', false, NULL, 7),
  ('love-languages', 8, 'I value time spent together more than receiving gifts', 'likert', 5, 'time', false, NULL, 8),
  ('love-languages', 9, 'When my partner is distracted or on their phone during our time, I feel neglected', 'likert', 5, 'time', true, NULL, 9),
  ('love-languages', 10, 'I love making plans for just the two of us with no distractions', 'likert', 5, 'time', false, NULL, 10),
  ('love-languages', 11, 'Scheduled date nights are important to me for maintaining our connection', 'likert', 5, 'time', false, NULL, 11),
  ('love-languages', 12, 'I feel loved when we spend an evening talking and catching up with each other', 'likert', 5, 'time', false, NULL, 12),
  ('love-languages', 13, 'I feel most loved when my partner gives me thoughtful gifts', 'likert', 5, 'gifts', false, NULL, 13),
  ('love-languages', 14, 'The effort my partner puts into finding a meaningful gift shows me they care', 'likert', 5, 'gifts', false, NULL, 14),
  ('love-languages', 15, 'I feel hurt when my partner forgets important occasions like birthdays or anniversaries', 'likert', 5, 'gifts', true, NULL, 15),
  ('love-languages', 16, 'Surprise gifts or little tokens of affection make me feel special', 'likert', 5, 'gifts', false, NULL, 16),
  ('love-languages', 17, 'I appreciate when my partner picks up small things they know I would like', 'likert', 5, 'gifts', false, NULL, 17),
  ('love-languages', 18, 'A gift does not need to be expensive to be meaningful to me—what matters is the thought behind it', 'likert', 5, 'gifts', false, NULL, 18),
  ('love-languages', 19, 'I feel most loved when my partner does helpful things for me without being asked', 'likert', 5, 'acts', false, NULL, 19),
  ('love-languages', 20, 'When my partner takes care of tasks I usually handle, I feel truly cared for', 'likert', 5, 'acts', false, NULL, 20),
  ('love-languages', 21, 'I feel hurt and unappreciated when I am overwhelmed and my partner does not help', 'likert', 5, 'acts', true, NULL, 21),
  ('love-languages', 22, 'I appreciate when my partner actively looks for ways to make my life easier', 'likert', 5, 'acts', false, NULL, 22),
  ('love-languages', 23, 'Actions speak louder than words to me—doing things for me shows love more than saying it', 'likert', 5, 'acts', false, NULL, 23),
  ('love-languages', 24, 'When my partner cooks a meal for me or helps with chores, I feel deeply loved', 'likert', 5, 'acts', false, NULL, 24),
  ('love-languages', 25, 'I feel most loved when my partner holds my hand, hugs me, or shows physical affection', 'likert', 5, 'touch', false, NULL, 25),
  ('love-languages', 26, 'Physical closeness and touch are essential to me feeling connected in the relationship', 'likert', 5, 'touch', false, NULL, 26),
  ('love-languages', 27, 'When my partner pulls away from physical touch, I feel rejected and unloved', 'likert', 5, 'touch', true, NULL, 27),
  ('love-languages', 28, 'I love cuddling, kissing, and general physical affection throughout the day', 'likert', 5, 'touch', false, NULL, 28),
  ('love-languages', 29, 'Physical touch is my primary way of feeling emotionally close to my partner', 'likert', 5, 'touch', false, NULL, 29),
  ('love-languages', 30, 'A warm embrace after a long day means more to me than any verbal reassurance', 'likert', 5, 'touch', false, NULL, 30),
  ('attachment-style', 1, 'I worry that my partner does not love me as much as I love them', 'likert', 5, 'anxiety', false, NULL, 1),
  ('attachment-style', 2, 'I am afraid that my partner might want to leave me', 'likert', 5, 'anxiety', false, NULL, 2),
  ('attachment-style', 3, 'I often wish my partner would show more emotion and affection', 'likert', 5, 'anxiety', false, NULL, 3),
  ('attachment-style', 4, 'I need a lot of reassurance that my partner loves me', 'likert', 5, 'anxiety', false, NULL, 4),
  ('attachment-style', 5, 'I often feel anxious when my partner is not around', 'likert', 5, 'anxiety', false, NULL, 5),
  ('attachment-style', 6, 'I often wonder whether my partner really cares about me', 'likert', 5, 'anxiety', false, NULL, 6),
  ('attachment-style', 7, 'When my partner does something hurtful, I cannot stop thinking about it', 'likert', 5, 'anxiety', false, NULL, 7),
  ('attachment-style', 8, 'I feel jealous when my partner spends time with others', 'likert', 5, 'anxiety', false, NULL, 8),
  ('attachment-style', 9, 'I am afraid of being abandoned in this relationship', 'likert', 5, 'anxiety', false, NULL, 9),
  ('attachment-style', 10, 'I often feel that my partner does not fully understand me or my needs', 'likert', 5, 'anxiety', false, NULL, 10),
  ('attachment-style', 11, 'I find it difficult to get emotionally close to my partner', 'likert', 5, 'avoidance', false, NULL, 11),
  ('attachment-style', 12, 'I prefer not to show my partner how I feel deep down', 'likert', 5, 'avoidance', false, NULL, 12),
  ('attachment-style', 13, 'I feel uncomfortable depending on my partner', 'likert', 5, 'avoidance', false, NULL, 13),
  ('attachment-style', 14, 'I prefer to deal with problems on my own rather than ask for help', 'likert', 5, 'avoidance', false, NULL, 14),
  ('attachment-style', 15, 'I feel smothered when my partner wants too much closeness', 'likert', 5, 'avoidance', false, NULL, 15),
  ('attachment-style', 16, 'I am uncomfortable when my partner wants to talk about our relationship feelings', 'likert', 5, 'avoidance', false, NULL, 16),
  ('attachment-style', 17, 'I tend to keep my emotions to myself in relationships', 'likert', 5, 'avoidance', false, NULL, 17),
  ('attachment-style', 18, 'I would rather stay independent than become too emotionally dependent on my partner', 'likert', 5, 'avoidance', false, NULL, 18),
  ('attachment-style', 19, 'I get uneasy when relationships become too intense or demanding', 'likert', 5, 'avoidance', false, NULL, 19),
  ('attachment-style', 20, 'I can stay calm and connected even when my partner is emotionally upset', 'likert', 5, 'avoidance', true, NULL, 20),
  ('communication-style', 1, 'I clearly express my needs to my partner', 'likert', 5, 'expression', false, NULL, 1),
  ('communication-style', 2, 'I listen without interrupting when my partner is speaking', 'likert', 5, 'listening', false, NULL, 2),
  ('communication-style', 3, 'I use "I feel" statements rather than blaming', 'likert', 5, 'expression', false, NULL, 3),
  ('communication-style', 4, 'I can discuss difficult topics calmly', 'likert', 5, 'self-regulation', false, NULL, 4),
  ('communication-style', 5, 'I validate my partner''s feelings even when I disagree', 'likert', 5, 'validation', false, NULL, 5),
  ('communication-style', 6, 'I avoid bringing up past conflicts during current disagreements', 'likert', 5, 'accountability', true, NULL, 6),
  ('communication-style', 7, 'I ask clarifying questions to understand my partner better', 'likert', 5, 'listening', false, NULL, 7),
  ('communication-style', 8, 'I take responsibility for my part in conflicts', 'likert', 5, 'accountability', false, NULL, 8),
  ('communication-style', 9, 'I express appreciation for my partner regularly', 'likert', 5, 'validation', false, NULL, 9),
  ('communication-style', 10, 'I can compromise when our needs differ', 'likert', 5, 'accountability', false, NULL, 10),
  ('communication-style', 11, 'I stay focused on the current issue instead of bringing up old wounds', 'likert', 5, 'accountability', false, NULL, 11),
  ('communication-style', 12, 'I can say hard things without becoming cruel or defensive', 'likert', 5, 'expression', false, NULL, 12),
  ('communication-style', 13, 'I let my partner finish their thought before I jump in', 'likert', 5, 'listening', false, NULL, 13),
  ('communication-style', 14, 'I check whether I understood my partner correctly', 'likert', 5, 'listening', false, NULL, 14),
  ('communication-style', 15, 'I can repair quickly after a miscommunication', 'likert', 5, 'validation', false, NULL, 15),
  ('gottman-four-horsemen', 1, 'I criticize my partner instead of making a specific request', 'likert', 5, 'criticism', true, NULL, 1),
  ('gottman-four-horsemen', 2, 'I find myself using contempt or sarcasm during conflict', 'likert', 5, 'contempt', true, NULL, 2),
  ('gottman-four-horsemen', 3, 'I get defensive when my partner brings up concerns', 'likert', 5, 'defensiveness', true, NULL, 3),
  ('gottman-four-horsemen', 4, 'I shut down or go silent when things get intense', 'likert', 5, 'stonewalling', true, NULL, 4),
  ('gottman-four-horsemen', 5, 'I can stay respectful even when I am angry', 'likert', 5, 'criticism', false, NULL, 5),
  ('gottman-four-horsemen', 6, 'I keep my tone kind even in a disagreement', 'likert', 5, 'contempt', false, NULL, 6),
  ('gottman-four-horsemen', 7, 'I can admit when I am wrong instead of defending myself', 'likert', 5, 'defensiveness', false, NULL, 7),
  ('gottman-four-horsemen', 8, 'I stay engaged instead of emotionally withdrawing', 'likert', 5, 'stonewalling', false, NULL, 8),
  ('gottman-four-horsemen', 9, 'I avoid blaming language when I am frustrated', 'likert', 5, 'criticism', false, NULL, 9),
  ('gottman-four-horsemen', 10, 'I avoid eye rolling, mocking, or dismissive behavior', 'likert', 5, 'contempt', false, NULL, 10),
  ('gottman-four-horsemen', 11, 'I try to understand my partner before reacting', 'likert', 5, 'defensiveness', false, NULL, 11),
  ('gottman-four-horsemen', 12, 'I can take a break and come back when I am overwhelmed', 'likert', 5, 'stonewalling', false, NULL, 12),
  ('gottman-four-horsemen', 13, 'I focus on the issue rather than attacking my partner''s character', 'likert', 5, 'criticism', false, NULL, 13),
  ('gottman-four-horsemen', 14, 'I show respect even when we disagree strongly', 'likert', 5, 'contempt', false, NULL, 14),
  ('gottman-four-horsemen', 15, 'I can hear feedback without immediately defending myself', 'likert', 5, 'defensiveness', false, NULL, 15),
  ('gottman-four-horsemen', 16, 'I know how to return to a conversation after taking space', 'likert', 5, 'stonewalling', false, NULL, 16),
  ('gottman-four-horsemen', 17, 'I can make a clear request instead of criticizing', 'likert', 5, 'criticism', false, NULL, 17),
  ('gottman-four-horsemen', 18, 'I do not use sarcasm or cruelty to get my point across', 'likert', 5, 'contempt', false, NULL, 18),
  ('gottman-four-horsemen', 19, 'I stay open to my partner''s perspective during tension', 'likert', 5, 'defensiveness', false, NULL, 19),
  ('gottman-four-horsemen', 20, 'I can stay present instead of checking out when conflict heats up', 'likert', 5, 'stonewalling', false, NULL, 20),
  ('conflict-resolution', 1, 'When conflict starts, I tend to avoid it', 'likert', 5, 'avoidance', true, NULL, 1),
  ('conflict-resolution', 2, 'I can stay calm when we disagree', 'likert', 5, 'composure', false, NULL, 2),
  ('conflict-resolution', 3, 'I am willing to compromise to reach a solution', 'likert', 5, 'compromise', false, NULL, 3),
  ('conflict-resolution', 4, 'I can understand my partner even when we see things differently', 'likert', 5, 'empathy', false, NULL, 4),
  ('conflict-resolution', 5, 'I know how to apologize and repair after conflict', 'likert', 5, 'repair', false, NULL, 5),
  ('conflict-resolution', 6, 'I shut down when conflict gets too emotional', 'likert', 5, 'avoidance', true, NULL, 6),
  ('conflict-resolution', 7, 'I can keep my tone steady during difficult conversations', 'likert', 5, 'composure', false, NULL, 7),
  ('conflict-resolution', 8, 'I am open to finding middle ground', 'likert', 5, 'compromise', false, NULL, 8),
  ('conflict-resolution', 9, 'I try to validate my partner even if I disagree', 'likert', 5, 'empathy', false, NULL, 9),
  ('conflict-resolution', 10, 'I can reconnect after an argument without holding grudges', 'likert', 5, 'repair', false, NULL, 10),
  ('conflict-resolution', 11, 'I would rather discuss issues than avoid them', 'likert', 5, 'avoidance', false, NULL, 11),
  ('conflict-resolution', 12, 'I keep the conversation calm and constructive', 'likert', 5, 'composure', false, NULL, 12),
  ('conflict-resolution', 13, 'I can balance my needs with my partner''s needs', 'likert', 5, 'compromise', false, NULL, 13),
  ('conflict-resolution', 14, 'I listen for the feeling underneath my partner''s words', 'likert', 5, 'empathy', false, NULL, 14),
  ('conflict-resolution', 15, 'I can make a sincere repair attempt after tension', 'likert', 5, 'repair', false, NULL, 15),
  ('conflict-resolution', 16, 'When a problem is uncomfortable, I still stay with it', 'likert', 5, 'avoidance', false, NULL, 16),
  ('conflict-resolution', 17, 'I can lower the temperature instead of escalating it', 'likert', 5, 'composure', false, NULL, 17),
  ('conflict-resolution', 18, 'I can think about a problem from both sides', 'likert', 5, 'empathy', false, NULL, 18),
  ('conflict-resolution', 19, 'I can accept a partial solution when perfect agreement is impossible', 'likert', 5, 'compromise', false, NULL, 19),
  ('conflict-resolution', 20, 'I know how to reset after a hard moment', 'likert', 5, 'repair', false, NULL, 20),
  ('conflict-resolution', 21, 'I tend to put off difficult conversations', 'likert', 5, 'avoidance', true, NULL, 21),
  ('conflict-resolution', 22, 'I can stay grounded even when I feel attacked', 'likert', 5, 'composure', false, NULL, 22),
  ('conflict-resolution', 23, 'I want solutions that honor both people', 'likert', 5, 'compromise', false, NULL, 23),
  ('conflict-resolution', 24, 'I care about my partner''s feelings during conflict', 'likert', 5, 'empathy', false, NULL, 24),
  ('conflict-resolution', 25, 'I am willing to try again after a conflict misfires', 'likert', 5, 'repair', false, NULL, 25),
  ('values-alignment', 1, 'We share similar values about family', 'likert', 5, 'family', false, NULL, 1),
  ('values-alignment', 2, 'We align on financial priorities', 'likert', 5, 'finance', false, NULL, 2),
  ('values-alignment', 3, 'We connect around spiritual or existential beliefs', 'likert', 5, 'spirituality', false, NULL, 3),
  ('values-alignment', 4, 'Our lifestyle preferences fit well together', 'likert', 5, 'lifestyle', false, NULL, 4),
  ('values-alignment', 5, 'We align in how we think about relationships and commitment', 'likert', 5, 'relationships', false, NULL, 5),
  ('values-alignment', 6, 'We want similar things from life', 'likert', 5, 'goals', false, NULL, 6),
  ('values-alignment', 7, 'We agree on what family should look like in our life', 'likert', 5, 'family', false, NULL, 7),
  ('values-alignment', 8, 'We talk openly about money and resources', 'likert', 5, 'finance', false, NULL, 8),
  ('values-alignment', 9, 'We can respectfully discuss beliefs that differ', 'likert', 5, 'spirituality', false, NULL, 9),
  ('values-alignment', 10, 'Our daily habits fit together well', 'likert', 5, 'lifestyle', false, NULL, 10),
  ('values-alignment', 11, 'We want the same kind of relationship long term', 'likert', 5, 'relationships', false, NULL, 11),
  ('values-alignment', 12, 'We are heading toward shared goals', 'likert', 5, 'goals', false, NULL, 12),
  ('values-alignment', 13, 'We value the same kind of family culture', 'likert', 5, 'family', false, NULL, 13),
  ('values-alignment', 14, 'We have similar beliefs about saving versus spending', 'likert', 5, 'finance', false, NULL, 14),
  ('values-alignment', 15, 'We have room for each other''s beliefs even when they differ', 'likert', 5, 'spirituality', false, NULL, 15),
  ('values-alignment', 16, 'We enjoy similar routines and pace of life', 'likert', 5, 'lifestyle', false, NULL, 16),
  ('values-alignment', 17, 'We both prioritize the relationship in a healthy way', 'likert', 5, 'relationships', false, NULL, 17),
  ('values-alignment', 18, 'We can describe a shared future we both like', 'likert', 5, 'goals', false, NULL, 18),
  ('values-alignment', 19, 'We agree on what family support should look like', 'likert', 5, 'family', false, NULL, 19),
  ('values-alignment', 20, 'We handle financial conversations with respect', 'likert', 5, 'finance', false, NULL, 20),
  ('values-alignment', 21, 'We respect different beliefs without trying to win', 'likert', 5, 'spirituality', false, NULL, 21),
  ('values-alignment', 22, 'Our daily rhythms feel compatible', 'likert', 5, 'lifestyle', false, NULL, 22),
  ('values-alignment', 23, 'We can talk about relationship expectations clearly', 'likert', 5, 'relationships', false, NULL, 23),
  ('values-alignment', 24, 'We can plan toward the same important goals', 'likert', 5, 'goals', false, NULL, 24),
  ('values-alignment', 25, 'We share similar hopes about family life', 'likert', 5, 'family', false, NULL, 25),
  ('values-alignment', 26, 'We are on the same page with financial planning', 'likert', 5, 'finance', false, NULL, 26),
  ('values-alignment', 27, 'We can talk about spiritual meaning respectfully', 'likert', 5, 'spirituality', false, NULL, 27),
  ('values-alignment', 28, 'We have compatible day-to-day preferences', 'likert', 5, 'lifestyle', false, NULL, 28),
  ('values-alignment', 29, 'We agree on what it means to show up in a relationship', 'likert', 5, 'relationships', false, NULL, 29),
  ('values-alignment', 30, 'We share a vision for where we are going', 'likert', 5, 'goals', false, NULL, 30),
  ('emotional-intelligence', 1, 'I can identify and name my emotions as I am experiencing them', 'likert', 5, 'selfAwareness', false, NULL, 1),
  ('emotional-intelligence', 2, 'I understand why I feel the way I do in most situations', 'likert', 5, 'selfAwareness', false, NULL, 2),
  ('emotional-intelligence', 3, 'I recognize how my emotions affect my behavior and reactions', 'likert', 5, 'selfAwareness', false, NULL, 3),
  ('emotional-intelligence', 4, 'I am aware of my emotional triggers and what sets me off', 'likert', 5, 'selfAwareness', false, NULL, 4),
  ('emotional-intelligence', 5, 'I can distinguish between different emotional states (e.g., fear vs. anxiety vs. worry)', 'likert', 5, 'selfAwareness', false, NULL, 5),
  ('emotional-intelligence', 6, 'I have good insight into my own strengths and weaknesses', 'likert', 5, 'selfAwareness', false, NULL, 6),
  ('emotional-intelligence', 7, 'I can calm myself down when I am upset or angry', 'likert', 5, 'selfRegulation', false, NULL, 7),
  ('emotional-intelligence', 8, 'I delay reacting in the moment to think before responding', 'likert', 5, 'selfRegulation', false, NULL, 8),
  ('emotional-intelligence', 9, 'I can handle criticism without becoming defensive or upset', 'likert', 5, 'selfRegulation', false, NULL, 9),
  ('emotional-intelligence', 10, 'I adapt well to unexpected changes and challenges', 'likert', 5, 'selfRegulation', false, NULL, 10),
  ('emotional-intelligence', 11, 'I manage stress effectively and do not let it overwhelm me easily', 'likert', 5, 'selfRegulation', false, NULL, 11),
  ('emotional-intelligence', 12, 'I keep my emotions in check even in difficult or high-pressure situations', 'likert', 5, 'selfRegulation', false, NULL, 12),
  ('emotional-intelligence', 13, 'I can sense how my partner is feeling even when they do not say it directly', 'likert', 5, 'empathy', false, NULL, 13),
  ('emotional-intelligence', 14, 'I understand my partner emotional perspective even when I disagree', 'likert', 5, 'empathy', false, NULL, 14),
  ('emotional-intelligence', 15, 'I respond to my partner emotions with care and concern', 'likert', 5, 'empathy', false, NULL, 15),
  ('emotional-intelligence', 16, 'I can put myself in my partner shoes and see things from their perspective', 'likert', 5, 'empathy', false, NULL, 16),
  ('emotional-intelligence', 17, 'I notice when my partner is struggling and offer support proactively', 'likert', 5, 'empathy', false, NULL, 17),
  ('emotional-intelligence', 18, 'I validate my partner feelings rather than dismissing or minimizing them', 'likert', 5, 'empathy', false, NULL, 18),
  ('emotional-intelligence', 19, 'I communicate clearly and effectively with my partner', 'likert', 5, 'socialSkills', false, NULL, 19),
  ('emotional-intelligence', 20, 'I can navigate disagreements without damaging the relationship', 'likert', 5, 'socialSkills', false, NULL, 20),
  ('emotional-intelligence', 21, 'I am good at reading non-verbal cues and body language', 'likert', 5, 'socialSkills', false, NULL, 21),
  ('emotional-intelligence', 22, 'I support my partner through difficult emotions without trying to fix everything', 'likert', 5, 'socialSkills', false, NULL, 22),
  ('emotional-intelligence', 23, 'I can express difficult emotions in a constructive way', 'likert', 5, 'socialSkills', false, NULL, 23),
  ('emotional-intelligence', 24, 'I maintain emotional intimacy even during stressful periods', 'likert', 5, 'socialSkills', false, NULL, 24),
  ('intimacy-closeness', 1, 'I feel safe sharing my deepest fears and insecurities with my partner', 'likert', 5, 'emotional', false, NULL, 1),
  ('intimacy-closeness', 2, 'I can be fully authentic with my partner without fear of judgment', 'likert', 5, 'emotional', false, NULL, 2),
  ('intimacy-closeness', 3, 'I feel emotionally supported and understood by my partner', 'likert', 5, 'emotional', false, NULL, 3),
  ('intimacy-closeness', 4, 'I can share personal struggles with my partner without hesitation', 'likert', 5, 'emotional', false, NULL, 4),
  ('intimacy-closeness', 5, 'I feel deeply connected when we have meaningful conversations', 'likert', 5, 'emotional', false, NULL, 5),
  ('intimacy-closeness', 6, 'I trust my partner with my most vulnerable thoughts and feelings', 'likert', 5, 'emotional', false, NULL, 6),
  ('intimacy-closeness', 7, 'I feel close to my partner when we talk about our inner lives', 'likert', 5, 'emotional', false, NULL, 7),
  ('intimacy-closeness', 8, 'I experience emotional intimacy as one of the strongest parts of our relationship', 'likert', 5, 'emotional', false, NULL, 8),
  ('intimacy-closeness', 9, 'I feel comfortable being emotionally dependent on my partner when needed', 'likert', 5, 'emotional', false, NULL, 9),
  ('intimacy-closeness', 10, 'Physical affection is an important part of how I feel connected', 'likert', 5, 'physical', false, NULL, 10),
  ('intimacy-closeness', 11, 'I feel close to my partner through touch, cuddling, or affection', 'likert', 5, 'physical', false, NULL, 11),
  ('intimacy-closeness', 12, 'I am comfortable expressing physical affection openly', 'likert', 5, 'physical', false, NULL, 12),
  ('intimacy-closeness', 13, 'I feel affectionate toward my partner throughout the day', 'likert', 5, 'physical', false, NULL, 13),
  ('intimacy-closeness', 14, 'I feel emotionally regulated when we are physically close', 'likert', 5, 'physical', false, NULL, 14),
  ('intimacy-closeness', 15, 'Physical closeness helps me feel secure in the relationship', 'likert', 5, 'physical', false, NULL, 15),
  ('intimacy-closeness', 16, 'I enjoy spontaneous affection and touch', 'likert', 5, 'physical', false, NULL, 16),
  ('intimacy-closeness', 17, 'Our physical connection supports our emotional connection', 'likert', 5, 'physical', false, NULL, 17),
  ('intimacy-closeness', 18, 'I feel safe initiating physical intimacy with my partner', 'likert', 5, 'physical', false, NULL, 18),
  ('intimacy-closeness', 19, 'We can talk through ideas and opinions without losing connection', 'likert', 5, 'intellectual', false, NULL, 19),
  ('intimacy-closeness', 20, 'I enjoy sharing thoughts, books, or ideas with my partner', 'likert', 5, 'intellectual', false, NULL, 20),
  ('intimacy-closeness', 21, 'We challenge each other to think more deeply', 'likert', 5, 'intellectual', false, NULL, 21),
  ('intimacy-closeness', 22, 'I feel mentally stimulated by conversations with my partner', 'likert', 5, 'intellectual', false, NULL, 22),
  ('intimacy-closeness', 23, 'We enjoy exploring meaningful topics together', 'likert', 5, 'intellectual', false, NULL, 23),
  ('intimacy-closeness', 24, 'I feel understood on an intellectual level by my partner', 'likert', 5, 'intellectual', false, NULL, 24),
  ('intimacy-closeness', 25, 'We can disagree intellectually without feeling disconnected', 'likert', 5, 'intellectual', false, NULL, 25),
  ('intimacy-closeness', 26, 'I like talking through our future and ideas together', 'likert', 5, 'intellectual', false, NULL, 26),
  ('intimacy-closeness', 27, 'Our conversations help me feel closer to my partner', 'likert', 5, 'intellectual', false, NULL, 27),
  ('trust-vulnerability', 1, 'I feel safe being honest with my partner even when the truth is uncomfortable', 'likert', 5, 'trust', false, NULL, 1),
  ('trust-vulnerability', 2, 'I believe my partner will keep important confidences', 'likert', 5, 'trust', false, NULL, 2),
  ('trust-vulnerability', 3, 'I can rely on my partner to follow through', 'likert', 5, 'trust', false, NULL, 3),
  ('trust-vulnerability', 4, 'I feel secure that my partner has my back', 'likert', 5, 'trust', false, NULL, 4),
  ('trust-vulnerability', 5, 'I trust my partner''s intentions even when we disagree', 'likert', 5, 'trust', false, NULL, 5),
  ('trust-vulnerability', 6, 'I can share something deeply personal without fearing rejection', 'likert', 5, 'vulnerability', false, NULL, 6),
  ('trust-vulnerability', 7, 'I can admit when I am hurting or scared', 'likert', 5, 'vulnerability', false, NULL, 7),
  ('trust-vulnerability', 8, 'I can ask for reassurance when I need it', 'likert', 5, 'vulnerability', false, NULL, 8),
  ('trust-vulnerability', 9, 'I let my partner see the imperfect parts of me', 'likert', 5, 'vulnerability', false, NULL, 9),
  ('trust-vulnerability', 10, 'I feel emotionally safe enough to take risks in this relationship', 'likert', 5, 'safety', false, NULL, 10),
  ('trust-vulnerability', 11, 'I feel calm when my partner is upset with me because we can repair', 'likert', 5, 'safety', false, NULL, 11),
  ('trust-vulnerability', 12, 'I can be myself without walking on eggshells', 'likert', 5, 'safety', false, NULL, 12),
  ('trust-vulnerability', 13, 'I feel respected even in difficult moments', 'likert', 5, 'safety', false, NULL, 13),
  ('trust-vulnerability', 14, 'I can bring up hard feelings without fearing retaliation', 'likert', 5, 'safety', false, NULL, 14),
  ('trust-vulnerability', 15, 'I know how to rebuild safety after conflict', 'likert', 5, 'safety', false, NULL, 15),
  ('trust-vulnerability', 16, 'My partner is consistent enough that I can relax', 'likert', 5, 'trust', false, NULL, 16),
  ('trust-vulnerability', 17, 'I feel comfortable letting my partner in emotionally', 'likert', 5, 'vulnerability', false, NULL, 17),
  ('trust-vulnerability', 18, 'I can trust the repair process after a hard moment', 'likert', 5, 'safety', false, NULL, 18),
  ('financial-values', 1, 'We agree on what money is for in our life', 'likert', 5, 'attitudes', false, NULL, 1),
  ('financial-values', 2, 'We can talk about money without it turning into conflict', 'likert', 5, 'communication', false, NULL, 2),
  ('financial-values', 3, 'We share similar financial goals', 'likert', 5, 'goals', false, NULL, 3),
  ('financial-values', 4, 'Our spending habits work well together', 'likert', 5, 'habits', false, NULL, 4),
  ('financial-values', 5, 'We are honest about money stress', 'likert', 5, 'communication', false, NULL, 5),
  ('financial-values', 6, 'We feel aligned on saving and planning', 'likert', 5, 'goals', false, NULL, 6),
  ('financial-values', 7, 'I feel comfortable discussing money with my partner', 'likert', 5, 'communication', false, NULL, 7),
  ('financial-values', 8, 'We handle surprises without financial panic', 'likert', 5, 'habits', false, NULL, 8),
  ('financial-values', 9, 'We agree on priorities for spending', 'likert', 5, 'attitudes', false, NULL, 9),
  ('financial-values', 10, 'We make money decisions as a team', 'likert', 5, 'communication', false, NULL, 10),
  ('financial-values', 11, 'We have shared goals that motivate our money choices', 'likert', 5, 'goals', false, NULL, 11),
  ('financial-values', 12, 'Our money habits reduce stress rather than create it', 'likert', 5, 'habits', false, NULL, 12),
  ('financial-values', 13, 'We can discuss debt or savings with honesty', 'likert', 5, 'communication', false, NULL, 13),
  ('financial-values', 14, 'We understand each other''s money story', 'likert', 5, 'attitudes', false, NULL, 14),
  ('financial-values', 15, 'We can plan for the future without getting overwhelmed', 'likert', 5, 'goals', false, NULL, 15),
  ('financial-values', 16, 'We are aligned on the practical side of money', 'likert', 5, 'habits', false, NULL, 16),
  ('financial-values', 17, 'We can discuss a purchase before making it', 'likert', 5, 'communication', false, NULL, 17),
  ('financial-values', 18, 'We share a healthy attitude toward money', 'likert', 5, 'attitudes', false, NULL, 18),
  ('financial-values', 19, 'We can coordinate financial responsibilities smoothly', 'likert', 5, 'habits', false, NULL, 19),
  ('financial-values', 20, 'We feel like partners in building a stable future', 'likert', 5, 'goals', false, NULL, 20),
  ('financial-values', 21, 'We talk about money before stress builds up', 'likert', 5, 'communication', false, NULL, 21),
  ('financial-values', 22, 'We have compatible views about spending and saving', 'likert', 5, 'attitudes', false, NULL, 22),
  ('sexual-compatibility', 1, 'We talk openly about desire and attraction', 'likert', 5, 'desire', false, NULL, 1),
  ('sexual-compatibility', 2, 'We can discuss what feels good and what does not', 'likert', 5, 'communication', false, NULL, 2),
  ('sexual-compatibility', 3, 'We respect each other''s boundaries', 'likert', 5, 'boundaries', false, NULL, 3),
  ('sexual-compatibility', 4, 'I feel satisfied with our physical connection', 'likert', 5, 'satisfaction', false, NULL, 4),
  ('sexual-compatibility', 5, 'We can talk about intimacy without awkwardness taking over', 'likert', 5, 'communication', false, NULL, 5),
  ('sexual-compatibility', 6, 'We can say yes and no clearly with kindness', 'likert', 5, 'boundaries', false, NULL, 6),
  ('sexual-compatibility', 7, 'We understand each other''s sexual needs', 'likert', 5, 'desire', false, NULL, 7),
  ('sexual-compatibility', 8, 'Our intimacy leaves us feeling connected afterward', 'likert', 5, 'satisfaction', false, NULL, 8),
  ('sexual-compatibility', 9, 'We can bring up discomfort without fear', 'likert', 5, 'communication', false, NULL, 9),
  ('sexual-compatibility', 10, 'We are aligned on what feels respectful and safe', 'likert', 5, 'boundaries', false, NULL, 10),
  ('sexual-compatibility', 11, 'We can talk about frequency and expectations honestly', 'likert', 5, 'desire', false, NULL, 11),
  ('sexual-compatibility', 12, 'Our intimacy feels mutually satisfying most of the time', 'likert', 5, 'satisfaction', false, NULL, 12),
  ('sexual-compatibility', 13, 'We can ask for what we need without shame', 'likert', 5, 'communication', false, NULL, 13),
  ('sexual-compatibility', 14, 'We feel safe enough to explore preferences', 'likert', 5, 'boundaries', false, NULL, 14),
  ('sexual-compatibility', 15, 'Our level of desire is discussed openly and kindly', 'likert', 5, 'desire', false, NULL, 15),
  ('sexual-compatibility', 16, 'I feel heard when I talk about intimacy', 'likert', 5, 'communication', false, NULL, 16),
  ('sexual-compatibility', 17, 'We can handle mismatched desire without shame', 'likert', 5, 'desire', false, NULL, 17),
  ('sexual-compatibility', 18, 'We are thoughtful about pacing and consent', 'likert', 5, 'boundaries', false, NULL, 18),
  ('sexual-compatibility', 19, 'I feel emotionally satisfied by our intimacy', 'likert', 5, 'satisfaction', false, NULL, 19),
  ('sexual-compatibility', 20, 'We can recover well after an intimacy misfire', 'likert', 5, 'communication', false, NULL, 20),
  ('sexual-compatibility', 21, 'We can talk about vulnerability in a sexual context', 'likert', 5, 'communication', false, NULL, 21),
  ('sexual-compatibility', 22, 'I feel respected in our intimate connection', 'likert', 5, 'boundaries', false, NULL, 22),
  ('sexual-compatibility', 23, 'We stay connected even when desire is uneven', 'likert', 5, 'desire', false, NULL, 23),
  ('sexual-compatibility', 24, 'Our intimate life feels like a shared experience', 'likert', 5, 'satisfaction', false, NULL, 24),
  ('sexual-compatibility', 25, 'We can ask questions about intimacy without judgment', 'likert', 5, 'communication', false, NULL, 25),
  ('shared-meaning', 1, 'We have rituals that make our relationship feel special', 'likert', 5, 'rituals', false, NULL, 1),
  ('shared-meaning', 2, 'We talk about our future together', 'likert', 5, 'goals', false, NULL, 2),
  ('shared-meaning', 3, 'We are clear about our roles and responsibilities', 'likert', 5, 'roles', false, NULL, 3),
  ('shared-meaning', 4, 'We feel like we are building a legacy together', 'likert', 5, 'legacy', false, NULL, 4),
  ('shared-meaning', 5, 'We grow together instead of drifting apart', 'likert', 5, 'growth', false, NULL, 5),
  ('shared-meaning', 6, 'We have routines that make us feel connected', 'likert', 5, 'rituals', false, NULL, 6),
  ('shared-meaning', 7, 'We set shared goals and revisit them', 'likert', 5, 'goals', false, NULL, 7),
  ('shared-meaning', 8, 'We are clear about what each of us handles', 'likert', 5, 'roles', false, NULL, 8),
  ('shared-meaning', 9, 'We think about the kind of life we are building', 'likert', 5, 'legacy', false, NULL, 9),
  ('shared-meaning', 10, 'We support each other''s growth', 'likert', 5, 'growth', false, NULL, 10),
  ('shared-meaning', 11, 'We protect traditions that matter to us', 'likert', 5, 'rituals', false, NULL, 11),
  ('shared-meaning', 12, 'We can align on major goals', 'likert', 5, 'goals', false, NULL, 12),
  ('shared-meaning', 13, 'We understand who is responsible for what', 'likert', 5, 'roles', false, NULL, 13),
  ('shared-meaning', 14, 'We have a sense of purpose as a couple', 'likert', 5, 'legacy', false, NULL, 14),
  ('shared-meaning', 15, 'We encourage each other to keep evolving', 'likert', 5, 'growth', false, NULL, 15),
  ('shared-meaning', 16, 'Our rituals make us feel rooted', 'likert', 5, 'rituals', false, NULL, 16),
  ('shared-meaning', 17, 'We can align around big life dreams', 'likert', 5, 'goals', false, NULL, 17),
  ('shared-meaning', 18, 'We share responsibilities in a way that feels fair', 'likert', 5, 'roles', false, NULL, 18),
  ('shared-meaning', 19, 'We think about what we are passing forward', 'likert', 5, 'legacy', false, NULL, 19),
  ('shared-meaning', 20, 'We support the other person''s growth even when it is hard', 'likert', 5, 'growth', false, NULL, 20),
  ('shared-meaning', 21, 'We have rituals we look forward to', 'likert', 5, 'rituals', false, NULL, 21),
  ('shared-meaning', 22, 'We stay aligned on important goals', 'likert', 5, 'goals', false, NULL, 22),
  ('shared-meaning', 23, 'We know how to share responsibility well', 'likert', 5, 'roles', false, NULL, 23),
  ('shared-meaning', 24, 'We feel proud of the life we are building', 'likert', 5, 'legacy', false, NULL, 24),
  ('shared-meaning', 25, 'We encourage long-term growth in each other', 'likert', 5, 'growth', false, NULL, 25),
  ('shared-meaning', 26, 'Our rituals feel meaningful rather than automatic', 'likert', 5, 'rituals', false, NULL, 26),
  ('shared-meaning', 27, 'We are clear on where we are headed', 'likert', 5, 'goals', false, NULL, 27),
  ('shared-meaning', 28, 'We handle our roles in a way that feels balanced', 'likert', 5, 'roles', false, NULL, 28),
  ('shared-meaning', 29, 'We think about the legacy of our relationship', 'likert', 5, 'legacy', false, NULL, 29),
  ('shared-meaning', 30, 'We grow in ways that support the relationship', 'likert', 5, 'growth', false, NULL, 30),
  ('relationship-satisfaction', 1, 'We agree on important decisions', 'likert', 5, 'consensus', false, NULL, 1),
  ('relationship-satisfaction', 2, 'I am satisfied with our relationship', 'likert', 5, 'satisfaction', false, NULL, 2),
  ('relationship-satisfaction', 3, 'We feel emotionally close', 'likert', 5, 'cohesion', false, NULL, 3),
  ('relationship-satisfaction', 4, 'We handle problems in a way that works for both of us', 'likert', 5, 'consensus', false, NULL, 4),
  ('relationship-satisfaction', 5, 'I feel content with the relationship most of the time', 'likert', 5, 'satisfaction', false, NULL, 5),
  ('relationship-satisfaction', 6, 'We enjoy being together', 'likert', 5, 'cohesion', false, NULL, 6),
  ('relationship-satisfaction', 7, 'We can agree on how to spend money and time', 'likert', 5, 'consensus', false, NULL, 7),
  ('relationship-satisfaction', 8, 'I am happy with how our relationship is going', 'likert', 5, 'satisfaction', false, NULL, 8),
  ('relationship-satisfaction', 9, 'We spend enough time together to feel bonded', 'likert', 5, 'cohesion', false, NULL, 9),
  ('relationship-satisfaction', 10, 'We usually see eye to eye on major matters', 'likert', 5, 'consensus', false, NULL, 10),
  ('relationship-satisfaction', 11, 'I feel good about our relationship overall', 'likert', 5, 'satisfaction', false, NULL, 11),
  ('relationship-satisfaction', 12, 'We have a sense of togetherness', 'likert', 5, 'cohesion', false, NULL, 12),
  ('relationship-satisfaction', 13, 'We can make decisions together smoothly', 'likert', 5, 'consensus', false, NULL, 13),
  ('relationship-satisfaction', 14, 'We are satisfied with the way we relate to each other', 'likert', 5, 'satisfaction', false, NULL, 14),
  ('stress-coping', 1, 'I manage my own stress in healthy ways', 'likert', 5, 'individual', false, NULL, 1),
  ('stress-coping', 2, 'My partner supports me well when life gets hard', 'likert', 5, 'partner', false, NULL, 2),
  ('stress-coping', 3, 'We handle stress like a team', 'likert', 5, 'team', false, NULL, 3),
  ('stress-coping', 4, 'I do not take my stress out on my partner when things get difficult', 'likert', 5, 'individual', false, NULL, 4),
  ('stress-coping', 5, 'I can separate work stress from my home life and relationship', 'likert', 5, 'individual', false, NULL, 5),
  ('stress-coping', 6, 'I maintain my own well-being even during stressful periods', 'likert', 5, 'individual', false, NULL, 6),
  ('stress-coping', 7, 'I know when I need support and can ask my partner for help', 'likert', 5, 'individual', false, NULL, 7),
  ('stress-coping', 8, 'My partner is supportive when I am going through stressful periods', 'likert', 5, 'partner', false, NULL, 8),
  ('stress-coping', 9, 'My partner gives me space when I need it but also checks in on me', 'likert', 5, 'partner', false, NULL, 9),
  ('stress-coping', 10, 'I can lean on my partner for emotional support during hard times', 'likert', 5, 'partner', false, NULL, 10),
  ('stress-coping', 11, 'My partner helps me see stressful situations more clearly', 'likert', 5, 'partner', false, NULL, 11),
  ('stress-coping', 12, 'When I am stressed, my partner does not make it worse with their own reactions', 'likert', 5, 'partner', false, NULL, 12),
  ('stress-coping', 13, 'My partner is patient with me when stress makes me less present', 'likert', 5, 'partner', false, NULL, 13),
  ('stress-coping', 14, 'I feel comfortable sharing my stress with my partner without judgment', 'likert', 5, 'partner', false, NULL, 14),
  ('stress-coping', 15, 'We handle financial stress together as a team', 'likert', 5, 'team', false, NULL, 15),
  ('stress-coping', 16, 'We support each other through work-related stress and career challenges', 'likert', 5, 'team', false, NULL, 16),
  ('stress-coping', 17, 'When external pressures threaten our relationship, we face them together', 'likert', 5, 'team', false, NULL, 17),
  ('stress-coping', 18, 'We can talk about stress without it turning into conflict', 'likert', 5, 'team', false, NULL, 18),
  ('stress-coping', 19, 'Our relationship remains stable even when external stressors increase', 'likert', 5, 'team', false, NULL, 19),
  ('stress-coping', 20, 'We have strategies for coping with stress that we practice together', 'likert', 5, 'team', false, NULL, 20),
  ('fun-personality', 1, 'I consider myself a playful person who enjoys laughter and lighthearted moments', 'likert', 5, 'playfulness', false, NULL, 1),
  ('fun-personality', 2, 'My partner and I enjoy being silly and playful together', 'likert', 5, 'playfulness', false, NULL, 2),
  ('fun-personality', 3, 'We can laugh at ourselves and not take everything so seriously', 'likert', 5, 'playfulness', false, NULL, 3),
  ('fun-personality', 4, 'Our relationship feels fun and enjoyable most of the time', 'likert', 5, 'playfulness', false, NULL, 4),
  ('fun-personality', 5, 'We retain a sense of childlike wonder and excitement together', 'likert', 5, 'playfulness', false, NULL, 5),
  ('fun-personality', 6, 'We have shared hobbies or activities that we enjoy doing together', 'likert', 5, 'activities', false, NULL, 6),
  ('fun-personality', 7, 'We regularly try new activities or explore new experiences together', 'likert', 5, 'activities', false, NULL, 7),
  ('fun-personality', 8, 'We enjoy spending quality time together doing things we both love', 'likert', 5, 'activities', false, NULL, 8),
  ('fun-personality', 9, 'We make time for fun and recreation even when life is busy', 'likert', 5, 'activities', false, NULL, 9),
  ('fun-personality', 10, 'Our shared activities bring us closer and create lasting memories', 'likert', 5, 'activities', false, NULL, 10),
  ('fun-personality', 11, 'We share a similar sense of humor and make each other laugh', 'likert', 5, 'humor', false, NULL, 11),
  ('fun-personality', 12, 'Laughter is a big part of our relationship', 'likert', 5, 'humor', false, NULL, 12),
  ('fun-personality', 13, 'We can laugh together even during difficult times', 'likert', 5, 'humor', false, NULL, 13),
  ('fun-personality', 14, 'We use humor to lighten tense moments and navigate conflict', 'likert', 5, 'humor', false, NULL, 14),
  ('fun-personality', 15, 'We enjoy spontaneous adventures and trying new things together', 'likert', 5, 'adventure', false, NULL, 15),
  ('fun-personality', 16, 'We share a spirit of curiosity and love exploring together', 'likert', 5, 'adventure', false, NULL, 16),
  ('fun-personality', 17, 'We plan exciting experiences and look forward to them together', 'likert', 5, 'adventure', false, NULL, 17),
  ('fun-personality', 18, 'We have a bucket list or goals that include adventurous experiences together', 'likert', 5, 'adventure', false, NULL, 18),
  ('appreciation-gratitude', 1, 'I regularly tell my partner things I appreciate about them', 'likert', 5, 'expression', false, NULL, 1),
  ('appreciation-gratitude', 2, 'I express gratitude for the small things my partner does daily', 'likert', 5, 'expression', false, NULL, 2),
  ('appreciation-gratitude', 3, 'I show appreciation for my partner more often than I take them for granted', 'likert', 5, 'expression', false, NULL, 3),
  ('appreciation-gratitude', 4, 'I make it a habit to notice and acknowledge my partner efforts', 'likert', 5, 'expression', false, NULL, 4),
  ('appreciation-gratitude', 5, 'I express thanks and gratitude rather than assuming my partner knows how I feel', 'likert', 5, 'expression', false, NULL, 5),
  ('appreciation-gratitude', 6, 'I recognize and acknowledge my partner contributions to our relationship', 'likert', 5, 'recognition', false, NULL, 6),
  ('appreciation-gratitude', 7, 'I celebrate my partner successes and accomplishments', 'likert', 5, 'recognition', false, NULL, 7),
  ('appreciation-gratitude', 8, 'I make my partner feel valued and seen for who they are', 'likert', 5, 'recognition', false, NULL, 8),
  ('appreciation-gratitude', 9, 'I notice the effort my partner puts into our relationship and show I notice', 'likert', 5, 'recognition', false, NULL, 9),
  ('appreciation-gratitude', 10, 'My partner makes me feel appreciated and valued', 'likert', 5, 'recognition', false, NULL, 10),
  ('appreciation-gratitude', 11, 'I focus on what I love about my partner rather than their flaws', 'likert', 5, 'positivity', false, NULL, 11),
  ('appreciation-gratitude', 12, 'I am grateful for our relationship and tell my partner that', 'likert', 5, 'positivity', false, NULL, 12),
  ('appreciation-gratitude', 13, 'I regularly reflect on the positive aspects of our relationship', 'likert', 5, 'positivity', false, NULL, 13),
  ('appreciation-gratitude', 14, 'I end each day with gratitude for my partner presence in my life', 'likert', 5, 'positivity', false, NULL, 14),
  ('appreciation-gratitude', 15, 'Gratitude and appreciation are natural parts of how we communicate', 'likert', 5, 'positivity', false, NULL, 15)
ON CONFLICT (assessment_id, question_key) DO UPDATE SET
  question_text = EXCLUDED.question_text,
  question_type = EXCLUDED.question_type,
  scale = EXCLUDED.scale,
  category = EXCLUDED.category,
  reverse = EXCLUDED.reverse,
  options = EXCLUDED.options,
  sort_order = EXCLUDED.sort_order;
