-- BOND Full Assessment Questions Seed
-- Extracted from allAssessments.js — 353 questions across 16 assessments
-- Run AFTER bond_schema.sql and bond_seed.sql

INSERT INTO assessment_questions (assessment_id,question_key,question_text,question_type,scale,category,reverse,options) VALUES
  ('love-languages','1','I feel most loved when my partner tells me they love me or compliments me','likert',5,'words',false,NULL),
  ('love-languages','2','Hearing encouraging words from my partner means more to me than any gift','likert',5,'words',false,NULL),
  ('love-languages','3','I appreciate it when my partner acknowledges my efforts, even for small things','likert',5,'words',false,NULL),
  ('love-languages','4','Written notes or text messages expressing love mean a lot to me','likert',5,'words',false,NULL),
  ('love-languages','5','When my partner criticizes me with harsh words, I feel deeply hurt','likert',5,'words',true,NULL),
  ('love-languages','6','I feel closest when my partner says kind things about me to others','likert',5,'words',false,NULL),
  ('love-languages','7','I feel most loved when my partner gives me their undivided attention','likert',5,'time',false,NULL),
  ('love-languages','8','I value time spent together more than receiving gifts','likert',5,'time',false,NULL),
  ('love-languages','9','When my partner is distracted or on their phone during our time, I feel neglected','likert',5,'time',true,NULL),
  ('love-languages','10','I love making plans for just the two of us with no distractions','likert',5,'time',false,NULL),
  ('love-languages','11','Scheduled date nights are important to me for maintaining our connection','likert',5,'time',false,NULL),
  ('love-languages','12','I feel loved when we spend an evening talking and catching up with each other','likert',5,'time',false,NULL),
  ('love-languages','13','I feel most loved when my partner gives me thoughtful gifts','likert',5,'gifts',false,NULL),
  ('love-languages','14','The effort my partner puts into finding a meaningful gift shows me they care','likert',5,'gifts',false,NULL),
  ('love-languages','15','I feel hurt when my partner forgets important occasions like birthdays or anniversaries','likert',5,'gifts',true,NULL),
  ('love-languages','16','Surprise gifts or little tokens of affection make me feel special','likert',5,'gifts',false,NULL),
  ('love-languages','17','I appreciate when my partner picks up small things they know I would like','likert',5,'gifts',false,NULL),
  ('love-languages','18','A gift does not need to be expensive to be meaningful to me—what matters is the thought behind it','likert',5,'gifts',false,NULL),
  ('love-languages','19','I feel most loved when my partner does helpful things for me without being asked','likert',5,'acts',false,NULL),
  ('love-languages','20','When my partner takes care of tasks I usually handle, I feel truly cared for','likert',5,'acts',false,NULL),
  ('love-languages','21','I feel hurt and unappreciated when I am overwhelmed and my partner does not help','likert',5,'acts',true,NULL),
  ('love-languages','22','I appreciate when my partner actively looks for ways to make my life easier','likert',5,'acts',false,NULL),
  ('love-languages','23','Actions speak louder than words to me—doing things for me shows love more than saying it','likert',5,'acts',false,NULL),
  ('love-languages','24','When my partner cooks a meal for me or helps with chores, I feel deeply loved','likert',5,'acts',false,NULL),
  ('love-languages','25','I feel most loved when my partner holds my hand, hugs me, or shows physical affection','likert',5,'touch',false,NULL),
  ('love-languages','26','Physical closeness and touch are essential to me feeling connected in the relationship','likert',5,'touch',false,NULL),
  ('love-languages','27','When my partner pulls away from physical touch, I feel rejected and unloved','likert',5,'touch',true,NULL),
  ('love-languages','28','I love cuddling, kissing, and general physical affection throughout the day','likert',5,'touch',false,NULL),
  ('love-languages','29','Physical touch is my primary way of feeling emotionally close to my partner','likert',5,'touch',false,NULL),
  ('love-languages','30','A warm embrace after a long day means more to me than any verbal reassurance','likert',5,'touch',false,NULL),
  ('attachment-style','1','I worry that my partner does not love me as much as I love them','likert',5,'anxiety',false,NULL),
  ('attachment-style','2','I am afraid that my partner might want to leave me','likert',5,'anxiety',false,NULL),
  ('attachment-style','3','I often wish my partner would show more emotion and affection','likert',5,'anxiety',false,NULL),
  ('attachment-style','4','I need a lot of reassurance that my partner loves me','likert',5,'anxiety',false,NULL),
  ('attachment-style','5','I often feel anxious when my partner is not around','likert',5,'anxiety',false,NULL),
  ('attachment-style','6','I often wonder whether my partner really cares about me','likert',5,'anxiety',false,NULL),
  ('attachment-style','7','When my partner does something hurtful, I cannot stop thinking about it','likert',5,'anxiety',false,NULL),
  ('attachment-style','8','I feel jealous when my partner spends time with others','likert',5,'anxiety',false,NULL),
  ('attachment-style','9','I am afraid of being abandoned in this relationship','likert',5,'anxiety',false,NULL),
  ('attachment-style','10','I often feel that my partner does not fully understand me or my needs','likert',5,'anxiety',false,NULL),
  ('attachment-style','11','I find it difficult to get emotionally close to my partner','likert',5,'avoidance',false,NULL),
  ('attachment-style','12','I prefer not to show my partner how I feel deep down','likert',5,'avoidance',false,NULL),
  ('attachment-style','13','I feel comfortable depending on my partner','likert',5,'avoidance',true,NULL),
  ('attachment-style','14','I am comfortable sharing my private thoughts and feelings with my partner','likert',5,'avoidance',true,NULL),
  ('attachment-style','15','I find it hard to trust my partner completely','likert',5,'avoidance',false,NULL),
  ('attachment-style','16','I feel uneasy when my partner wants to be very close','likert',5,'avoidance',false,NULL),
  ('attachment-style','17','I try to avoid too much closeness with my partner','likert',5,'avoidance',false,NULL),
  ('attachment-style','18','When my partner gets too close, I feel the need to pull away','likert',5,'avoidance',false,NULL),
  ('attachment-style','19','I am not very comfortable being depending on others','likert',5,'avoidance',false,NULL),
  ('attachment-style','20','I do not like sharing my inner thoughts and feelings with my partner','likert',5,'avoidance',false,NULL),
  ('communication-style','1','I clearly express my needs and feelings to my partner','likert',5,'expression',false,NULL),
  ('communication-style','2','I use \"I feel\" statements rather than blaming or accusing my partner','likert',5,'expression',false,NULL),
  ('communication-style','3','I can articulate when something is bothering me without escalating into conflict','likert',5,'expression',false,NULL),
  ('communication-style','4','I tend to keep my frustrations to myself until they build up and explode','likert',5,'expression',true,NULL),
  ('communication-style','5','I listen without interrupting when my partner is speaking','likert',5,'listening',false,NULL),
  ('communication-style','6','I ask clarifying questions to make sure I understand what my partner is saying','likert',5,'listening',false,NULL),
  ('communication-style','7','I can tell when my partner is upset even without them explicitly saying so','likert',5,'listening',false,NULL),
  ('communication-style','8','I find myself planning my response while my partner is still talking rather than truly listening','likert',5,'listening',true,NULL),
  ('communication-style','9','I validate my partner feelings even when I disagree with their perspective','likert',5,'validation',false,NULL),
  ('communication-style','10','I acknowledge my partner point of view before offering my own','likert',5,'validation',false,NULL),
  ('communication-style','11','When my partner shares something difficult, I offer comfort and support first','likert',5,'validation',false,NULL),
  ('communication-style','12','I tend to dismiss or minimize my partner feelings when they are upset','likert',5,'validation',true,NULL),
  ('communication-style','13','I take responsibility for my part in conflicts and apologize when I am wrong','likert',5,'accountability',false,NULL),
  ('communication-style','14','I avoid bringing up past conflicts during current disagreements','likert',5,'accountability',false,NULL),
  ('communication-style','15','I can compromise and find middle ground when our needs differ','likert',5,'accountability',false,NULL),
  ('gottman-four-horsemen','1','During disagreements, I criticize my partner character rather than their specific behavior','likert',5,'criticism',true,NULL),
  ('gottman-four-horsemen','2','I use words like \"always\" or \"never\" when describing my partner flaws (e.g., \"You always ignore me\")','likert',5,'criticism',true,NULL),
  ('gottman-four-horsemen','3','I make negative observations about my partner personality as part of arguments','likert',5,'criticism',true,NULL),
  ('gottman-four-horsemen','4','When providing feedback, I focus on the issue at hand rather than attacking my partner character','likert',5,'criticism',false,NULL),
  ('gottman-four-horsemen','5','I express complaints as \"I\" statements (e.g., \"I feel hurt when...\") rather than \"You\" accusations','likert',5,'criticism',false,NULL),
  ('gottman-four-horsemen','6','I show contempt through eye-rolling, sneering, or mocking during conflicts','likert',5,'contempt',true,NULL),
  ('gottman-four-horsemen','7','I use sarcasm or mockery when my partner says something I disagree with','likert',5,'contempt',true,NULL),
  ('gottman-four-horsemen','8','I have used hostile humor or put-downs during arguments','likert',5,'contempt',true,NULL),
  ('gottman-four-horsemen','9','When my partner shares their perspective, I respond with genuine interest and respect','likert',5,'contempt',false,NULL),
  ('gottman-four-horsemen','10','I treat my partner as an equal, even during disagreements','likert',5,'contempt',false,NULL),
  ('gottman-four-horsemen','11','When my partner brings up a concern, I immediately become defensive','likert',5,'defensiveness',true,NULL),
  ('gottman-four-horsemen','12','I make excuses or deflect blame when my partner points out something I did wrong','likert',5,'defensiveness',true,NULL),
  ('gottman-four-horsemen','13','I respond to my partner criticism with \"Whatever\" or by walking away','likert',5,'defensiveness',true,NULL),
  ('gottman-four-horsemen','14','When my partner raises an issue, I can acknowledge their perspective even if I disagree','likert',5,'defensiveness',false,NULL),
  ('gottman-four-horsemen','15','I take responsibility for my mistakes rather than immediately deflecting','likert',5,'defensiveness',false,NULL),
  ('gottman-four-horsemen','16','I withdraw or shut down emotionally when conflicts become too intense','likert',5,'stonewalling',true,NULL),
  ('gottman-four-horsemen','17','I refuse to engage in conversation or give my partner any response during arguments','likert',5,'stonewalling',true,NULL),
  ('gottman-four-horsemen','18','When I am overwhelmed, I need to step away to calm down before continuing the conversation','likert',5,'stonewalling',false,NULL),
  ('gottman-four-horsemen','19','I make repair attempts (e.g., \"Can we pause and come back to this?\") when things get heated','likert',5,'stonewalling',false,NULL),
  ('gottman-four-horsemen','20','I stay engaged with my partner even during difficult conversations','likert',5,'stonewalling',false,NULL),
  ('conflict-resolution','1','I prefer to avoid conflicts rather than address them directly','likert',5,'avoidance',true,NULL),
  ('conflict-resolution','2','I拖延 discussing difficult topics hoping they will resolve on their own','likert',5,'avoidance',true,NULL),
  ('conflict-resolution','3','When a conflict arises, I prefer to address it rather than let it fester','likert',5,'avoidance',false,NULL),
  ('conflict-resolution','4','I can discuss sensitive topics openly without trying to escape the conversation','likert',5,'avoidance',false,NULL),
  ('conflict-resolution','5','I address issues as they come rather than letting them build up','likert',5,'avoidance',false,NULL),
  ('conflict-resolution','6','I can discuss difficult topics without becoming angry or upset','likert',5,'composure',false,NULL),
  ('conflict-resolution','7','When my partner raises a concern, I can stay calm and listen','likert',5,'composure',false,NULL),
  ('conflict-resolution','8','I can stay emotionally regulated even when my partner is upset','likert',5,'composure',false,NULL),
  ('conflict-resolution','9','I have raised my voice or said things I regret during conflicts','likert',5,'composure',true,NULL),
  ('conflict-resolution','10','I need time to cool down before discussing problems','likert',5,'composure',false,NULL),
  ('conflict-resolution','11','I seek compromise during disagreements rather than trying to win','likert',5,'compromise',false,NULL),
  ('conflict-resolution','12','I can find solutions that work for both of us, not just me','likert',5,'compromise',false,NULL),
  ('conflict-resolution','13','I am willing to give up my position if my partner has a compelling point','likert',5,'compromise',false,NULL),
  ('conflict-resolution','14','We often struggle to find middle ground when our needs differ','likert',5,'compromise',true,NULL),
  ('conflict-resolution','15','I look for win-win solutions rather than demanding my way','likert',5,'compromise',false,NULL),
  ('conflict-resolution','16','I can see my partner point of view even when we disagree','likert',5,'empathy',false,NULL),
  ('conflict-resolution','17','I try to understand why my partner feels the way they do before responding','likert',5,'empathy',false,NULL),
  ('conflict-resolution','18','I feel heard during conflicts with my partner','likert',5,'empathy',false,NULL),
  ('conflict-resolution','19','My partner understands my perspective even when we disagree','likert',5,'empathy',false,NULL),
  ('conflict-resolution','20','Conflicts feel threatening to our relationship rather than normal','likert',5,'empathy',true,NULL),
  ('conflict-resolution','21','I make repair attempts when things get tense (e.g., lighten the mood, apologize)','likert',5,'repair',false,NULL),
  ('conflict-resolution','22','After a conflict, I follow up to ensure we are both okay','likert',5,'repair',false,NULL),
  ('conflict-resolution','23','We can laugh together even after disagreements','likert',5,'repair',false,NULL),
  ('conflict-resolution','24','I apologize when I am wrong, even for small things','likert',5,'repair',false,NULL),
  ('conflict-resolution','25','We reconcile after conflicts and move forward without lingering resentment','likert',5,'repair',false,NULL),
  ('values-alignment','1','My partner and I share similar views on what family means and how to prioritize family','likert',5,'family',false,NULL),
  ('values-alignment','2','We agree on how much time to spend with extended family vs. alone time together','likert',5,'family',false,NULL),
  ('values-alignment','3','We have compatible expectations about caring for aging parents','likert',5,'family',false,NULL),
  ('values-alignment','4','We align on how to handle family traditions and create new ones together','likert',5,'family',false,NULL),
  ('values-alignment','5','My family values align with my partner family values','likert',5,'family',false,NULL),
  ('values-alignment','6','We have aligned financial goals and agree on how to handle money','likert',5,'finance',false,NULL),
  ('values-alignment','7','We agree on how much to spend vs. save and our spending priorities','likert',5,'finance',false,NULL),
  ('values-alignment','8','We share similar attitudes about taking on debt (e.g., loans, credit cards)','likert',5,'finance',false,NULL),
  ('values-alignment','9','We align on how much to spend on gifts, travel, and discretionary items','likert',5,'finance',false,NULL),
  ('values-alignment','10','We agree on financial transparency and how to handle shared vs. separate finances','likert',5,'finance',false,NULL),
  ('values-alignment','11','Our spiritual or religious beliefs are compatible','likert',5,'spirituality',false,NULL),
  ('values-alignment','12','We align on how important spirituality/religion is in our daily lives','likert',5,'spirituality',false,NULL),
  ('values-alignment','13','We share similar ethical values and views on what is right and wrong','likert',5,'spirituality',false,NULL),
  ('values-alignment','14','We agree on how to navigate differences in spiritual/religious beliefs','likert',5,'spirituality',false,NULL),
  ('values-alignment','15','Our core values and beliefs are aligned even if our spiritual practices differ','likert',5,'spirituality',false,NULL),
  ('values-alignment','16','We agree on work-life balance priorities and how much time to dedicate to careers','likert',5,'lifestyle',false,NULL),
  ('values-alignment','17','We share similar views on health, wellness, and how we take care of ourselves','likert',5,'lifestyle',false,NULL),
  ('values-alignment','18','We align on how we want to spend our leisure time and hobbies','likert',5,'lifestyle',false,NULL),
  ('values-alignment','19','We agree on living arrangements (e.g., city vs. suburbs, apartment vs. house)','likert',5,'lifestyle',false,NULL),
  ('values-alignment','20','Our lifestyle preferences (e.g., social, active, introverted) are compatible','likert',5,'lifestyle',false,NULL),
  ('values-alignment','21','We share similar views on gender roles and expectations in the relationship','likert',5,'relationships',false,NULL),
  ('values-alignment','22','We align on how to divide household responsibilities','likert',5,'relationships',false,NULL),
  ('values-alignment','23','We agree on how to handle decisions about the relationship (e.g., equal partnership)','likert',5,'relationships',false,NULL),
  ('values-alignment','24','Our social and political values are compatible','likert',5,'relationships',false,NULL),
  ('values-alignment','25','We align on how much independence and autonomy each person needs in the relationship','likert',5,'relationships',false,NULL),
  ('values-alignment','26','We have compatible views on children and whether/how to become parents','likert',5,'goals',false,NULL),
  ('values-alignment','27','Our long-term life goals are aligned (e.g., where we want to live, career aspirations)','likert',5,'goals',false,NULL),
  ('values-alignment','28','We share similar ambitions for personal growth and self-improvement','likert',5,'goals',false,NULL),
  ('values-alignment','29','We value similar things in life and have a shared vision for our future','likert',5,'goals',false,NULL),
  ('values-alignment','30','We respect each other individual values even where they differ','likert',5,'goals',false,NULL),
  ('emotional-intelligence','1','I can identify and name my emotions as I am experiencing them','likert',5,'selfAwareness',false,NULL),
  ('emotional-intelligence','2','I understand why I feel the way I do in most situations','likert',5,'selfAwareness',false,NULL),
  ('emotional-intelligence','3','I recognize how my emotions affect my behavior and reactions','likert',5,'selfAwareness',false,NULL),
  ('emotional-intelligence','4','I am aware of my emotional triggers and what sets me off','likert',5,'selfAwareness',false,NULL),
  ('emotional-intelligence','5','I can distinguish between different emotional states (e.g., fear vs. anxiety vs. worry)','likert',5,'selfAwareness',false,NULL),
  ('emotional-intelligence','6','I have good insight into my own strengths and weaknesses','likert',5,'selfAwareness',false,NULL),
  ('emotional-intelligence','7','I can calm myself down when I am upset or angry','likert',5,'selfRegulation',false,NULL),
  ('emotional-intelligence','8','I delay reacting in the moment to think before responding','likert',5,'selfRegulation',false,NULL),
  ('emotional-intelligence','9','I can handle criticism without becoming defensive or upset','likert',5,'selfRegulation',false,NULL),
  ('emotional-intelligence','10','I adapt well to unexpected changes and challenges','likert',5,'selfRegulation',false,NULL),
  ('emotional-intelligence','11','I manage stress effectively and do not let it overwhelm me easily','likert',5,'selfRegulation',false,NULL),
  ('emotional-intelligence','12','I keep my emotions in check even in difficult or high-pressure situations','likert',5,'selfRegulation',false,NULL),
  ('emotional-intelligence','13','I can sense how my partner is feeling even when they do not say it directly','likert',5,'empathy',false,NULL),
  ('emotional-intelligence','14','I understand my partner emotional perspective even when I disagree','likert',5,'empathy',false,NULL),
  ('emotional-intelligence','15','I respond to my partner emotions with care and concern','likert',5,'empathy',false,NULL),
  ('emotional-intelligence','16','I can put myself in my partner shoes and see things from their perspective','likert',5,'empathy',false,NULL),
  ('emotional-intelligence','17','I notice when my partner is struggling and offer support proactively','likert',5,'empathy',false,NULL),
  ('emotional-intelligence','18','I validate my partner feelings rather than dismissing or minimizing them','likert',5,'empathy',false,NULL),
  ('emotional-intelligence','19','I communicate clearly and effectively with my partner','likert',5,'socialSkills',false,NULL),
  ('emotional-intelligence','20','I can navigate disagreements without damaging the relationship','likert',5,'socialSkills',false,NULL),
  ('emotional-intelligence','21','I am good at reading non-verbal cues and body language','likert',5,'socialSkills',false,NULL),
  ('emotional-intelligence','22','I support my partner through difficult emotions without trying to fix everything','likert',5,'socialSkills',false,NULL),
  ('emotional-intelligence','23','I can express difficult emotions in a constructive way','likert',5,'socialSkills',false,NULL),
  ('emotional-intelligence','24','I maintain emotional intimacy even during stressful periods','likert',5,'socialSkills',false,NULL),
  ('intimacy-closeness','1','I feel safe sharing my deepest fears and insecurities with my partner','likert',5,'emotional',false,NULL),
  ('intimacy-closeness','2','I can be fully authentic with my partner without fear of judgment','likert',5,'emotional',false,NULL),
  ('intimacy-closeness','3','My partner knows the real me, including my vulnerabilities','likert',5,'emotional',false,NULL),
  ('intimacy-closeness','4','I feel emotionally supported during difficult times','likert',5,'emotional',false,NULL),
  ('intimacy-closeness','5','We share our hopes, dreams, and aspirations with each other','likert',5,'emotional',false,NULL),
  ('intimacy-closeness','6','I feel a deep sense of closeness and connection with my partner','likert',5,'emotional',false,NULL),
  ('intimacy-closeness','7','We can sit in comfortable silence and still feel connected','likert',5,'emotional',false,NULL),
  ('intimacy-closeness','8','My partner celebrates my successes and supports me through failures','likert',5,'emotional',false,NULL),
  ('intimacy-closeness','9','I feel accepted for who I am, including my flaws and imperfections','likert',5,'emotional',false,NULL),
  ('intimacy-closeness','10','I feel satisfied with the amount of physical affection in our relationship','likert',5,'physical',false,NULL),
  ('intimacy-closeness','11','Physical touch (hugging, kissing, cuddling) is an important part of our daily connection','likert',5,'physical',false,NULL),
  ('intimacy-closeness','12','We are comfortable being physically close and intimate','likert',5,'physical',false,NULL),
  ('intimacy-closeness','13','Physical intimacy is fulfilling and satisfying for both of us','likert',5,'physical',false,NULL),
  ('intimacy-closeness','14','I feel desired by my partner and find them physically attractive','likert',5,'physical',false,NULL),
  ('intimacy-closeness','15','We can be physically affectionate without it always leading to sex','likert',5,'physical',false,NULL),
  ('intimacy-closeness','16','I feel comfortable initiating physical touch with my partner','likert',5,'physical',false,NULL),
  ('intimacy-closeness','17','Our physical intimacy has deepened over time rather than faded','likert',5,'physical',false,NULL),
  ('intimacy-closeness','18','We prioritize physical closeness even when life gets busy','likert',5,'physical',false,NULL),
  ('intimacy-closeness','19','I enjoy deep, meaningful conversations with my partner','likert',5,'intellectual',false,NULL),
  ('intimacy-closeness','20','We share similar interests and enjoy discussing ideas together','likert',5,'intellectual',false,NULL),
  ('intimacy-closeness','21','My partner challenges my thinking and helps me grow intellectually','likert',5,'intellectual',false,NULL),
  ('intimacy-closeness','22','We can disagree intellectually without damaging our connection','likert',5,'intellectual',false,NULL),
  ('intimacy-closeness','23','I feel stimulated and engaged when we talk about topics of mutual interest','likert',5,'intellectual',false,NULL),
  ('intimacy-closeness','24','We enjoy learning new things together and exploring new ideas','likert',5,'intellectual',false,NULL),
  ('intimacy-closeness','25','My partner respects my opinions and values my perspective','likert',5,'intellectual',false,NULL),
  ('intimacy-closeness','26','We have engaging conversations about life, philosophy, and the world','likert',5,'intellectual',false,NULL),
  ('intimacy-closeness','27','I feel intellectually connected to my partner beyond just everyday topics','likert',5,'intellectual',false,NULL),
  ('trust-vulnerability','1','I trust my partner completely and believe they have my best interests at heart','likert',5,'trust',false,NULL),
  ('trust-vulnerability','2','I believe my partner is honest with me even when the truth is difficult','likert',5,'trust',false,NULL),
  ('trust-vulnerability','3','I feel confident that my partner will follow through on their commitments','likert',5,'trust',false,NULL),
  ('trust-vulnerability','4','I do not worry about my partner being unfaithful or betraying me','likert',5,'trust',false,NULL),
  ('trust-vulnerability','5','My partner has earned my trust through consistent actions over time','likert',5,'trust',false,NULL),
  ('trust-vulnerability','6','I can rely on my partner to be there when I need them','likert',5,'trust',false,NULL),
  ('trust-vulnerability','7','I feel safe being vulnerable with my partner, even with my biggest fears','likert',5,'vulnerability',false,NULL),
  ('trust-vulnerability','8','I can share my failures and insecurities without fear of being judged','likert',5,'vulnerability',false,NULL),
  ('trust-vulnerability','9','I let my guard down with my partner and show my authentic self','likert',5,'vulnerability',false,NULL),
  ('trust-vulnerability','10','I can ask for help and support from my partner without feeling weak','likert',5,'vulnerability',false,NULL),
  ('trust-vulnerability','11','I express my needs openly rather than expecting my partner to read my mind','likert',5,'vulnerability',false,NULL),
  ('trust-vulnerability','12','I let my partner see me at my worst without fear of rejection','likert',5,'vulnerability',false,NULL),
  ('trust-vulnerability','13','I feel emotionally safe to be myself around my partner','likert',5,'safety',false,NULL),
  ('trust-vulnerability','14','My partner creates an environment where I feel accepted and valued','likert',5,'safety',false,NULL),
  ('trust-vulnerability','15','I do not need to protect myself from criticism or ridicule from my partner','likert',5,'safety',false,NULL),
  ('trust-vulnerability','16','When I am hurting, my partner responds with compassion rather than dismissal','likert',5,'safety',false,NULL),
  ('trust-vulnerability','17','I feel comfortable expressing disagreement without fearing emotional retaliation','likert',5,'safety',false,NULL),
  ('trust-vulnerability','18','Our relationship feels like a safe haven where I can be fully myself','likert',5,'safety',false,NULL),
  ('financial-values','1','I am comfortable discussing money and financial topics openly with my partner','likert',5,'attitudes',false,NULL),
  ('financial-values','2','I view money as a tool for building a life together rather than a source of conflict','likert',5,'attitudes',false,NULL),
  ('financial-values','3','My partner and I share similar attitudes about spending and saving','likert',5,'attitudes',false,NULL),
  ('financial-values','4','I believe financial transparency is essential in our relationship','likert',5,'attitudes',false,NULL),
  ('financial-values','5','I feel comfortable talking about money stress with my partner','likert',5,'attitudes',false,NULL),
  ('financial-values','6','I have positive associations with money and financial discussions','likert',5,'attitudes',false,NULL),
  ('financial-values','7','We discuss our financial situation regularly, not just when there is a problem','likert',5,'communication',false,NULL),
  ('financial-values','8','We make major financial decisions together after careful discussion','likert',5,'communication',false,NULL),
  ('financial-values','9','I feel heard when discussing financial concerns with my partner','likert',5,'communication',false,NULL),
  ('financial-values','10','We can disagree about money without the conversation turning hostile','likert',5,'communication',false,NULL),
  ('financial-values','11','My partner considers my financial perspective when making spending decisions','likert',5,'communication',false,NULL),
  ('financial-values','12','We have shared short-term and long-term financial goals','likert',5,'goals',false,NULL),
  ('financial-values','13','We align on how much to save vs. spend and our savings priorities','likert',5,'goals',false,NULL),
  ('financial-values','14','We agree on major financial milestones (e.g., buying a home, retirement)','likert',5,'goals',false,NULL),
  ('financial-values','15','We work together as a team to achieve our financial goals','likert',5,'goals',false,NULL),
  ('financial-values','16','I trust my partner to handle finances responsibly','likert',5,'goals',false,NULL),
  ('financial-values','17','We track our spending and have a clear picture of our finances','likert',5,'habits',false,NULL),
  ('financial-values','18','We budget together and review our financial progress regularly','likert',5,'habits',false,NULL),
  ('financial-values','19','Our spending habits are compatible and we rarely disagree about purchases','likert',5,'habits',false,NULL),
  ('financial-values','20','We have an emergency fund or plan for unexpected expenses','likert',5,'habits',false,NULL),
  ('financial-values','21','We discuss purchases over a certain threshold before making them','likert',5,'habits',false,NULL),
  ('financial-values','22','Financial stress does not negatively impact our relationship','likert',5,'habits',false,NULL),
  ('sexual-compatibility','1','My partner and I have similar levels of sexual desire','likert',5,'desire',false,NULL),
  ('sexual-compatibility','2','I feel satisfied with the frequency of our sexual intimacy','likert',5,'desire',false,NULL),
  ('sexual-compatibility','3','I can talk openly with my partner about my sexual needs and desires','likert',5,'desire',false,NULL),
  ('sexual-compatibility','4','My partner makes me feel desired and attractive','likert',5,'desire',false,NULL),
  ('sexual-compatibility','5','We are both comfortable with the pace of our sexual relationship','likert',5,'desire',false,NULL),
  ('sexual-compatibility','6','I feel comfortable initiating sex with my partner','likert',5,'desire',false,NULL),
  ('sexual-compatibility','7','I can openly discuss what I enjoy and do not enjoy sexually','likert',5,'communication',false,NULL),
  ('sexual-compatibility','8','My partner listens and responds positively when I share sexual feedback','likert',5,'communication',false,NULL),
  ('sexual-compatibility','9','We can discuss sexual topics without feeling embarrassed or uncomfortable','likert',5,'communication',false,NULL),
  ('sexual-compatibility','10','I feel comfortable telling my partner if something is not working for me','likert',5,'communication',false,NULL),
  ('sexual-compatibility','11','We explore new things together and discuss trying new experiences','likert',5,'communication',false,NULL),
  ('sexual-compatibility','12','My partner asks about my preferences and follows up on my feedback','likert',5,'communication',false,NULL),
  ('sexual-compatibility','13','I feel completely safe expressing my boundaries around sex','likert',5,'boundaries',false,NULL),
  ('sexual-compatibility','14','My partner respects my boundaries without question or pressure','likert',5,'boundaries',false,NULL),
  ('sexual-compatibility','15','I feel comfortable saying no to sex or certain sexual activities','likert',5,'boundaries',false,NULL),
  ('sexual-compatibility','16','We have an ongoing conversation about consent that feels natural','likert',5,'boundaries',false,NULL),
  ('sexual-compatibility','17','I trust my partner to respect my physical and emotional boundaries','likert',5,'boundaries',false,NULL),
  ('sexual-compatibility','18','My partner never makes me feel guilty for setting boundaries','likert',5,'boundaries',false,NULL),
  ('sexual-compatibility','19','I feel sexually fulfilled in our relationship','likert',5,'satisfaction',false,NULL),
  ('sexual-compatibility','20','Our sexual connection has improved or deepened over time','likert',5,'satisfaction',false,NULL),
  ('sexual-compatibility','21','I feel emotionally connected to my partner during physical intimacy','likert',5,'satisfaction',false,NULL),
  ('sexual-compatibility','22','We prioritize our sexual relationship even during busy or stressful periods','likert',5,'satisfaction',false,NULL),
  ('sexual-compatibility','23','I feel comfortable being vulnerable and intimate with my partner','likert',5,'satisfaction',false,NULL),
  ('sexual-compatibility','24','Our sexual relationship feels satisfying for both of us','likert',5,'satisfaction',false,NULL),
  ('sexual-compatibility','25','I am happy with how we balance emotional and physical intimacy','likert',5,'satisfaction',false,NULL),
  ('shared-meaning','1','We have established meaningful rituals together (e.g., date night, morning coffee)','likert',5,'rituals',false,NULL),
  ('shared-meaning','2','We create new traditions together that feel special to us as a couple','likert',5,'rituals',false,NULL),
  ('shared-meaning','3','We have rituals that mark important occasions (anniversaries, milestones)','likert',5,'rituals',false,NULL),
  ('shared-meaning','4','Our daily routines include elements that strengthen our connection','likert',5,'rituals',false,NULL),
  ('shared-meaning','5','We have inside jokes, nicknames, or references that are unique to us','likert',5,'rituals',false,NULL),
  ('shared-meaning','6','We regularly reflect together on our relationship and what is working','likert',5,'rituals',false,NULL),
  ('shared-meaning','7','We have clear, shared goals for our future together','likert',5,'goals',false,NULL),
  ('shared-meaning','8','We regularly discuss and update our life plans together','likert',5,'goals',false,NULL),
  ('shared-meaning','9','Our individual goals support and align with each other','likert',5,'goals',false,NULL),
  ('shared-meaning','10','We work together as a team to achieve our shared dreams','likert',5,'goals',false,NULL),
  ('shared-meaning','11','We have discussed and agree on major life decisions (career, location, family)','likert',5,'goals',false,NULL),
  ('shared-meaning','12','We inspire each other to grow and pursue our individual aspirations','likert',5,'goals',false,NULL),
  ('shared-meaning','13','We have clear, agreed-upon roles and responsibilities in our partnership','likert',5,'roles',false,NULL),
  ('shared-meaning','14','We share responsibilities in a way that feels fair and balanced','likert',5,'roles',false,NULL),
  ('shared-meaning','15','We both contribute to decisions about our shared life','likert',5,'roles',false,NULL),
  ('shared-meaning','16','We can discuss and adjust our roles as life circumstances change','likert',5,'roles',false,NULL),
  ('shared-meaning','17','We support each other roles as individuals beyond the partnership','likert',5,'roles',false,NULL),
  ('shared-meaning','18','We are a unified team facing lifes challenges together','likert',5,'roles',false,NULL),
  ('shared-meaning','19','We have discussed what kind of life we want to build together','likert',5,'legacy',false,NULL),
  ('shared-meaning','20','We want to create something meaningful that extends beyond ourselves','likert',5,'legacy',false,NULL),
  ('shared-meaning','21','We share a vision for how we want to contribute to the world','likert',5,'legacy',false,NULL),
  ('shared-meaning','22','We have discussed how we want to raise future generations (if applicable)','likert',5,'legacy',false,NULL),
  ('shared-meaning','23','We care about building a legacy together that reflects our values','likert',5,'legacy',false,NULL),
  ('shared-meaning','24','We want to be remembered as a couple who made a positive impact','likert',5,'legacy',false,NULL),
  ('shared-meaning','25','We grow together rather than apart over time','likert',5,'growth',false,NULL),
  ('shared-meaning','26','We encourage and support each other personal development','likert',5,'growth',false,NULL),
  ('shared-meaning','27','We learn new things together and explore new experiences as a couple','likert',5,'growth',false,NULL),
  ('shared-meaning','28','Our relationship has evolved and deepened over time','likert',5,'growth',false,NULL),
  ('shared-meaning','29','We adapt to changes together and emerge stronger from challenges','likert',5,'growth',false,NULL),
  ('shared-meaning','30','We invest in our relationship as much as we invest in ourselves individually','likert',5,'growth',false,NULL),
  ('relationship-satisfaction','1','My partner and I agree on how to handle household responsibilities','likert',5,'consensus',false,NULL),
  ('relationship-satisfaction','2','We see eye-to-eye on most major life decisions and priorities','likert',5,'consensus',false,NULL),
  ('relationship-satisfaction','3','We share similar views on how we want to live our lives','likert',5,'consensus',false,NULL),
  ('relationship-satisfaction','4','We agree on how to manage finances and financial priorities','likert',5,'consensus',false,NULL),
  ('relationship-satisfaction','5','We align on values and beliefs that matter most in our relationship','likert',5,'consensus',false,NULL),
  ('relationship-satisfaction','6','I am satisfied with the overall quality of our relationship','likert',5,'satisfaction',false,NULL),
  ('relationship-satisfaction','7','I am happy with how our relationship has turned out so far','likert',5,'satisfaction',false,NULL),
  ('relationship-satisfaction','8','Our relationship meets my expectations and needs','likert',5,'satisfaction',false,NULL),
  ('relationship-satisfaction','9','I would choose the same partner if I could do it over again','likert',5,'satisfaction',false,NULL),
  ('relationship-satisfaction','10','Overall, I feel our relationship is successful','likert',5,'satisfaction',false,NULL),
  ('relationship-satisfaction','11','We enjoy spending time together and feel a strong sense of closeness','likert',5,'cohesion',false,NULL),
  ('relationship-satisfaction','12','We work well as a team and support each other through challenges','likert',5,'cohesion',false,NULL),
  ('relationship-satisfaction','13','We share a strong connection and feel we belong together','likert',5,'cohesion',false,NULL),
  ('relationship-satisfaction','14','We make a great team and can count on each other no matter what','likert',5,'cohesion',false,NULL),
  ('stress-coping','1','I can manage my stress levels effectively without them affecting my relationship','likert',5,'individual',false,NULL),
  ('stress-coping','2','When stressed, I use healthy coping strategies (exercise, talking, journaling)','likert',5,'individual',false,NULL),
  ('stress-coping','3','I recognize when stress is affecting my mood and behavior','likert',5,'individual',false,NULL),
  ('stress-coping','4','I do not take my stress out on my partner when things get difficult','likert',5,'individual',false,NULL),
  ('stress-coping','5','I can separate work stress from my home life and relationship','likert',5,'individual',false,NULL),
  ('stress-coping','6','I maintain my own well-being even during stressful periods','likert',5,'individual',false,NULL),
  ('stress-coping','7','I know when I need support and can ask my partner for help','likert',5,'individual',false,NULL),
  ('stress-coping','8','My partner is supportive when I am going through stressful periods','likert',5,'partner',false,NULL),
  ('stress-coping','9','My partner gives me space when I need it but also checks in on me','likert',5,'partner',false,NULL),
  ('stress-coping','10','I can lean on my partner for emotional support during hard times','likert',5,'partner',false,NULL),
  ('stress-coping','11','My partner helps me see stressful situations more clearly','likert',5,'partner',false,NULL),
  ('stress-coping','12','When I am stressed, my partner does not make it worse with their own reactions','likert',5,'partner',false,NULL),
  ('stress-coping','13','My partner is patient with me when stress makes me less present','likert',5,'partner',false,NULL),
  ('stress-coping','14','I feel comfortable sharing my stress with my partner without judgment','likert',5,'partner',false,NULL),
  ('stress-coping','15','We handle financial stress together as a team','likert',5,'team',false,NULL),
  ('stress-coping','16','We support each other through work-related stress and career challenges','likert',5,'team',false,NULL),
  ('stress-coping','17','When external pressures threaten our relationship, we face them together','likert',5,'team',false,NULL),
  ('stress-coping','18','We can talk about stress without it turning into conflict','likert',5,'team',false,NULL),
  ('stress-coping','19','Our relationship remains stable even when external stressors increase','likert',5,'team',false,NULL),
  ('stress-coping','20','We have strategies for coping with stress that we practice together','likert',5,'team',false,NULL),
  ('fun-personality','1','I consider myself a playful person who enjoys laughter and lighthearted moments','likert',5,'playfulness',false,NULL),
  ('fun-personality','2','My partner and I enjoy being silly and playful together','likert',5,'playfulness',false,NULL),
  ('fun-personality','3','We can laugh at ourselves and not take everything so seriously','likert',5,'playfulness',false,NULL),
  ('fun-personality','4','Our relationship feels fun and enjoyable most of the time','likert',5,'playfulness',false,NULL),
  ('fun-personality','5','We retain a sense of childlike wonder and excitement together','likert',5,'playfulness',false,NULL),
  ('fun-personality','6','We have shared hobbies or activities that we enjoy doing together','likert',5,'activities',false,NULL),
  ('fun-personality','7','We regularly try new activities or explore new experiences together','likert',5,'activities',false,NULL),
  ('fun-personality','8','We enjoy spending quality time together doing things we both love','likert',5,'activities',false,NULL),
  ('fun-personality','9','We make time for fun and recreation even when life is busy','likert',5,'activities',false,NULL),
  ('fun-personality','10','Our shared activities bring us closer and create lasting memories','likert',5,'activities',false,NULL),
  ('fun-personality','11','We share a similar sense of humor and make each other laugh','likert',5,'humor',false,NULL),
  ('fun-personality','12','Laughter is a big part of our relationship','likert',5,'humor',false,NULL),
  ('fun-personality','13','We can laugh together even during difficult times','likert',5,'humor',false,NULL),
  ('fun-personality','14','We use humor to lighten tense moments and navigate conflict','likert',5,'humor',false,NULL),
  ('fun-personality','15','We enjoy spontaneous adventures and trying new things together','likert',5,'adventure',false,NULL),
  ('fun-personality','16','We share a spirit of curiosity and love exploring together','likert',5,'adventure',false,NULL),
  ('fun-personality','17','We plan exciting experiences and look forward to them together','likert',5,'adventure',false,NULL),
  ('fun-personality','18','We have a bucket list or goals that include adventurous experiences together','likert',5,'adventure',false,NULL),
  ('appreciation-gratitude','1','I regularly tell my partner things I appreciate about them','likert',5,'expression',false,NULL),
  ('appreciation-gratitude','2','I express gratitude for the small things my partner does daily','likert',5,'expression',false,NULL),
  ('appreciation-gratitude','3','I show appreciation for my partner more often than I take them for granted','likert',5,'expression',false,NULL),
  ('appreciation-gratitude','4','I make it a habit to notice and acknowledge my partner efforts','likert',5,'expression',false,NULL),
  ('appreciation-gratitude','5','I express thanks and gratitude rather than assuming my partner knows how I feel','likert',5,'expression',false,NULL),
  ('appreciation-gratitude','6','I recognize and acknowledge my partner contributions to our relationship','likert',5,'recognition',false,NULL),
  ('appreciation-gratitude','7','I celebrate my partner successes and accomplishments','likert',5,'recognition',false,NULL),
  ('appreciation-gratitude','8','I make my partner feel valued and seen for who they are','likert',5,'recognition',false,NULL),
  ('appreciation-gratitude','9','I notice the effort my partner puts into our relationship and show I notice','likert',5,'recognition',false,NULL),
  ('appreciation-gratitude','10','My partner makes me feel appreciated and valued','likert',5,'recognition',false,NULL),
  ('appreciation-gratitude','11','I focus on what I love about my partner rather than their flaws','likert',5,'positivity',false,NULL),
  ('appreciation-gratitude','12','I am grateful for our relationship and tell my partner that','likert',5,'positivity',false,NULL),
  ('appreciation-gratitude','13','I regularly reflect on the positive aspects of our relationship','likert',5,'positivity',false,NULL),
  ('appreciation-gratitude','14','I end each day with gratitude for my partner presence in my life','likert',5,'positivity',false,NULL),
  ('appreciation-gratitude','15','Gratitude and appreciation are natural parts of how we communicate','likert',5,'positivity',false,NULL)
ON CONFLICT (assessment_id, question_key) DO NOTHING;