-- BOND Onboarding Seed — questions and scoring stored in app code
-- The 4 onboarding questions and all scoring logic live in:
--   mobile/utils/onboardingAssessment.js
--
-- The DB tables store results after submission:
--   onboarding_assessments (answers)
--   onboarding_assessment_patterns (4 patterns — already seeded in bond_seed.sql)
--   onboarding_assessment_dimensions (dimensions — already seeded in bond_seed.sql)
--   onboarding_assessment_recommendation_rules (4 rules — already seeded in bond_seed.sql)
--
-- This file is a reference marker. The onboarding scoring is entirely client-side.
-- No additional DB seeds are needed for the onboarding flow.