// Complete Assessment Library - All 16 Assessments with Full Question Banks
// BOND App v2.0

// ============================================================================
// ASSESSMENT DEFINITIONS
// ============================================================================

export const allAssessments = [
  {
    id: 'love-languages',
    name: 'Love Languages',
    framework: 'Five Love Languages (Gary Chapman)',
    description: 'Discover how you and your partner prefer to give and receive love. Understanding these preferences can transform how you connect daily.',
    estimatedTime: '8 min',
    questionsCount: 30,
    icon: '❤️',
    category: 'connection',
    introTitle: 'How do you experience love?',
    introDescription: 'This assessment reveals your primary love language and helps you understand how you prefer to give and receive affection.',
    resultDescription: 'Your love language profile shows how you most naturally express and receive love.',
  },
  {
    id: 'attachment-style',
    name: 'Attachment Style',
    framework: 'Attachment Theory (Bowlby & Ainsworth)',
    description: 'Understand your attachment patterns and how they shape your relationship dynamics, emotional responses, and closeness with your partner.',
    estimatedTime: '6 min',
    questionsCount: 20,
    icon: '🔗',
    category: 'emotional',
    introTitle: 'How do you connect emotionally?',
    introDescription: 'Your attachment style influences how you seek closeness, handle anxiety, and maintain independence in relationships.',
    resultDescription: 'Your attachment style shapes how you bond and respond to intimacy.',
  },
  {
    id: 'communication-style',
    name: 'Communication Style',
    framework: 'Nonviolent Communication (Rosenberg)',
    description: 'Explore how you communicate needs, feelings, and boundaries. Learn patterns that strengthen or strain your connection.',
    estimatedTime: '5 min',
    questionsCount: 15,
    icon: '💬',
    category: 'communication',
    introTitle: 'How do you express yourself?',
    introDescription: 'Effective communication is the foundation of healthy relationships. Discover your strengths and growth areas.',
    resultDescription: 'Your communication profile reveals how you navigate conversations and connect with your partner.',
  },
  {
    id: 'gottman-four-horsemen',
    name: 'Four Horsemen',
    framework: 'Gottman Method',
    description: 'Identify destructive communication patterns that can damage your relationship. Learn to recognize and replace them with healthy alternatives.',
    estimatedTime: '7 min',
    questionsCount: 20,
    icon: '🐴',
    category: 'communication',
    introTitle: 'Are there hidden patterns hurting your connection?',
    introDescription: 'The Four Horsemen are criticism, contempt, defensiveness, and stonewalling. Learn if these patterns exist in your relationship.',
    resultDescription: 'Understanding these patterns helps you build healthier communication habits.',
  },
  {
    id: 'conflict-resolution',
    name: 'Conflict Resolution',
    framework: 'Gottman Conflict Management',
    description: 'Discover your conflict resolution styles and learn how to navigate disagreements in ways that strengthen rather than strain your relationship.',
    estimatedTime: '8 min',
    questionsCount: 25,
    icon: '⚡',
    category: 'conflict',
    introTitle: 'How do you handle disagreements?',
    introDescription: 'Every couple conflicts, but it is how you navigate those moments that determines relationship health.',
    resultDescription: 'Your conflict style reveals strengths and strategies for healthier disagreements.',
  },
  {
    id: 'values-alignment',
    name: 'Values Alignment',
    framework: 'Acceptance & Commitment Therapy (ACT)',
    description: 'Explore shared values and life priorities. Understanding what matters most to both of you helps align your vision for the future.',
    estimatedTime: '10 min',
    questionsCount: 30,
    icon: '🎯',
    category: 'values',
    introTitle: 'What truly matters to you both?',
    introDescription: 'Shared values create shared purpose. This assessment explores where your values align and where they differ.',
    resultDescription: 'Your values profile shows areas of alignment and opportunities for deeper understanding.',
  },
  {
    id: 'emotional-intelligence',
    name: 'Emotional Intelligence',
    framework: 'Goleman EQ Model',
    description: 'Assess your emotional awareness, regulation, and responsiveness. High emotional intelligence is linked to stronger, more resilient relationships.',
    estimatedTime: '8 min',
    questionsCount: 24,
    icon: '🧠',
    category: 'emotional',
    introTitle: 'How well do you understand and manage emotions?',
    introDescription: 'Emotional intelligence includes recognizing your own feelings, understanding your partner, and responding thoughtfully rather than reactively.',
    resultDescription: 'Your EQ profile highlights emotional strengths and growth areas for deeper connection.',
  },
  {
    id: 'intimacy-closeness',
    name: 'Intimacy & Closeness',
    framework: 'Sternberg Triangular Theory',
    description: 'Measure emotional, physical, and intellectual intimacy levels. True intimacy combines all three dimensions for deep connection.',
    estimatedTime: '9 min',
    questionsCount: 27,
    icon: '💕',
    category: 'intimacy',
    introTitle: 'How intimate is your connection?',
    introDescription: 'Intimacy goes beyond physical closeness. Explore emotional vulnerability, intellectual connection, and physical affection.',
    resultDescription: 'Your intimacy profile shows the balance and depth of connection across all dimensions.',
  },
  {
    id: 'trust-vulnerability',
    name: 'Trust & Vulnerability',
    framework: 'Brené Brown Vulnerability Research',
    description: 'Evaluate trust levels and comfort with vulnerability. Trust is built through consistent vulnerability and emotional risk-taking.',
    estimatedTime: '7 min',
    questionsCount: 18,
    icon: '🛡️',
    category: 'trust',
    introTitle: 'How safe do you feel being vulnerable?',
    introDescription: 'Vulnerability is the foundation of deep connection. This assessment explores how comfortable you are being emotionally open.',
    resultDescription: 'Your trust profile reveals the safety and depth of emotional vulnerability in your relationship.',
  },
  {
    id: 'financial-values',
    name: 'Financial Values',
    framework: 'Financial Therapy Models',
    description: 'Understand your money beliefs, spending patterns, and financial communication. Financial stress is a leading cause of relationship tension.',
    estimatedTime: '8 min',
    questionsCount: 22,
    icon: '💰',
    category: 'values',
    introTitle: 'How do your money values align?',
    introDescription: 'Money is one of the most common sources of conflict in relationships. Understanding each other financial perspectives is key.',
    resultDescription: 'Your financial compatibility profile shows alignment and differences in money values and habits.',
  },
  {
    id: 'sexual-compatibility',
    name: 'Sexual Compatibility',
    framework: 'Sexual Health Models',
    description: 'Explore desires, boundaries, and sexual communication. Healthy sexual connection requires openness, understanding, and mutual satisfaction.',
    estimatedTime: '10 min',
    questionsCount: 25,
    icon: '🔥',
    category: 'intimacy',
    introTitle: 'How aligned are your sexual needs and boundaries?',
    introDescription: 'Sexual compatibility is about more than desire—it includes communication, comfort, and mutual respect for boundaries.',
    resultDescription: 'Your sexual compatibility profile helps identify areas of alignment and communication opportunities.',
  },
  {
    id: 'shared-meaning',
    name: 'Shared Meaning',
    framework: 'Gottman Sound Relationship House',
    description: 'Build shared rituals, goals, and life dreams. Creating shared meaning strengthens your bond and gives you a joint vision for the future.',
    estimatedTime: '12 min',
    questionsCount: 30,
    icon: '🏡',
    category: 'connection',
    introTitle: 'What shared story are you building together?',
    introDescription: 'Shared meaning encompasses your joint goals, traditions, and the legacy you creating as a couple.',
    resultDescription: 'Your shared meaning profile shows the depth of your joint vision and connection.',
  },
  {
    id: 'relationship-satisfaction',
    name: 'Relationship Satisfaction',
    framework: 'RDAS (Revised Dyadic Adjustment Scale)',
    description: 'Overall relationship quality and satisfaction assessment. This validated scale measures consensus, satisfaction, and cohesion.',
    estimatedTime: '6 min',
    questionsCount: 14,
    icon: '⭐',
    category: 'general',
    introTitle: 'How satisfied are you with your relationship?',
    introDescription: 'This comprehensive assessment evaluates your overall relationship health across key dimensions.',
    resultDescription: 'Your satisfaction profile provides a complete picture of your relationship wellness.',
  },
  {
    id: 'stress-coping',
    name: 'Stress & Coping',
    framework: 'Lazarus & Folkman Stress Model',
    description: 'How you handle stress as a couple. External pressures can strain relationships or become opportunities for deeper connection.',
    estimatedTime: '7 min',
    questionsCount: 20,
    icon: '🌊',
    category: 'resilience',
    introTitle: 'How do you navigate stress together?',
    introDescription: 'Stress affects us all, and how couples support each other through challenges determines relationship resilience.',
    resultDescription: 'Your stress coping profile reveals how you and your partner handle pressure as a team.',
  },
  {
    id: 'fun-personality',
    name: 'Fun & Personality',
    framework: 'Leisure & Play Research',
    description: 'Explore how you enjoy time together and shared interests. Play and laughter are essential for long-term relationship satisfaction.',
    estimatedTime: '6 min',
    questionsCount: 18,
    icon: '🎉',
    category: 'connection',
    introTitle: 'How do you have fun together?',
    introDescription: 'Shared activities, humor, and play create positive experiences that strengthen your bond and create lasting memories.',
    resultDescription: 'Your fun and play profile shows how you create joy and connection through shared experiences.',
  },
  {
    id: 'appreciation-gratitude',
    name: 'Appreciation & Gratitude',
    framework: 'Positive Psychology',
    description: 'How you express and receive appreciation. Regular appreciation and gratitude are among the strongest predictors of relationship satisfaction.',
    estimatedTime: '5 min',
    questionsCount: 15,
    icon: '🙏',
    category: 'connection',
    introTitle: 'Do you feel appreciated and grateful?',
    introDescription: 'Expressing appreciation strengthens relationships. This assessment explores how you give and receive gratitude.',
    resultDescription: 'Your appreciation profile reveals how well gratitude and recognition flow in your relationship.',
  },
];

// ============================================================================
// LOVE LANGUAGES — 30 Questions (5 per love language)
// Category mapping: words, time, gifts, acts, touch
// ============================================================================

export const loveLanguagesQuestions = [
  // Words of Affirmation (6 questions)
  {
    id: 1,
    text: 'I feel most loved when my partner tells me they love me or compliments me',
    type: 'likert',
    scale: 5,
    category: 'words',
    reverse: false,
  },
  {
    id: 2,
    text: 'Hearing encouraging words from my partner means more to me than any gift',
    type: 'likert',
    scale: 5,
    category: 'words',
    reverse: false,
  },
  {
    id: 3,
    text: 'I appreciate it when my partner acknowledges my efforts, even for small things',
    type: 'likert',
    scale: 5,
    category: 'words',
    reverse: false,
  },
  {
    id: 4,
    text: 'Written notes or text messages expressing love mean a lot to me',
    type: 'likert',
    scale: 5,
    category: 'words',
    reverse: false,
  },
  {
    id: 5,
    text: 'When my partner criticizes me with harsh words, I feel deeply hurt',
    type: 'likert',
    scale: 5,
    category: 'words',
    reverse: true,
  },
  {
    id: 6,
    text: 'I feel closest when my partner says kind things about me to others',
    type: 'likert',
    scale: 5,
    category: 'words',
    reverse: false,
  },

  // Quality Time (6 questions)
  {
    id: 7,
    text: 'I feel most loved when my partner gives me their undivided attention',
    type: 'likert',
    scale: 5,
    category: 'time',
    reverse: false,
  },
  {
    id: 8,
    text: 'I value time spent together more than receiving gifts',
    type: 'likert',
    scale: 5,
    category: 'time',
    reverse: false,
  },
  {
    id: 9,
    text: 'When my partner is distracted or on their phone during our time, I feel neglected',
    type: 'likert',
    scale: 5,
    category: 'time',
    reverse: true,
  },
  {
    id: 10,
    text: 'I love making plans for just the two of us with no distractions',
    type: 'likert',
    scale: 5,
    category: 'time',
    reverse: false,
  },
  {
    id: 11,
    text: 'Scheduled date nights are important to me for maintaining our connection',
    type: 'likert',
    scale: 5,
    category: 'time',
    reverse: false,
  },
  {
    id: 12,
    text: 'I feel loved when we spend an evening talking and catching up with each other',
    type: 'likert',
    scale: 5,
    category: 'time',
    reverse: false,
  },

  // Receiving Gifts (6 questions)
  {
    id: 13,
    text: 'I feel most loved when my partner gives me thoughtful gifts',
    type: 'likert',
    scale: 5,
    category: 'gifts',
    reverse: false,
  },
  {
    id: 14,
    text: 'The effort my partner puts into finding a meaningful gift shows me they care',
    type: 'likert',
    scale: 5,
    category: 'gifts',
    reverse: false,
  },
  {
    id: 15,
    text: 'I feel hurt when my partner forgets important occasions like birthdays or anniversaries',
    type: 'likert',
    scale: 5,
    category: 'gifts',
    reverse: true,
  },
  {
    id: 16,
    text: 'Surprise gifts or little tokens of affection make me feel special',
    type: 'likert',
    scale: 5,
    category: 'gifts',
    reverse: false,
  },
  {
    id: 17,
    text: 'I appreciate when my partner picks up small things they know I would like',
    type: 'likert',
    scale: 5,
    category: 'gifts',
    reverse: false,
  },
  {
    id: 18,
    text: 'A gift does not need to be expensive to be meaningful to me—what matters is the thought behind it',
    type: 'likert',
    scale: 5,
    category: 'gifts',
    reverse: false,
  },

  // Acts of Service (6 questions)
  {
    id: 19,
    text: 'I feel most loved when my partner does helpful things for me without being asked',
    type: 'likert',
    scale: 5,
    category: 'acts',
    reverse: false,
  },
  {
    id: 20,
    text: 'When my partner takes care of tasks I usually handle, I feel truly cared for',
    type: 'likert',
    scale: 5,
    category: 'acts',
    reverse: false,
  },
  {
    id: 21,
    text: 'I feel hurt and unappreciated when I am overwhelmed and my partner does not help',
    type: 'likert',
    scale: 5,
    category: 'acts',
    reverse: true,
  },
  {
    id: 22,
    text: 'I appreciate when my partner actively looks for ways to make my life easier',
    type: 'likert',
    scale: 5,
    category: 'acts',
    reverse: false,
  },
  {
    id: 23,
    text: 'Actions speak louder than words to me—doing things for me shows love more than saying it',
    type: 'likert',
    scale: 5,
    category: 'acts',
    reverse: false,
  },
  {
    id: 24,
    text: 'When my partner cooks a meal for me or helps with chores, I feel deeply loved',
    type: 'likert',
    scale: 5,
    category: 'acts',
    reverse: false,
  },

  // Physical Touch (6 questions)
  {
    id: 25,
    text: 'I feel most loved when my partner holds my hand, hugs me, or shows physical affection',
    type: 'likert',
    scale: 5,
    category: 'touch',
    reverse: false,
  },
  {
    id: 26,
    text: 'Physical closeness and touch are essential to me feeling connected in the relationship',
    type: 'likert',
    scale: 5,
    category: 'touch',
    reverse: false,
  },
  {
    id: 27,
    text: 'When my partner pulls away from physical touch, I feel rejected and unloved',
    type: 'likert',
    scale: 5,
    category: 'touch',
    reverse: true,
  },
  {
    id: 28,
    text: 'I love cuddling, kissing, and general physical affection throughout the day',
    type: 'likert',
    scale: 5,
    category: 'touch',
    reverse: false,
  },
  {
    id: 29,
    text: 'Physical touch is my primary way of feeling emotionally close to my partner',
    type: 'likert',
    scale: 5,
    category: 'touch',
    reverse: false,
  },
  {
    id: 30,
    text: 'A warm embrace after a long day means more to me than any verbal reassurance',
    type: 'likert',
    scale: 5,
    category: 'touch',
    reverse: false,
  },
];

// ============================================================================
// ATTACHMENT STYLE — 20 Questions
// Based on ECR-R (Experiences in Close Relationships Revised)
// Categories: anxiety, avoidance
// ============================================================================

export const attachmentStyleQuestions = [
  // Anxiety dimension (10 questions)
  {
    id: 1,
    text: 'I worry that my partner does not love me as much as I love them',
    type: 'likert',
    scale: 5,
    category: 'anxiety',
    reverse: false,
  },
  {
    id: 2,
    text: 'I am afraid that my partner might want to leave me',
    type: 'likert',
    scale: 5,
    category: 'anxiety',
    reverse: false,
  },
  {
    id: 3,
    text: 'I often wish my partner would show more emotion and affection',
    type: 'likert',
    scale: 5,
    category: 'anxiety',
    reverse: false,
  },
  {
    id: 4,
    text: 'I need a lot of reassurance that my partner loves me',
    type: 'likert',
    scale: 5,
    category: 'anxiety',
    reverse: false,
  },
  {
    id: 5,
    text: 'I often feel anxious when my partner is not around',
    type: 'likert',
    scale: 5,
    category: 'anxiety',
    reverse: false,
  },
  {
    id: 6,
    text: 'I often wonder whether my partner really cares about me',
    type: 'likert',
    scale: 5,
    category: 'anxiety',
    reverse: false,
  },
  {
    id: 7,
    text: 'When my partner does something hurtful, I cannot stop thinking about it',
    type: 'likert',
    scale: 5,
    category: 'anxiety',
    reverse: false,
  },
  {
    id: 8,
    text: 'I feel jealous when my partner spends time with others',
    type: 'likert',
    scale: 5,
    category: 'anxiety',
    reverse: false,
  },
  {
    id: 9,
    text: 'I am afraid of being abandoned in this relationship',
    type: 'likert',
    scale: 5,
    category: 'anxiety',
    reverse: false,
  },
  {
    id: 10,
    text: 'I often feel that my partner does not fully understand me or my needs',
    type: 'likert',
    scale: 5,
    category: 'anxiety',
    reverse: false,
  },

  // Avoidance dimension (10 questions)
  {
    id: 11,
    text: 'I find it difficult to get emotionally close to my partner',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: false,
  },
  {
    id: 12,
    text: 'I prefer not to show my partner how I feel deep down',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: false,
  },
  {
    id: 13,
    text: 'I feel comfortable depending on my partner',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: true,
  },
  {
    id: 14,
    text: 'I am comfortable sharing my private thoughts and feelings with my partner',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: true,
  },
  {
    id: 15,
    text: 'I find it hard to trust my partner completely',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: false,
  },
  {
    id: 16,
    text: 'I feel uneasy when my partner wants to be very close',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: false,
  },
  {
    id: 17,
    text: 'I try to avoid too much closeness with my partner',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: false,
  },
  {
    id: 18,
    text: 'When my partner gets too close, I feel the need to pull away',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: false,
  },
  {
    id: 19,
    text: 'I am not very comfortable being depending on others',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: false,
  },
  {
    id: 20,
    text: 'I do not like sharing my inner thoughts and feelings with my partner',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: false,
  },
];

// ============================================================================
// COMMUNICATION STYLE — 15 Questions
// Based on Nonviolent Communication principles
// Categories: expression, listening, validation, accountability
// ============================================================================

export const communicationStyleQuestions = [
  // Expression (4 questions)
  {
    id: 1,
    text: 'I clearly express my needs and feelings to my partner',
    type: 'likert',
    scale: 5,
    category: 'expression',
    reverse: false,
  },
  {
    id: 2,
    text: 'I use \"I feel\" statements rather than blaming or accusing my partner',
    type: 'likert',
    scale: 5,
    category: 'expression',
    reverse: false,
  },
  {
    id: 3,
    text: 'I can articulate when something is bothering me without escalating into conflict',
    type: 'likert',
    scale: 5,
    category: 'expression',
    reverse: false,
  },
  {
    id: 4,
    text: 'I tend to keep my frustrations to myself until they build up and explode',
    type: 'likert',
    scale: 5,
    category: 'expression',
    reverse: true,
  },

  // Listening (4 questions)
  {
    id: 5,
    text: 'I listen without interrupting when my partner is speaking',
    type: 'likert',
    scale: 5,
    category: 'listening',
    reverse: false,
  },
  {
    id: 6,
    text: 'I ask clarifying questions to make sure I understand what my partner is saying',
    type: 'likert',
    scale: 5,
    category: 'listening',
    reverse: false,
  },
  {
    id: 7,
    text: 'I can tell when my partner is upset even without them explicitly saying so',
    type: 'likert',
    scale: 5,
    category: 'listening',
    reverse: false,
  },
  {
    id: 8,
    text: 'I find myself planning my response while my partner is still talking rather than truly listening',
    type: 'likert',
    scale: 5,
    category: 'listening',
    reverse: true,
  },

  // Validation (4 questions)
  {
    id: 9,
    text: 'I validate my partner feelings even when I disagree with their perspective',
    type: 'likert',
    scale: 5,
    category: 'validation',
    reverse: false,
  },
  {
    id: 10,
    text: 'I acknowledge my partner point of view before offering my own',
    type: 'likert',
    scale: 5,
    category: 'validation',
    reverse: false,
  },
  {
    id: 11,
    text: 'When my partner shares something difficult, I offer comfort and support first',
    type: 'likert',
    scale: 5,
    category: 'validation',
    reverse: false,
  },
  {
    id: 12,
    text: 'I tend to dismiss or minimize my partner feelings when they are upset',
    type: 'likert',
    scale: 5,
    category: 'validation',
    reverse: true,
  },

  // Accountability (3 questions)
  {
    id: 13,
    text: 'I take responsibility for my part in conflicts and apologize when I am wrong',
    type: 'likert',
    scale: 5,
    category: 'accountability',
    reverse: false,
  },
  {
    id: 14,
    text: 'I avoid bringing up past conflicts during current disagreements',
    type: 'likert',
    scale: 5,
    category: 'accountability',
    reverse: false,
  },
  {
    id: 15,
    text: 'I can compromise and find middle ground when our needs differ',
    type: 'likert',
    scale: 5,
    category: 'accountability',
    reverse: false,
  },
];

// ============================================================================
// FOUR HORSEMEN — 20 Questions
// Based on Gottman Institute research
// Categories: criticism, contempt, defensiveness, stonewalling
// ============================================================================

export const gottmanFourHorsemenQuestions = [
  // Criticism (5 questions)
  {
    id: 1,
    text: 'During disagreements, I criticize my partner character rather than their specific behavior',
    type: 'likert',
    scale: 5,
    category: 'criticism',
    reverse: true,
  },
  {
    id: 2,
    text: 'I use words like \"always\" or \"never\" when describing my partner flaws (e.g., \"You always ignore me\")',
    type: 'likert',
    scale: 5,
    category: 'criticism',
    reverse: true,
  },
  {
    id: 3,
    text: 'I make negative observations about my partner personality as part of arguments',
    type: 'likert',
    scale: 5,
    category: 'criticism',
    reverse: true,
  },
  {
    id: 4,
    text: 'When providing feedback, I focus on the issue at hand rather than attacking my partner character',
    type: 'likert',
    scale: 5,
    category: 'criticism',
    reverse: false,
  },
  {
    id: 5,
    text: 'I express complaints as \"I\" statements (e.g., \"I feel hurt when...\") rather than \"You\" accusations',
    type: 'likert',
    scale: 5,
    category: 'criticism',
    reverse: false,
  },

  // Contempt (5 questions)
  {
    id: 6,
    text: 'I show contempt through eye-rolling, sneering, or mocking during conflicts',
    type: 'likert',
    scale: 5,
    category: 'contempt',
    reverse: true,
  },
  {
    id: 7,
    text: 'I use sarcasm or mockery when my partner says something I disagree with',
    type: 'likert',
    scale: 5,
    category: 'contempt',
    reverse: true,
  },
  {
    id: 8,
    text: 'I have used hostile humor or put-downs during arguments',
    type: 'likert',
    scale: 5,
    category: 'contempt',
    reverse: true,
  },
  {
    id: 9,
    text: 'When my partner shares their perspective, I respond with genuine interest and respect',
    type: 'likert',
    scale: 5,
    category: 'contempt',
    reverse: false,
  },
  {
    id: 10,
    text: 'I treat my partner as an equal, even during disagreements',
    type: 'likert',
    scale: 5,
    category: 'contempt',
    reverse: false,
  },

  // Defensiveness (5 questions)
  {
    id: 11,
    text: 'When my partner brings up a concern, I immediately become defensive',
    type: 'likert',
    scale: 5,
    category: 'defensiveness',
    reverse: true,
  },
  {
    id: 12,
    text: 'I make excuses or deflect blame when my partner points out something I did wrong',
    type: 'likert',
    scale: 5,
    category: 'defensiveness',
    reverse: true,
  },
  {
    id: 13,
    text: 'I respond to my partner criticism with \"Whatever\" or by walking away',
    type: 'likert',
    scale: 5,
    category: 'defensiveness',
    reverse: true,
  },
  {
    id: 14,
    text: 'When my partner raises an issue, I can acknowledge their perspective even if I disagree',
    type: 'likert',
    scale: 5,
    category: 'defensiveness',
    reverse: false,
  },
  {
    id: 15,
    text: 'I take responsibility for my mistakes rather than immediately deflecting',
    type: 'likert',
    scale: 5,
    category: 'defensiveness',
    reverse: false,
  },

  // Stonewalling (5 questions)
  {
    id: 16,
    text: 'I withdraw or shut down emotionally when conflicts become too intense',
    type: 'likert',
    scale: 5,
    category: 'stonewalling',
    reverse: true,
  },
  {
    id: 17,
    text: 'I refuse to engage in conversation or give my partner any response during arguments',
    type: 'likert',
    scale: 5,
    category: 'stonewalling',
    reverse: true,
  },
  {
    id: 18,
    text: 'When I am overwhelmed, I need to step away to calm down before continuing the conversation',
    type: 'likert',
    scale: 5,
    category: 'stonewalling',
    reverse: false,
  },
  {
    id: 19,
    text: 'I make repair attempts (e.g., \"Can we pause and come back to this?\") when things get heated',
    type: 'likert',
    scale: 5,
    category: 'stonewalling',
    reverse: false,
  },
  {
    id: 20,
    text: 'I stay engaged with my partner even during difficult conversations',
    type: 'likert',
    scale: 5,
    category: 'stonewalling',
    reverse: false,
  },
];

// ============================================================================
// CONFLICT RESOLUTION — 25 Questions
// Categories: avoidance, composure, compromise, empathy, repair
// ============================================================================

export const conflictResolutionQuestions = [
  // Avoidance (5 questions)
  {
    id: 1,
    text: 'I prefer to avoid conflicts rather than address them directly',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: true,
  },
  {
    id: 2,
    text: 'I put off discussing difficult topics hoping they will resolve on their own',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: true,
  },
  {
    id: 3,
    text: 'When a conflict arises, I prefer to address it rather than let it fester',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: false,
  },
  {
    id: 4,
    text: 'I can discuss sensitive topics openly without trying to escape the conversation',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: false,
  },
  {
    id: 5,
    text: 'I address issues as they come rather than letting them build up',
    type: 'likert',
    scale: 5,
    category: 'avoidance',
    reverse: false,
  },

  // Composure (5 questions)
  {
    id: 6,
    text: 'I can discuss difficult topics without becoming angry or upset',
    type: 'likert',
    scale: 5,
    category: 'composure',
    reverse: false,
  },
  {
    id: 7,
    text: 'When my partner raises a concern, I can stay calm and listen',
    type: 'likert',
    scale: 5,
    category: 'composure',
    reverse: false,
  },
  {
    id: 8,
    text: 'I can stay emotionally regulated even when my partner is upset',
    type: 'likert',
    scale: 5,
    category: 'composure',
    reverse: false,
  },
  {
    id: 9,
    text: 'I have raised my voice or said things I regret during conflicts',
    type: 'likert',
    scale: 5,
    category: 'composure',
    reverse: true,
  },
  {
    id: 10,
    text: 'I need time to cool down before discussing problems',
    type: 'likert',
    scale: 5,
    category: 'composure',
    reverse: false,
  },

  // Compromise (5 questions)
  {
    id: 11,
    text: 'I seek compromise during disagreements rather than trying to win',
    type: 'likert',
    scale: 5,
    category: 'compromise',
    reverse: false,
  },
  {
    id: 12,
    text: 'I can find solutions that work for both of us, not just me',
    type: 'likert',
    scale: 5,
    category: 'compromise',
    reverse: false,
  },
  {
    id: 13,
    text: 'I am willing to give up my position if my partner has a compelling point',
    type: 'likert',
    scale: 5,
    category: 'compromise',
    reverse: false,
  },
  {
    id: 14,
    text: 'We often struggle to find middle ground when our needs differ',
    type: 'likert',
    scale: 5,
    category: 'compromise',
    reverse: true,
  },
  {
    id: 15,
    text: 'I look for win-win solutions rather than demanding my way',
    type: 'likert',
    scale: 5,
    category: 'compromise',
    reverse: false,
  },

  // Empathy (5 questions)
  {
    id: 16,
    text: 'I can see my partner point of view even when we disagree',
    type: 'likert',
    scale: 5,
    category: 'empathy',
    reverse: false,
  },
  {
    id: 17,
    text: 'I try to understand why my partner feels the way they do before responding',
    type: 'likert',
    scale: 5,
    category: 'empathy',
    reverse: false,
  },
  {
    id: 18,
    text: 'I feel heard during conflicts with my partner',
    type: 'likert',
    scale: 5,
    category: 'empathy',
    reverse: false,
  },
  {
    id: 19,
    text: 'My partner understands my perspective even when we disagree',
    type: 'likert',
    scale: 5,
    category: 'empathy',
    reverse: false,
  },
  {
    id: 20,
    text: 'Conflicts feel threatening to our relationship rather than normal',
    type: 'likert',
    scale: 5,
    category: 'empathy',
    reverse: true,
  },

  // Repair (5 questions)
  {
    id: 21,
    text: 'I make repair attempts when things get tense (e.g., lighten the mood, apologize)',
    type: 'likert',
    scale: 5,
    category: 'repair',
    reverse: false,
  },
  {
    id: 22,
    text: 'After a conflict, I follow up to ensure we are both okay',
    type: 'likert',
    scale: 5,
    category: 'repair',
    reverse: false,
  },
  {
    id: 23,
    text: 'We can laugh together even after disagreements',
    type: 'likert',
    scale: 5,
    category: 'repair',
    reverse: false,
  },
  {
    id: 24,
    text: 'I apologize when I am wrong, even for small things',
    type: 'likert',
    scale: 5,
    category: 'repair',
    reverse: false,
  },
  {
    id: 25,
    text: 'We reconcile after conflicts and move forward without lingering resentment',
    type: 'likert',
    scale: 5,
    category: 'repair',
    reverse: false,
  },
];

// ============================================================================
// VALUES ALIGNMENT — 30 Questions
// Categories: family, finance, spirituality, lifestyle, relationships, goals
// ============================================================================

export const valuesAlignmentQuestions = [
  // Family Values (5 questions)
  {
    id: 1,
    text: 'My partner and I share similar views on what family means and how to prioritize family',
    type: 'likert',
    scale: 5,
    category: 'family',
    reverse: false,
  },
  {
    id: 2,
    text: 'We agree on how much time to spend with extended family vs. alone time together',
    type: 'likert',
    scale: 5,
    category: 'family',
    reverse: false,
  },
  {
    id: 3,
    text: 'We have compatible expectations about caring for aging parents',
    type: 'likert',
    scale: 5,
    category: 'family',
    reverse: false,
  },
  {
    id: 4,
    text: 'We align on how to handle family traditions and create new ones together',
    type: 'likert',
    scale: 5,
    category: 'family',
    reverse: false,
  },
  {
    id: 5,
    text: 'My family values align with my partner family values',
    type: 'likert',
    scale: 5,
    category: 'family',
    reverse: false,
  },

  // Financial Values (5 questions)
  {
    id: 6,
    text: 'We have aligned financial goals and agree on how to handle money',
    type: 'likert',
    scale: 5,
    category: 'finance',
    reverse: false,
  },
  {
    id: 7,
    text: 'We agree on how much to spend vs. save and our spending priorities',
    type: 'likert',
    scale: 5,
    category: 'finance',
    reverse: false,
  },
  {
    id: 8,
    text: 'We share similar attitudes about taking on debt (e.g., loans, credit cards)',
    type: 'likert',
    scale: 5,
    category: 'finance',
    reverse: false,
  },
  {
    id: 9,
    text: 'We align on how much to spend on gifts, travel, and discretionary items',
    type: 'likert',
    scale: 5,
    category: 'finance',
    reverse: false,
  },
  {
    id: 10,
    text: 'We agree on financial transparency and how to handle shared vs. separate finances',
    type: 'likert',
    scale: 5,
    category: 'finance',
    reverse: false,
  },

  // Spirituality/Values (5 questions)
  {
    id: 11,
    text: 'Our spiritual or religious beliefs are compatible',
    type: 'likert',
    scale: 5,
    category: 'spirituality',
    reverse: false,
  },
  {
    id: 12,
    text: 'We align on how important spirituality/religion is in our daily lives',
    type: 'likert',
    scale: 5,
    category: 'spirituality',
    reverse: false,
  },
  {
    id: 13,
    text: 'We share similar ethical values and views on what is right and wrong',
    type: 'likert',
    scale: 5,
    category: 'spirituality',
    reverse: false,
  },
  {
    id: 14,
    text: 'We agree on how to navigate differences in spiritual/religious beliefs',
    type: 'likert',
    scale: 5,
    category: 'spirituality',
    reverse: false,
  },
  {
    id: 15,
    text: 'Our core values and beliefs are aligned even if our spiritual practices differ',
    type: 'likert',
    scale: 5,
    category: 'spirituality',
    reverse: false,
  },

  // Lifestyle (5 questions)
  {
    id: 16,
    text: 'We agree on work-life balance priorities and how much time to dedicate to careers',
    type: 'likert',
    scale: 5,
    category: 'lifestyle',
    reverse: false,
  },
  {
    id: 17,
    text: 'We share similar views on health, wellness, and how we take care of ourselves',
    type: 'likert',
    scale: 5,
    category: 'lifestyle',
    reverse: false,
  },
  {
    id: 18,
    text: 'We align on how we want to spend our leisure time and hobbies',
    type: 'likert',
    scale: 5,
    category: 'lifestyle',
    reverse: false,
  },
  {
    id: 19,
    text: 'We agree on living arrangements (e.g., city vs. suburbs, apartment vs. house)',
    type: 'likert',
    scale: 5,
    category: 'lifestyle',
    reverse: false,
  },
  {
    id: 20,
    text: 'Our lifestyle preferences (e.g., social, active, introverted) are compatible',
    type: 'likert',
    scale: 5,
    category: 'lifestyle',
    reverse: false,
  },

  // Relationships/Gender Roles (5 questions)
  {
    id: 21,
    text: 'We share similar views on gender roles and expectations in the relationship',
    type: 'likert',
    scale: 5,
    category: 'relationships',
    reverse: false,
  },
  {
    id: 22,
    text: 'We align on how to divide household responsibilities',
    type: 'likert',
    scale: 5,
    category: 'relationships',
    reverse: false,
  },
  {
    id: 23,
    text: 'We agree on how to handle decisions about the relationship (e.g., equal partnership)',
    type: 'likert',
    scale: 5,
    category: 'relationships',
    reverse: false,
  },
  {
    id: 24,
    text: 'Our social and political values are compatible',
    type: 'likert',
    scale: 5,
    category: 'relationships',
    reverse: false,
  },
  {
    id: 25,
    text: 'We align on how much independence and autonomy each person needs in the relationship',
    type: 'likert',
    scale: 5,
    category: 'relationships',
    reverse: false,
  },

  // Life Goals (5 questions)
  {
    id: 26,
    text: 'We have compatible views on children and whether/how to become parents',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },
  {
    id: 27,
    text: 'Our long-term life goals are aligned (e.g., where we want to live, career aspirations)',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },
  {
    id: 28,
    text: 'We share similar ambitions for personal growth and self-improvement',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },
  {
    id: 29,
    text: 'We value similar things in life and have a shared vision for our future',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },
  {
    id: 30,
    text: 'We respect each other individual values even where they differ',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },
];

// ============================================================================
// EMOTIONAL INTELLIGENCE — 24 Questions
// Categories: selfAwareness, selfRegulation, empathy, socialSkills
// ============================================================================

export const emotionalIntelligenceQuestions = [
  // Self-Awareness (6 questions)
  {
    id: 1,
    text: 'I can identify and name my emotions as I am experiencing them',
    type: 'likert',
    scale: 5,
    category: 'selfAwareness',
    reverse: false,
  },
  {
    id: 2,
    text: 'I understand why I feel the way I do in most situations',
    type: 'likert',
    scale: 5,
    category: 'selfAwareness',
    reverse: false,
  },
  {
    id: 3,
    text: 'I recognize how my emotions affect my behavior and reactions',
    type: 'likert',
    scale: 5,
    category: 'selfAwareness',
    reverse: false,
  },
  {
    id: 4,
    text: 'I am aware of my emotional triggers and what sets me off',
    type: 'likert',
    scale: 5,
    category: 'selfAwareness',
    reverse: false,
  },
  {
    id: 5,
    text: 'I can distinguish between different emotional states (e.g., fear vs. anxiety vs. worry)',
    type: 'likert',
    scale: 5,
    category: 'selfAwareness',
    reverse: false,
  },
  {
    id: 6,
    text: 'I have good insight into my own strengths and weaknesses',
    type: 'likert',
    scale: 5,
    category: 'selfAwareness',
    reverse: false,
  },

  // Self-Regulation (6 questions)
  {
    id: 7,
    text: 'I can calm myself down when I am upset or angry',
    type: 'likert',
    scale: 5,
    category: 'selfRegulation',
    reverse: false,
  },
  {
    id: 8,
    text: 'I delay reacting in the moment to think before responding',
    type: 'likert',
    scale: 5,
    category: 'selfRegulation',
    reverse: false,
  },
  {
    id: 9,
    text: 'I can handle criticism without becoming defensive or upset',
    type: 'likert',
    scale: 5,
    category: 'selfRegulation',
    reverse: false,
  },
  {
    id: 10,
    text: 'I adapt well to unexpected changes and challenges',
    type: 'likert',
    scale: 5,
    category: 'selfRegulation',
    reverse: false,
  },
  {
    id: 11,
    text: 'I manage stress effectively and do not let it overwhelm me easily',
    type: 'likert',
    scale: 5,
    category: 'selfRegulation',
    reverse: false,
  },
  {
    id: 12,
    text: 'I keep my emotions in check even in difficult or high-pressure situations',
    type: 'likert',
    scale: 5,
    category: 'selfRegulation',
    reverse: false,
  },

  // Empathy (6 questions)
  {
    id: 13,
    text: 'I can sense how my partner is feeling even when they do not say it directly',
    type: 'likert',
    scale: 5,
    category: 'empathy',
    reverse: false,
  },
  {
    id: 14,
    text: 'I understand my partner emotional perspective even when I disagree',
    type: 'likert',
    scale: 5,
    category: 'empathy',
    reverse: false,
  },
  {
    id: 15,
    text: 'I respond to my partner emotions with care and concern',
    type: 'likert',
    scale: 5,
    category: 'empathy',
    reverse: false,
  },
  {
    id: 16,
    text: 'I can put myself in my partner shoes and see things from their perspective',
    type: 'likert',
    scale: 5,
    category: 'empathy',
    reverse: false,
  },
  {
    id: 17,
    text: 'I notice when my partner is struggling and offer support proactively',
    type: 'likert',
    scale: 5,
    category: 'empathy',
    reverse: false,
  },
  {
    id: 18,
    text: 'I validate my partner feelings rather than dismissing or minimizing them',
    type: 'likert',
    scale: 5,
    category: 'empathy',
    reverse: false,
  },

  // Social Skills (6 questions)
  {
    id: 19,
    text: 'I communicate clearly and effectively with my partner',
    type: 'likert',
    scale: 5,
    category: 'socialSkills',
    reverse: false,
  },
  {
    id: 20,
    text: 'I can navigate disagreements without damaging the relationship',
    type: 'likert',
    scale: 5,
    category: 'socialSkills',
    reverse: false,
  },
  {
    id: 21,
    text: 'I am good at reading non-verbal cues and body language',
    type: 'likert',
    scale: 5,
    category: 'socialSkills',
    reverse: false,
  },
  {
    id: 22,
    text: 'I support my partner through difficult emotions without trying to fix everything',
    type: 'likert',
    scale: 5,
    category: 'socialSkills',
    reverse: false,
  },
  {
    id: 23,
    text: 'I can express difficult emotions in a constructive way',
    type: 'likert',
    scale: 5,
    category: 'socialSkills',
    reverse: false,
  },
  {
    id: 24,
    text: 'I maintain emotional intimacy even during stressful periods',
    type: 'likert',
    scale: 5,
    category: 'socialSkills',
    reverse: false,
  },
];

// ============================================================================
// INTIMACY & CLOSENESS — 27 Questions
// Categories: emotional, physical, intellectual
// ============================================================================

export const intimacyClosenessQuestions = [
  // Emotional Intimacy (9 questions)
  {
    id: 1,
    text: 'I feel safe sharing my deepest fears and insecurities with my partner',
    type: 'likert',
    scale: 5,
    category: 'emotional',
    reverse: false,
  },
  {
    id: 2,
    text: 'I can be fully authentic with my partner without fear of judgment',
    type: 'likert',
    scale: 5,
    category: 'emotional',
    reverse: false,
  },
  {
    id: 3,
    text: 'My partner knows the real me, including my vulnerabilities',
    type: 'likert',
    scale: 5,
    category: 'emotional',
    reverse: false,
  },
  {
    id: 4,
    text: 'I feel emotionally supported during difficult times',
    type: 'likert',
    scale: 5,
    category: 'emotional',
    reverse: false,
  },
  {
    id: 5,
    text: 'We share our hopes, dreams, and aspirations with each other',
    type: 'likert',
    scale: 5,
    category: 'emotional',
    reverse: false,
  },
  {
    id: 6,
    text: 'I feel a deep sense of closeness and connection with my partner',
    type: 'likert',
    scale: 5,
    category: 'emotional',
    reverse: false,
  },
  {
    id: 7,
    text: 'We can sit in comfortable silence and still feel connected',
    type: 'likert',
    scale: 5,
    category: 'emotional',
    reverse: false,
  },
  {
    id: 8,
    text: 'My partner celebrates my successes and supports me through failures',
    type: 'likert',
    scale: 5,
    category: 'emotional',
    reverse: false,
  },
  {
    id: 9,
    text: 'I feel accepted for who I am, including my flaws and imperfections',
    type: 'likert',
    scale: 5,
    category: 'emotional',
    reverse: false,
  },

  // Physical Intimacy (9 questions)
  {
    id: 10,
    text: 'I feel satisfied with the amount of physical affection in our relationship',
    type: 'likert',
    scale: 5,
    category: 'physical',
    reverse: false,
  },
  {
    id: 11,
    text: 'Physical touch (hugging, kissing, cuddling) is an important part of our daily connection',
    type: 'likert',
    scale: 5,
    category: 'physical',
    reverse: false,
  },
  {
    id: 12,
    text: 'We are comfortable being physically close and intimate',
    type: 'likert',
    scale: 5,
    category: 'physical',
    reverse: false,
  },
  {
    id: 13,
    text: 'Physical intimacy is fulfilling and satisfying for both of us',
    type: 'likert',
    scale: 5,
    category: 'physical',
    reverse: false,
  },
  {
    id: 14,
    text: 'I feel desired by my partner and find them physically attractive',
    type: 'likert',
    scale: 5,
    category: 'physical',
    reverse: false,
  },
  {
    id: 15,
    text: 'We can be physically affectionate without it always leading to sex',
    type: 'likert',
    scale: 5,
    category: 'physical',
    reverse: false,
  },
  {
    id: 16,
    text: 'I feel comfortable initiating physical touch with my partner',
    type: 'likert',
    scale: 5,
    category: 'physical',
    reverse: false,
  },
  {
    id: 17,
    text: 'Our physical intimacy has deepened over time rather than faded',
    type: 'likert',
    scale: 5,
    category: 'physical',
    reverse: false,
  },
  {
    id: 18,
    text: 'We prioritize physical closeness even when life gets busy',
    type: 'likert',
    scale: 5,
    category: 'physical',
    reverse: false,
  },

  // Intellectual Intimacy (9 questions)
  {
    id: 19,
    text: 'I enjoy deep, meaningful conversations with my partner',
    type: 'likert',
    scale: 5,
    category: 'intellectual',
    reverse: false,
  },
  {
    id: 20,
    text: 'We share similar interests and enjoy discussing ideas together',
    type: 'likert',
    scale: 5,
    category: 'intellectual',
    reverse: false,
  },
  {
    id: 21,
    text: 'My partner challenges my thinking and helps me grow intellectually',
    type: 'likert',
    scale: 5,
    category: 'intellectual',
    reverse: false,
  },
  {
    id: 22,
    text: 'We can disagree intellectually without damaging our connection',
    type: 'likert',
    scale: 5,
    category: 'intellectual',
    reverse: false,
  },
  {
    id: 23,
    text: 'I feel stimulated and engaged when we talk about topics of mutual interest',
    type: 'likert',
    scale: 5,
    category: 'intellectual',
    reverse: false,
  },
  {
    id: 24,
    text: 'We enjoy learning new things together and exploring new ideas',
    type: 'likert',
    scale: 5,
    category: 'intellectual',
    reverse: false,
  },
  {
    id: 25,
    text: 'My partner respects my opinions and values my perspective',
    type: 'likert',
    scale: 5,
    category: 'intellectual',
    reverse: false,
  },
  {
    id: 26,
    text: 'We have engaging conversations about life, philosophy, and the world',
    type: 'likert',
    scale: 5,
    category: 'intellectual',
    reverse: false,
  },
  {
    id: 27,
    text: 'I feel intellectually connected to my partner beyond just everyday topics',
    type: 'likert',
    scale: 5,
    category: 'intellectual',
    reverse: false,
  },
];

// ============================================================================
// TRUST & VULNERABILITY — 18 Questions
// Categories: trust, vulnerability, safety
// ============================================================================

export const trustVulnerabilityQuestions = [
  // Trust (6 questions)
  {
    id: 1,
    text: 'I trust my partner completely and believe they have my best interests at heart',
    type: 'likert',
    scale: 5,
    category: 'trust',
    reverse: false,
  },
  {
    id: 2,
    text: 'I believe my partner is honest with me even when the truth is difficult',
    type: 'likert',
    scale: 5,
    category: 'trust',
    reverse: false,
  },
  {
    id: 3,
    text: 'I feel confident that my partner will follow through on their commitments',
    type: 'likert',
    scale: 5,
    category: 'trust',
    reverse: false,
  },
  {
    id: 4,
    text: 'I do not worry about my partner being unfaithful or betraying me',
    type: 'likert',
    scale: 5,
    category: 'trust',
    reverse: false,
  },
  {
    id: 5,
    text: 'My partner has earned my trust through consistent actions over time',
    type: 'likert',
    scale: 5,
    category: 'trust',
    reverse: false,
  },
  {
    id: 6,
    text: 'I can rely on my partner to be there when I need them',
    type: 'likert',
    scale: 5,
    category: 'trust',
    reverse: false,
  },

  // Vulnerability (6 questions)
  {
    id: 7,
    text: 'I feel safe being vulnerable with my partner, even with my biggest fears',
    type: 'likert',
    scale: 5,
    category: 'vulnerability',
    reverse: false,
  },
  {
    id: 8,
    text: 'I can share my failures and insecurities without fear of being judged',
    type: 'likert',
    scale: 5,
    category: 'vulnerability',
    reverse: false,
  },
  {
    id: 9,
    text: 'I let my guard down with my partner and show my authentic self',
    type: 'likert',
    scale: 5,
    category: 'vulnerability',
    reverse: false,
  },
  {
    id: 10,
    text: 'I can ask for help and support from my partner without feeling weak',
    type: 'likert',
    scale: 5,
    category: 'vulnerability',
    reverse: false,
  },
  {
    id: 11,
    text: 'I express my needs openly rather than expecting my partner to read my mind',
    type: 'likert',
    scale: 5,
    category: 'vulnerability',
    reverse: false,
  },
  {
    id: 12,
    text: 'I let my partner see me at my worst without fear of rejection',
    type: 'likert',
    scale: 5,
    category: 'vulnerability',
    reverse: false,
  },

  // Safety (6 questions)
  {
    id: 13,
    text: 'I feel emotionally safe to be myself around my partner',
    type: 'likert',
    scale: 5,
    category: 'safety',
    reverse: false,
  },
  {
    id: 14,
    text: 'My partner creates an environment where I feel accepted and valued',
    type: 'likert',
    scale: 5,
    category: 'safety',
    reverse: false,
  },
  {
    id: 15,
    text: 'I do not need to protect myself from criticism or ridicule from my partner',
    type: 'likert',
    scale: 5,
    category: 'safety',
    reverse: false,
  },
  {
    id: 16,
    text: 'When I am hurting, my partner responds with compassion rather than dismissal',
    type: 'likert',
    scale: 5,
    category: 'safety',
    reverse: false,
  },
  {
    id: 17,
    text: 'I feel comfortable expressing disagreement without fearing emotional retaliation',
    type: 'likert',
    scale: 5,
    category: 'safety',
    reverse: false,
  },
  {
    id: 18,
    text: 'Our relationship feels like a safe haven where I can be fully myself',
    type: 'likert',
    scale: 5,
    category: 'safety',
    reverse: false,
  },
];

// ============================================================================
// FINANCIAL VALUES — 22 Questions
// Categories: attitudes, communication, goals, habits
// ============================================================================

export const financialValuesQuestions = [
  // Financial Attitudes (6 questions)
  {
    id: 1,
    text: 'I am comfortable discussing money and financial topics openly with my partner',
    type: 'likert',
    scale: 5,
    category: 'attitudes',
    reverse: false,
  },
  {
    id: 2,
    text: 'I view money as a tool for building a life together rather than a source of conflict',
    type: 'likert',
    scale: 5,
    category: 'attitudes',
    reverse: false,
  },
  {
    id: 3,
    text: 'My partner and I share similar attitudes about spending and saving',
    type: 'likert',
    scale: 5,
    category: 'attitudes',
    reverse: false,
  },
  {
    id: 4,
    text: 'I believe financial transparency is essential in our relationship',
    type: 'likert',
    scale: 5,
    category: 'attitudes',
    reverse: false,
  },
  {
    id: 5,
    text: 'I feel comfortable talking about money stress with my partner',
    type: 'likert',
    scale: 5,
    category: 'attitudes',
    reverse: false,
  },
  {
    id: 6,
    text: 'I have positive associations with money and financial discussions',
    type: 'likert',
    scale: 5,
    category: 'attitudes',
    reverse: false,
  },

  // Financial Communication (5 questions)
  {
    id: 7,
    text: 'We discuss our financial situation regularly, not just when there is a problem',
    type: 'likert',
    scale: 5,
    category: 'communication',
    reverse: false,
  },
  {
    id: 8,
    text: 'We make major financial decisions together after careful discussion',
    type: 'likert',
    scale: 5,
    category: 'communication',
    reverse: false,
  },
  {
    id: 9,
    text: 'I feel heard when discussing financial concerns with my partner',
    type: 'likert',
    scale: 5,
    category: 'communication',
    reverse: false,
  },
  {
    id: 10,
    text: 'We can disagree about money without the conversation turning hostile',
    type: 'likert',
    scale: 5,
    category: 'communication',
    reverse: false,
  },
  {
    id: 11,
    text: 'My partner considers my financial perspective when making spending decisions',
    type: 'likert',
    scale: 5,
    category: 'communication',
    reverse: false,
  },

  // Financial Goals (5 questions)
  {
    id: 12,
    text: 'We have shared short-term and long-term financial goals',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },
  {
    id: 13,
    text: 'We align on how much to save vs. spend and our savings priorities',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },
  {
    id: 14,
    text: 'We agree on major financial milestones (e.g., buying a home, retirement)',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },
  {
    id: 15,
    text: 'We work together as a team to achieve our financial goals',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },
  {
    id: 16,
    text: 'I trust my partner to handle finances responsibly',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },

  // Financial Habits (6 questions)
  {
    id: 17,
    text: 'We track our spending and have a clear picture of our finances',
    type: 'likert',
    scale: 5,
    category: 'habits',
    reverse: false,
  },
  {
    id: 18,
    text: 'We budget together and review our financial progress regularly',
    type: 'likert',
    scale: 5,
    category: 'habits',
    reverse: false,
  },
  {
    id: 19,
    text: 'Our spending habits are compatible and we rarely disagree about purchases',
    type: 'likert',
    scale: 5,
    category: 'habits',
    reverse: false,
  },
  {
    id: 20,
    text: 'We have an emergency fund or plan for unexpected expenses',
    type: 'likert',
    scale: 5,
    category: 'habits',
    reverse: false,
  },
  {
    id: 21,
    text: 'We discuss purchases over a certain threshold before making them',
    type: 'likert',
    scale: 5,
    category: 'habits',
    reverse: false,
  },
  {
    id: 22,
    text: 'Financial stress does not negatively impact our relationship',
    type: 'likert',
    scale: 5,
    category: 'habits',
    reverse: false,
  },
];

// ============================================================================
// SEXUAL COMPATIBILITY — 25 Questions
// Categories: desire, communication, boundaries, satisfaction
// ============================================================================

export const sexualCompatibilityQuestions = [
  // Desire & Frequency (6 questions)
  {
    id: 1,
    text: 'My partner and I have similar levels of sexual desire',
    type: 'likert',
    scale: 5,
    category: 'desire',
    reverse: false,
  },
  {
    id: 2,
    text: 'I feel satisfied with the frequency of our sexual intimacy',
    type: 'likert',
    scale: 5,
    category: 'desire',
    reverse: false,
  },
  {
    id: 3,
    text: 'I can talk openly with my partner about my sexual needs and desires',
    type: 'likert',
    scale: 5,
    category: 'desire',
    reverse: false,
  },
  {
    id: 4,
    text: 'My partner makes me feel desired and attractive',
    type: 'likert',
    scale: 5,
    category: 'desire',
    reverse: false,
  },
  {
    id: 5,
    text: 'We are both comfortable with the pace of our sexual relationship',
    type: 'likert',
    scale: 5,
    category: 'desire',
    reverse: false,
  },
  {
    id: 6,
    text: 'I feel comfortable initiating sex with my partner',
    type: 'likert',
    scale: 5,
    category: 'desire',
    reverse: false,
  },

  // Communication (6 questions)
  {
    id: 7,
    text: 'I can openly discuss what I enjoy and do not enjoy sexually',
    type: 'likert',
    scale: 5,
    category: 'communication',
    reverse: false,
  },
  {
    id: 8,
    text: 'My partner listens and responds positively when I share sexual feedback',
    type: 'likert',
    scale: 5,
    category: 'communication',
    reverse: false,
  },
  {
    id: 9,
    text: 'We can discuss sexual topics without feeling embarrassed or uncomfortable',
    type: 'likert',
    scale: 5,
    category: 'communication',
    reverse: false,
  },
  {
    id: 10,
    text: 'I feel comfortable telling my partner if something is not working for me',
    type: 'likert',
    scale: 5,
    category: 'communication',
    reverse: false,
  },
  {
    id: 11,
    text: 'We explore new things together and discuss trying new experiences',
    type: 'likert',
    scale: 5,
    category: 'communication',
    reverse: false,
  },
  {
    id: 12,
    text: 'My partner asks about my preferences and follows up on my feedback',
    type: 'likert',
    scale: 5,
    category: 'communication',
    reverse: false,
  },

  // Boundaries & Consent (6 questions)
  {
    id: 13,
    text: 'I feel completely safe expressing my boundaries around sex',
    type: 'likert',
    scale: 5,
    category: 'boundaries',
    reverse: false,
  },
  {
    id: 14,
    text: 'My partner respects my boundaries without question or pressure',
    type: 'likert',
    scale: 5,
    category: 'boundaries',
    reverse: false,
  },
  {
    id: 15,
    text: 'I feel comfortable saying no to sex or certain sexual activities',
    type: 'likert',
    scale: 5,
    category: 'boundaries',
    reverse: false,
  },
  {
    id: 16,
    text: 'We have an ongoing conversation about consent that feels natural',
    type: 'likert',
    scale: 5,
    category: 'boundaries',
    reverse: false,
  },
  {
    id: 17,
    text: 'I trust my partner to respect my physical and emotional boundaries',
    type: 'likert',
    scale: 5,
    category: 'boundaries',
    reverse: false,
  },
  {
    id: 18,
    text: 'My partner never makes me feel guilty for setting boundaries',
    type: 'likert',
    scale: 5,
    category: 'boundaries',
    reverse: false,
  },

  // Satisfaction & Fulfillment (7 questions)
  {
    id: 19,
    text: 'I feel sexually fulfilled in our relationship',
    type: 'likert',
    scale: 5,
    category: 'satisfaction',
    reverse: false,
  },
  {
    id: 20,
    text: 'Our sexual connection has improved or deepened over time',
    type: 'likert',
    scale: 5,
    category: 'satisfaction',
    reverse: false,
  },
  {
    id: 21,
    text: 'I feel emotionally connected to my partner during physical intimacy',
    type: 'likert',
    scale: 5,
    category: 'satisfaction',
    reverse: false,
  },
  {
    id: 22,
    text: 'We prioritize our sexual relationship even during busy or stressful periods',
    type: 'likert',
    scale: 5,
    category: 'satisfaction',
    reverse: false,
  },
  {
    id: 23,
    text: 'I feel comfortable being vulnerable and intimate with my partner',
    type: 'likert',
    scale: 5,
    category: 'satisfaction',
    reverse: false,
  },
  {
    id: 24,
    text: 'Our sexual relationship feels satisfying for both of us',
    type: 'likert',
    scale: 5,
    category: 'satisfaction',
    reverse: false,
  },
  {
    id: 25,
    text: 'I am happy with how we balance emotional and physical intimacy',
    type: 'likert',
    scale: 5,
    category: 'satisfaction',
    reverse: false,
  },
];

// ============================================================================
// SHARED MEANING — 30 Questions
// Categories: rituals, goals, roles, legacy, growth
// ============================================================================

export const sharedMeaningQuestions = [
  // Shared Rituals (6 questions)
  {
    id: 1,
    text: 'We have established meaningful rituals together (e.g., date night, morning coffee)',
    type: 'likert',
    scale: 5,
    category: 'rituals',
    reverse: false,
  },
  {
    id: 2,
    text: 'We create new traditions together that feel special to us as a couple',
    type: 'likert',
    scale: 5,
    category: 'rituals',
    reverse: false,
  },
  {
    id: 3,
    text: 'We have rituals that mark important occasions (anniversaries, milestones)',
    type: 'likert',
    scale: 5,
    category: 'rituals',
    reverse: false,
  },
  {
    id: 4,
    text: 'Our daily routines include elements that strengthen our connection',
    type: 'likert',
    scale: 5,
    category: 'rituals',
    reverse: false,
  },
  {
    id: 5,
    text: 'We have inside jokes, nicknames, or references that are unique to us',
    type: 'likert',
    scale: 5,
    category: 'rituals',
    reverse: false,
  },
  {
    id: 6,
    text: 'We regularly reflect together on our relationship and what is working',
    type: 'likert',
    scale: 5,
    category: 'rituals',
    reverse: false,
  },

  // Shared Goals (6 questions)
  {
    id: 7,
    text: 'We have clear, shared goals for our future together',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },
  {
    id: 8,
    text: 'We regularly discuss and update our life plans together',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },
  {
    id: 9,
    text: 'Our individual goals support and align with each other',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },
  {
    id: 10,
    text: 'We work together as a team to achieve our shared dreams',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },
  {
    id: 11,
    text: 'We have discussed and agree on major life decisions (career, location, family)',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },
  {
    id: 12,
    text: 'We inspire each other to grow and pursue our individual aspirations',
    type: 'likert',
    scale: 5,
    category: 'goals',
    reverse: false,
  },

  // Shared Roles (6 questions)
  {
    id: 13,
    text: 'We have clear, agreed-upon roles and responsibilities in our partnership',
    type: 'likert',
    scale: 5,
    category: 'roles',
    reverse: false,
  },
  {
    id: 14,
    text: 'We share responsibilities in a way that feels fair and balanced',
    type: 'likert',
    scale: 5,
    category: 'roles',
    reverse: false,
  },
  {
    id: 15,
    text: 'We both contribute to decisions about our shared life',
    type: 'likert',
    scale: 5,
    category: 'roles',
    reverse: false,
  },
  {
    id: 16,
    text: 'We can discuss and adjust our roles as life circumstances change',
    type: 'likert',
    scale: 5,
    category: 'roles',
    reverse: false,
  },
  {
    id: 17,
    text: 'We support each other roles as individuals beyond the partnership',
    type: 'likert',
    scale: 5,
    category: 'roles',
    reverse: false,
  },
  {
    id: 18,
    text: 'We are a unified team facing lifes challenges together',
    type: 'likert',
    scale: 5,
    category: 'roles',
    reverse: false,
  },

  // Shared Legacy (6 questions)
  {
    id: 19,
    text: 'We have discussed what kind of life we want to build together',
    type: 'likert',
    scale: 5,
    category: 'legacy',
    reverse: false,
  },
  {
    id: 20,
    text: 'We want to create something meaningful that extends beyond ourselves',
    type: 'likert',
    scale: 5,
    category: 'legacy',
    reverse: false,
  },
  {
    id: 21,
    text: 'We share a vision for how we want to contribute to the world',
    type: 'likert',
    scale: 5,
    category: 'legacy',
    reverse: false,
  },
  {
    id: 22,
    text: 'We have discussed how we want to raise future generations (if applicable)',
    type: 'likert',
    scale: 5,
    category: 'legacy',
    reverse: false,
  },
  {
    id: 23,
    text: 'We care about building a legacy together that reflects our values',
    type: 'likert',
    scale: 5,
    category: 'legacy',
    reverse: false,
  },
  {
    id: 24,
    text: 'We want to be remembered as a couple who made a positive impact',
    type: 'likert',
    scale: 5,
    category: 'legacy',
    reverse: false,
  },

  // Shared Growth (6 questions)
  {
    id: 25,
    text: 'We grow together rather than apart over time',
    type: 'likert',
    scale: 5,
    category: 'growth',
    reverse: false,
  },
  {
    id: 26,
    text: 'We encourage and support each other personal development',
    type: 'likert',
    scale: 5,
    category: 'growth',
    reverse: false,
  },
  {
    id: 27,
    text: 'We learn new things together and explore new experiences as a couple',
    type: 'likert',
    scale: 5,
    category: 'growth',
    reverse: false,
  },
  {
    id: 28,
    text: 'Our relationship has evolved and deepened over time',
    type: 'likert',
    scale: 5,
    category: 'growth',
    reverse: false,
  },
  {
    id: 29,
    text: 'We adapt to changes together and emerge stronger from challenges',
    type: 'likert',
    scale: 5,
    category: 'growth',
    reverse: false,
  },
  {
    id: 30,
    text: 'We invest in our relationship as much as we invest in ourselves individually',
    type: 'likert',
    scale: 5,
    category: 'growth',
    reverse: false,
  },
];

// ============================================================================
// RELATIONSHIP SATISFACTION — 14 Questions (RDAS-based)
// Categories: consensus, satisfaction, cohesion
// ============================================================================

export const relationshipSatisfactionQuestions = [
  // Consensus (5 questions)
  {
    id: 1,
    text: 'My partner and I agree on how to handle household responsibilities',
    type: 'likert',
    scale: 5,
    category: 'consensus',
    reverse: false,
  },
  {
    id: 2,
    text: 'We see eye-to-eye on most major life decisions and priorities',
    type: 'likert',
    scale: 5,
    category: 'consensus',
    reverse: false,
  },
  {
    id: 3,
    text: 'We share similar views on how we want to live our lives',
    type: 'likert',
    scale: 5,
    category: 'consensus',
    reverse: false,
  },
  {
    id: 4,
    text: 'We agree on how to manage finances and financial priorities',
    type: 'likert',
    scale: 5,
    category: 'consensus',
    reverse: false,
  },
  {
    id: 5,
    text: 'We align on values and beliefs that matter most in our relationship',
    type: 'likert',
    scale: 5,
    category: 'consensus',
    reverse: false,
  },

  // Satisfaction (5 questions)
  {
    id: 6,
    text: 'I am satisfied with the overall quality of our relationship',
    type: 'likert',
    scale: 5,
    category: 'satisfaction',
    reverse: false,
  },
  {
    id: 7,
    text: 'I am happy with how our relationship has turned out so far',
    type: 'likert',
    scale: 5,
    category: 'satisfaction',
    reverse: false,
  },
  {
    id: 8,
    text: 'Our relationship meets my expectations and needs',
    type: 'likert',
    scale: 5,
    category: 'satisfaction',
    reverse: false,
  },
  {
    id: 9,
    text: 'I would choose the same partner if I could do it over again',
    type: 'likert',
    scale: 5,
    category: 'satisfaction',
    reverse: false,
  },
  {
    id: 10,
    text: 'Overall, I feel our relationship is successful',
    type: 'likert',
    scale: 5,
    category: 'satisfaction',
    reverse: false,
  },

  // Cohesion (4 questions)
  {
    id: 11,
    text: 'We enjoy spending time together and feel a strong sense of closeness',
    type: 'likert',
    scale: 5,
    category: 'cohesion',
    reverse: false,
  },
  {
    id: 12,
    text: 'We work well as a team and support each other through challenges',
    type: 'likert',
    scale: 5,
    category: 'cohesion',
    reverse: false,
  },
  {
    id: 13,
    text: 'We share a strong connection and feel we belong together',
    type: 'likert',
    scale: 5,
    category: 'cohesion',
    reverse: false,
  },
  {
    id: 14,
    text: 'We make a great team and can count on each other no matter what',
    type: 'likert',
    scale: 5,
    category: 'cohesion',
    reverse: false,
  },
];

// ============================================================================
// STRESS & COPING — 20 Questions
// Categories: individual, partner, team
// ============================================================================

export const stressCopingQuestions = [
  // Individual Coping (7 questions)
  {
    id: 1,
    text: 'I can manage my stress levels effectively without them affecting my relationship',
    type: 'likert',
    scale: 5,
    category: 'individual',
    reverse: false,
  },
  {
    id: 2,
    text: 'When stressed, I use healthy coping strategies (exercise, talking, journaling)',
    type: 'likert',
    scale: 5,
    category: 'individual',
    reverse: false,
  },
  {
    id: 3,
    text: 'I recognize when stress is affecting my mood and behavior',
    type: 'likert',
    scale: 5,
    category: 'individual',
    reverse: false,
  },
  {
    id: 4,
    text: 'I do not take my stress out on my partner when things get difficult',
    type: 'likert',
    scale: 5,
    category: 'individual',
    reverse: false,
  },
  {
    id: 5,
    text: 'I can separate work stress from my home life and relationship',
    type: 'likert',
    scale: 5,
    category: 'individual',
    reverse: false,
  },
  {
    id: 6,
    text: 'I maintain my own well-being even during stressful periods',
    type: 'likert',
    scale: 5,
    category: 'individual',
    reverse: false,
  },
  {
    id: 7,
    text: 'I know when I need support and can ask my partner for help',
    type: 'likert',
    scale: 5,
    category: 'individual',
    reverse: false,
  },

  // Partner Support (7 questions)
  {
    id: 8,
    text: 'My partner is supportive when I am going through stressful periods',
    type: 'likert',
    scale: 5,
    category: 'partner',
    reverse: false,
  },
  {
    id: 9,
    text: 'My partner gives me space when I need it but also checks in on me',
    type: 'likert',
    scale: 5,
    category: 'partner',
    reverse: false,
  },
  {
    id: 10,
    text: 'I can lean on my partner for emotional support during hard times',
    type: 'likert',
    scale: 5,
    category: 'partner',
    reverse: false,
  },
  {
    id: 11,
    text: 'My partner helps me see stressful situations more clearly',
    type: 'likert',
    scale: 5,
    category: 'partner',
    reverse: false,
  },
  {
    id: 12,
    text: 'When I am stressed, my partner does not make it worse with their own reactions',
    type: 'likert',
    scale: 5,
    category: 'partner',
    reverse: false,
  },
  {
    id: 13,
    text: 'My partner is patient with me when stress makes me less present',
    type: 'likert',
    scale: 5,
    category: 'partner',
    reverse: false,
  },
  {
    id: 14,
    text: 'I feel comfortable sharing my stress with my partner without judgment',
    type: 'likert',
    scale: 5,
    category: 'partner',
    reverse: false,
  },

  // Team Coping (6 questions)
  {
    id: 15,
    text: 'We handle financial stress together as a team',
    type: 'likert',
    scale: 5,
    category: 'team',
    reverse: false,
  },
  {
    id: 16,
    text: 'We support each other through work-related stress and career challenges',
    type: 'likert',
    scale: 5,
    category: 'team',
    reverse: false,
  },
  {
    id: 17,
    text: 'When external pressures threaten our relationship, we face them together',
    type: 'likert',
    scale: 5,
    category: 'team',
    reverse: false,
  },
  {
    id: 18,
    text: 'We can talk about stress without it turning into conflict',
    type: 'likert',
    scale: 5,
    category: 'team',
    reverse: false,
  },
  {
    id: 19,
    text: 'Our relationship remains stable even when external stressors increase',
    type: 'likert',
    scale: 5,
    category: 'team',
    reverse: false,
  },
  {
    id: 20,
    text: 'We have strategies for coping with stress that we practice together',
    type: 'likert',
    scale: 5,
    category: 'team',
    reverse: false,
  },
];

// ============================================================================
// FUN & PERSONALITY — 18 Questions
// Categories: playfulness, shared activities, humor, adventure
// ============================================================================

export const funPersonalityQuestions = [
  // Playfulness (5 questions)
  {
    id: 1,
    text: 'I consider myself a playful person who enjoys laughter and lighthearted moments',
    type: 'likert',
    scale: 5,
    category: 'playfulness',
    reverse: false,
  },
  {
    id: 2,
    text: 'My partner and I enjoy being silly and playful together',
    type: 'likert',
    scale: 5,
    category: 'playfulness',
    reverse: false,
  },
  {
    id: 3,
    text: 'We can laugh at ourselves and not take everything so seriously',
    type: 'likert',
    scale: 5,
    category: 'playfulness',
    reverse: false,
  },
  {
    id: 4,
    text: 'Our relationship feels fun and enjoyable most of the time',
    type: 'likert',
    scale: 5,
    category: 'playfulness',
    reverse: false,
  },
  {
    id: 5,
    text: 'We retain a sense of childlike wonder and excitement together',
    type: 'likert',
    scale: 5,
    category: 'playfulness',
    reverse: false,
  },

  // Shared Activities (5 questions)
  {
    id: 6,
    text: 'We have shared hobbies or activities that we enjoy doing together',
    type: 'likert',
    scale: 5,
    category: 'activities',
    reverse: false,
  },
  {
    id: 7,
    text: 'We regularly try new activities or explore new experiences together',
    type: 'likert',
    scale: 5,
    category: 'activities',
    reverse: false,
  },
  {
    id: 8,
    text: 'We enjoy spending quality time together doing things we both love',
    type: 'likert',
    scale: 5,
    category: 'activities',
    reverse: false,
  },
  {
    id: 9,
    text: 'We make time for fun and recreation even when life is busy',
    type: 'likert',
    scale: 5,
    category: 'activities',
    reverse: false,
  },
  {
    id: 10,
    text: 'Our shared activities bring us closer and create lasting memories',
    type: 'likert',
    scale: 5,
    category: 'activities',
    reverse: false,
  },

  // Humor (4 questions)
  {
    id: 11,
    text: 'We share a similar sense of humor and make each other laugh',
    type: 'likert',
    scale: 5,
    category: 'humor',
    reverse: false,
  },
  {
    id: 12,
    text: 'Laughter is a big part of our relationship',
    type: 'likert',
    scale: 5,
    category: 'humor',
    reverse: false,
  },
  {
    id: 13,
    text: 'We can laugh together even during difficult times',
    type: 'likert',
    scale: 5,
    category: 'humor',
    reverse: false,
  },
  {
    id: 14,
    text: 'We use humor to lighten tense moments and navigate conflict',
    type: 'likert',
    scale: 5,
    category: 'humor',
    reverse: false,
  },

  // Adventure (4 questions)
  {
    id: 15,
    text: 'We enjoy spontaneous adventures and trying new things together',
    type: 'likert',
    scale: 5,
    category: 'adventure',
    reverse: false,
  },
  {
    id: 16,
    text: 'We share a spirit of curiosity and love exploring together',
    type: 'likert',
    scale: 5,
    category: 'adventure',
    reverse: false,
  },
  {
    id: 17,
    text: 'We plan exciting experiences and look forward to them together',
    type: 'likert',
    scale: 5,
    category: 'adventure',
    reverse: false,
  },
  {
    id: 18,
    text: 'We have a bucket list or goals that include adventurous experiences together',
    type: 'likert',
    scale: 5,
    category: 'adventure',
    reverse: false,
  },
];

// ============================================================================
// APPRECIATION & GRATITUDE — 15 Questions
// Categories: expression, recognition, positivity
// ============================================================================

export const appreciationGratitudeQuestions = [
  // Expression (5 questions)
  {
    id: 1,
    text: 'I regularly tell my partner things I appreciate about them',
    type: 'likert',
    scale: 5,
    category: 'expression',
    reverse: false,
  },
  {
    id: 2,
    text: 'I express gratitude for the small things my partner does daily',
    type: 'likert',
    scale: 5,
    category: 'expression',
    reverse: false,
  },
  {
    id: 3,
    text: 'I show appreciation for my partner more often than I take them for granted',
    type: 'likert',
    scale: 5,
    category: 'expression',
    reverse: false,
  },
  {
    id: 4,
    text: 'I make it a habit to notice and acknowledge my partner efforts',
    type: 'likert',
    scale: 5,
    category: 'expression',
    reverse: false,
  },
  {
    id: 5,
    text: 'I express thanks and gratitude rather than assuming my partner knows how I feel',
    type: 'likert',
    scale: 5,
    category: 'expression',
    reverse: false,
  },

  // Recognition (5 questions)
  {
    id: 6,
    text: 'I recognize and acknowledge my partner contributions to our relationship',
    type: 'likert',
    scale: 5,
    category: 'recognition',
    reverse: false,
  },
  {
    id: 7,
    text: 'I celebrate my partner successes and accomplishments',
    type: 'likert',
    scale: 5,
    category: 'recognition',
    reverse: false,
  },
  {
    id: 8,
    text: 'I make my partner feel valued and seen for who they are',
    type: 'likert',
    scale: 5,
    category: 'recognition',
    reverse: false,
  },
  {
    id: 9,
    text: 'I notice the effort my partner puts into our relationship and show I notice',
    type: 'likert',
    scale: 5,
    category: 'recognition',
    reverse: false,
  },
  {
    id: 10,
    text: 'My partner makes me feel appreciated and valued',
    type: 'likert',
    scale: 5,
    category: 'recognition',
    reverse: false,
  },

  // Positivity (5 questions)
  {
    id: 11,
    text: 'I focus on what I love about my partner rather than their flaws',
    type: 'likert',
    scale: 5,
    category: 'positivity',
    reverse: false,
  },
  {
    id: 12,
    text: 'I am grateful for our relationship and tell my partner that',
    type: 'likert',
    scale: 5,
    category: 'positivity',
    reverse: false,
  },
  {
    id: 13,
    text: 'I regularly reflect on the positive aspects of our relationship',
    type: 'likert',
    scale: 5,
    category: 'positivity',
    reverse: false,
  },
  {
    id: 14,
    text: 'I end each day with gratitude for my partner presence in my life',
    type: 'likert',
    scale: 5,
    category: 'positivity',
    reverse: false,
  },
  {
    id: 15,
    text: 'Gratitude and appreciation are natural parts of how we communicate',
    type: 'likert',
    scale: 5,
    category: 'positivity',
    reverse: false,
  },
];

// ============================================================================
// QUESTION BANK MAP
// ============================================================================

export const assessmentQuestionBanks = {
  'love-languages': loveLanguagesQuestions,
  'attachment-style': attachmentStyleQuestions,
  'communication-style': communicationStyleQuestions,
  'gottman-four-horsemen': gottmanFourHorsemenQuestions,
  'conflict-resolution': conflictResolutionQuestions,
  'values-alignment': valuesAlignmentQuestions,
  'emotional-intelligence': emotionalIntelligenceQuestions,
  'intimacy-closeness': intimacyClosenessQuestions,
  'trust-vulnerability': trustVulnerabilityQuestions,
  'financial-values': financialValuesQuestions,
  'sexual-compatibility': sexualCompatibilityQuestions,
  'shared-meaning': sharedMeaningQuestions,
  'relationship-satisfaction': relationshipSatisfactionQuestions,
  'stress-coping': stressCopingQuestions,
  'fun-personality': funPersonalityQuestions,
  'appreciation-gratitude': appreciationGratitudeQuestions,
};

// Helper to get assessment by ID
export function getAssessmentById(id) {
  return allAssessments.find(a => a.id === id);
}

// Helper to get questions for an assessment
export function getQuestionsForAssessment(assessmentId) {
  return assessmentQuestionBanks[assessmentId] || [];
}

// Calculate category scores for an assessment
export function calculateCategoryScores(assessmentId, answers) {
  const questions = getQuestionsForAssessment(assessmentId);
  const categoryScores = {};

  // Group questions by category
  questions.forEach(q => {
    if (!categoryScores[q.category]) {
      categoryScores[q.category] = { total: 0, count: 0 };
    }
    const answer = answers[q.id];
    if (answer !== undefined) {
      let value = parseInt(answer);
      if (q.reverse) {
        value = 6 - value; // Reverse 5-point scale
      }
      categoryScores[q.category].total += value;
      categoryScores[q.category].count += 1;
    }
  });

  // Calculate averages
  const result = {};
  Object.keys(categoryScores).forEach(cat => {
    const score = categoryScores[cat];
    result[cat] = score.count > 0 ? (score.total / score.count) : 0;
  });

  return result;
}