-- 013: activities, daily questions, check-in topics, and monthly deep-dive themes.
--
-- DRAFT: requires review before launch. Every row is inserted with review_status = 'draft';
-- mark items 'approved' after review. Pre-launch check:
--   SELECT 'activity', activity_key FROM activities WHERE review_status <> 'approved'
--   UNION ALL SELECT 'question', question FROM daily_questions WHERE active AND review_status <> 'approved'
--   UNION ALL SELECT 'topic', topic_key FROM check_in_topics WHERE review_status <> 'approved'
--   UNION ALL SELECT 'theme', theme_key FROM deep_dive_themes WHERE review_status <> 'approved';
--
-- Generated from authored content (Claude-drafted; each item names its framework).
-- Keeps the sample rows seeded by bond_seed.sql: the four activities and six check-in topics get
-- stable keys (matched by title/name), and the eight daily questions are kept verbatim.
-- Daily questions run in sort_order as a rotation (see the app's daily-question screen);
-- questions no longer in the list are deactivated, not deleted, so past answers keep their question.
--
-- Requires 011_content_architecture.sql. Safe to re-run.

BEGIN;

-- ============ ACTIVITIES (42)
UPDATE activities SET activity_key = 'three-worst-things' WHERE activity_key IS NULL AND title = 'Three Worst Things';
UPDATE activities SET activity_key = 'ideal-day' WHERE activity_key IS NULL AND title = 'Ideal Day';
UPDATE activities SET activity_key = 'memory-lane-walk' WHERE activity_key IS NULL AND title = 'Memory Lane Walk';
UPDATE activities SET activity_key = 'relationship-timeline' WHERE activity_key IS NULL AND title = 'Relationship Timeline';
INSERT INTO activities (activity_key, type, category, title, description, duration, difficulty, framework, content, sort_order, review_status) VALUES
  ('ideal-day', 'conversation_starter', 'connection', 'Ideal Day', 'Share what your ideal day off together would look like.', '15 min', 'easy', 'Gottman Method (love maps)', '{"prompt": "Describe your ideal day off together from morning to night.", "followUp": "What is one thing from each person''s version you could make happen this month?"}'::jsonb, 10, 'draft'),
  ('memory-lane-walk', 'activity', 'connection', 'Memory Lane Walk', 'Take a walk together and share one memory from each year you have been together.', '30 min', 'medium', 'Gottman Method (fondness and admiration)', '{"instructions": ["Find a time to walk together outside.", "Take turns sharing one memory from each year you have been together.", "For each memory, say what it meant to you then and what it means now."], "followUp": "Save one of the memories to Memory Lane."}'::jsonb, 20, 'draft'),
  ('six-second-kiss', 'challenge', 'connection', 'The Six-Second Kiss', 'Swap the quick peck for a kiss long enough to actually feel connected.', '1 week', 'easy', 'Gottman Method (rituals of connection)', '{"instructions": ["For one week, greet and say goodbye to each other with a six-second kiss.", "Notice how it changes the moment of leaving or reuniting."], "followUp": "At the end of the week, talk about whether you want to keep the ritual."}'::jsonb, 30, 'draft'),
  ('stress-reducing-conversation', 'conversation_starter', 'connection', 'Stress-Reducing Conversation', 'A daily check-in about stress outside the relationship, where the listener is fully on the speaker''s side.', '20 min', 'medium', 'Gottman Method', '{"prompt": "What was the most stressful part of your day or week — outside of us?", "instructions": ["Take turns: one person talks for about 10 minutes, then switch.", "The listener shows interest and takes their partner''s side.", "Don''t offer solutions unless asked; understanding comes first."], "rules": "This conversation is only about stress outside the relationship."}'::jsonb, 40, 'draft'),
  ('love-map-questions', 'conversation_starter', 'connection', 'Love Map Update', 'Catch up on each other''s inner world with a few curious questions.', '15 min', 'easy', 'Gottman Method (love maps)', '{"instructions": ["Take turns asking: Who is your closest friend at the moment?", "What is something you''re worried about right now?", "What is something you''re looking forward to?", "What would you do with a completely free day?"], "followUp": "Did any answer surprise you?"}'::jsonb, 50, 'draft'),
  ('reunion-ritual', 'challenge', 'connection', 'Design a Reunion Ritual', 'Create a small, repeatable way to reconnect at the end of each day.', '10 min', 'easy', 'Gottman Method (rituals of connection)', '{"instructions": ["Talk about how your reunions usually go when you get home.", "Design a 5-minute ritual: a hug, a question, a cup of tea together.", "Try it every day for two weeks."], "followUp": "What made the ritual easy or hard to keep?"}'::jsonb, 60, 'draft'),
  ('closeness-questions', 'conversation_starter', 'connection', 'Growing Closer Questions', 'A set of questions that gradually get more personal, designed to build closeness.', '45 min', 'medium', 'Closeness-generating research (Aron et al.)', '{"instructions": ["Take turns answering each question. Go slowly.", "If you could have dinner with anyone, who would it be and why?", "What would a perfect ordinary day look like for you?", "What is something you are deeply grateful for?", "What is a memory you treasure?", "What does friendship mean to you?", "What is something you''ve always wanted to tell me?"], "rules": "Either of you can pass on a question."}'::jsonb, 70, 'draft'),
  ('tech-free-evening', 'challenge', 'connection', 'Tech-Free Evening', 'Spend one evening with phones away and full attention on each other.', '1 evening', 'easy', 'Technoference research', '{"instructions": ["Pick an evening and put both phones in another room.", "Cook, walk, play a game, or just talk.", "Notice what fills the space."], "followUp": "Is there a regular phone-free time you''d like to keep?"}'::jsonb, 80, 'draft'),
  ('three-worst-things', 'conversation_starter', 'communication', 'Three Worst Things', 'Each partner shares three small things that bother them, and the other just listens.', '10 min', 'easy', 'Gottman Method (gentle start-up)', '{"prompt": "What are three small things that bother you in our relationship?", "rules": "No solving during the share — just listening. Then each person picks one to work on."}'::jsonb, 90, 'draft'),
  ('speaker-listener', 'scenario', 'communication', 'Speaker–Listener Practice', 'A structured way to talk about a sensitive topic, one person at a time.', '20 min', 'medium', 'PREP (Speaker–Listener technique)', '{"instructions": ["Choose a small, low-stakes topic.", "The speaker holds an object (the \"floor\") and shares short pieces of their view.", "The listener paraphrases what they heard before responding.", "Switch the floor after a few rounds."], "rules": "The listener doesn''t argue or solve while paraphrasing."}'::jsonb, 100, 'draft'),
  ('soft-startup-rewrite', 'scenario', 'communication', 'Soft Start-Up Rewrite', 'Practice turning a harsh complaint into a gentle request.', '15 min', 'easy', 'Gottman Method (gentle start-up)', '{"prompt": "Rewrite: \"You never help around the house.\"", "instructions": ["Together, rewrite the complaint using \"I feel… about… I need…\".", "Each write one real complaint of your own the same way.", "Read them to each other and notice how they land."]}'::jsonb, 110, 'draft'),
  ('needs-and-requests', 'challenge', 'communication', 'Observation, Feeling, Need, Request', 'Practice making clear requests instead of criticisms.', '15 min', 'easy', 'Nonviolent Communication', '{"instructions": ["Each think of something you''d like to change.", "Write it as: When I see… I feel… because I need… Would you be willing to…?", "Share, and let your partner respond with yes, no, or a counteroffer."]}'::jsonb, 120, 'draft'),
  ('state-of-the-union', 'conversation_starter', 'communication', 'Weekly State of the Union', 'A weekly meeting to appreciate each other and talk through one issue calmly.', '45 min', 'medium', 'Gottman Method', '{"instructions": ["Start with five appreciations each.", "Each share what went well this week.", "Choose one issue; each share your view while the other listens and summarizes.", "End by asking: \"What can I do to make you feel loved this week?\""]}'::jsonb, 130, 'draft'),
  ('validation-practice', 'scenario', 'communication', 'Validation Practice', 'Practice letting your partner know their feelings make sense — even when you see it differently.', '15 min', 'easy', 'Validation (Gottman Method, DBT)', '{"instructions": ["One partner shares a recent frustration (not about the relationship).", "The listener responds with: \"That makes sense because…\"", "Switch roles."], "rules": "Validation isn''t agreement — it''s understanding."}'::jsonb, 140, 'draft'),
  ('repair-phrase-menu', 'challenge', 'conflict', 'Repair Phrase Menu', 'Choose phrases you can use to de-escalate when a conversation heats up.', '10 min', 'easy', 'Gottman Method (repair attempts)', '{"instructions": ["Together, choose phrases you''d welcome in a tense moment, e.g. \"Can we start over?\", \"I''m feeling overwhelmed\", \"I see your point.\"", "Write your favorites down somewhere you''ll both see.", "Agree to accept a repair attempt when it''s offered."]}'::jsonb, 150, 'draft'),
  ('time-out-plan', 'activity', 'conflict', 'Make a Time-Out Plan', 'Agree on how to pause and come back when either of you gets flooded.', '15 min', 'easy', 'Gottman Method (flooding)', '{"instructions": ["Agree on a signal or phrase for \"I need a break.\"", "Agree on how long a break lasts (at least 20 minutes, usually less than 24 hours).", "Decide who will restart the conversation and how.", "During breaks, do something soothing — not rehearsing the argument."]}'::jsonb, 160, 'draft'),
  ('processing-a-past-argument', 'conversation_starter', 'conflict', 'Processing a Past Argument', 'Look back at a past disagreement calmly, to understand each other rather than re-fight it.', '30 min', 'hard', 'Gottman Method (processing a regrettable incident)', '{"instructions": ["Pick an argument that is over and that you both feel calm about now.", "Each share what you felt during it, without debating the facts.", "Each share what you think triggered you — often something older than the argument.", "Each own one part you''d do differently.", "Agree on one thing that would help next time."], "rules": "Stop and take a break if either of you feels flooded. These tools are for couples who feel safe with each other. If you are afraid of your partner, or conflict involves threats, intimidation, or physical harm, relationship exercises are not the right tool. In the US you can reach the National Domestic Violence Hotline at 1-800-799-7233 (or text START to 88788)."}'::jsonb, 170, 'draft'),
  ('dreams-within-conflict', 'conversation_starter', 'conflict', 'Dreams Within Conflict', 'Explore the deeper hopes behind a recurring disagreement.', '30 min', 'hard', 'Gottman Method (gridlock)', '{"prompt": "Choose a recurring disagreement. What deeper hope, value, or story is behind your position?", "instructions": ["One partner speaks about their dream; the other asks curious questions.", "Useful questions: \"What does this mean to you?\", \"Is there a story behind this?\"", "Switch roles, then talk about what you understand now."], "rules": "The goal is understanding, not solving."}'::jsonb, 180, 'draft'),
  ('compromise-circles', 'activity', 'conflict', 'Compromise Circles', 'Find the flexible middle ground in a disagreement.', '20 min', 'medium', 'Gottman Method (accepting influence)', '{"instructions": ["Each draw two circles, one inside the other.", "In the inner circle, write what you can''t give up on this issue.", "In the outer circle, write where you can be flexible.", "Compare and look for a shared plan that respects both inner circles."]}'::jsonb, 190, 'draft'),
  ('yes-and-week', 'challenge', 'conflict', '"Yes, And" Week', 'Practice accepting influence by building on each other''s ideas.', '1 week', 'easy', 'Gottman Method (accepting influence)', '{"instructions": ["For one week, when your partner suggests something, start with \"Yes, and…\" before any \"but\".", "Notice how often you can find something to agree with."], "followUp": "Did it change how decisions felt?"}'::jsonb, 200, 'draft'),
  ('appreciation-jar', 'challenge', 'appreciation', 'Appreciation Jar', 'Collect small notes of appreciation for each other over a week.', '1 week', 'easy', 'Gottman Method (fondness and admiration)', '{"instructions": ["Each day, write one specific thing you appreciated about your partner.", "Put the notes in a jar or shared place.", "At the end of the week, read them together."]}'::jsonb, 210, 'draft'),
  ('gratitude-letter', 'journal', 'appreciation', 'Gratitude Letter', 'Write your partner a letter about a specific way they''ve made your life better.', '30 min', 'medium', 'Positive psychology (gratitude interventions)', '{"instructions": ["Think of a specific time your partner made a difference to you.", "Write about what they did and how it affected you.", "Read it to them, or give it to them to read."]}'::jsonb, 220, 'draft'),
  ('fondness-list', 'journal', 'appreciation', 'Fondness and Admiration List', 'List the qualities you admire in your partner, with examples.', '15 min', 'easy', 'Gottman Method (fondness and admiration)', '{"instructions": ["Each write three qualities you admire in your partner.", "For each one, write a moment when you saw it.", "Share your lists."]}'::jsonb, 230, 'draft'),
  ('three-good-things', 'challenge', 'appreciation', 'Three Good Things, Together', 'End each day by naming three good things — at least one about each other.', '5 min a day', 'easy', 'Positive psychology (three good things)', '{"instructions": ["Each night for a week, each share three good things from the day.", "At least one should be about your partner or your relationship."]}'::jsonb, 240, 'draft'),
  ('celebrate-good-news', 'challenge', 'appreciation', 'Celebrate Good News', 'Practice responding to each other''s good news with real enthusiasm.', '1 week', 'easy', 'Capitalization research (Gable)', '{"instructions": ["For one week, when your partner shares good news, ask two follow-up questions.", "Show genuine enthusiasm and help them savor it."], "followUp": "How did it feel to be celebrated?"}'::jsonb, 250, 'draft'),
  ('shared-values-sort', 'activity', 'values', 'Shared Values Sort', 'Discover which values matter most to each of you, and where they overlap.', '30 min', 'medium', 'Values clarification', '{"instructions": ["Each list your top ten values (e.g. family, adventure, security, faith, creativity).", "Narrow to your top five.", "Compare lists: which values overlap and which differ?", "Talk about how your shared values show up in daily life."]}'::jsonb, 260, 'draft'),
  ('rituals-of-connection', 'conversation_starter', 'values', 'Our Rituals', 'Talk about the rituals that make your relationship feel like yours.', '20 min', 'medium', 'Gottman Method (shared meaning)', '{"prompt": "How do we want to mark mornings, weekends, holidays, birthdays, and hard days?", "followUp": "Choose one ritual to start or strengthen."}'::jsonb, 270, 'draft'),
  ('money-stories', 'conversation_starter', 'values', 'Money Stories', 'Share what money meant in each of your families growing up.', '25 min', 'medium', 'Financial relationship research', '{"instructions": ["What was money like in your family growing up?", "What does money mean to you now: security, freedom, generosity, or something else?", "Where do your money values overlap?"]}'::jsonb, 280, 'draft'),
  ('five-year-vision', 'journal', 'values', 'Five-Year Vision', 'Imagine your life together five years from now, then compare notes.', '30 min', 'medium', 'Gottman Method (shared meaning)', '{"instructions": ["Each write a short description of an ordinary day five years from now.", "Include home, work, relationships, and how you spend time together.", "Share and look for common threads."]}'::jsonb, 290, 'draft'),
  ('load-audit', 'activity', 'values', 'Household Load Audit', 'Make the invisible work of running your life visible, and share it fairly.', '30 min', 'medium', 'Household labor research', '{"instructions": ["List every recurring task, including planning and remembering tasks.", "Mark who currently notices, plans, and does each one.", "Choose one area to hand over fully, from noticing to finishing."]}'::jsonb, 300, 'draft'),
  ('closeness-ranking', 'conversation_starter', 'intimacy', 'Kinds of Closeness', 'Compare how much each of you values emotional, physical, intellectual, and shared-time closeness.', '15 min', 'easy', 'Intimacy process research', '{"instructions": ["Each rank emotional, physical, intellectual, and shared-experience closeness.", "Share your rankings and an example of each.", "Plan one moment this week for each partner''s top kind."]}'::jsonb, 310, 'draft'),
  ('affection-menu', 'activity', 'intimacy', 'Affection Menu', 'Create a menu of everyday, non-sexual affection you each enjoy.', '15 min', 'easy', 'Couple intimacy practice', '{"instructions": ["Each list small kinds of affection you enjoy (holding hands, a back rub, a hug from behind).", "Mark your favorites.", "Try one item from your partner''s menu every day this week."]}'::jsonb, 320, 'draft'),
  ('novelty-date', 'challenge', 'fun', 'Something New Date', 'Plan a date doing something neither of you has done before.', '1–3 hours', 'easy', 'Self-expansion research', '{"instructions": ["Brainstorm activities neither of you has tried.", "Pick one and put it on the calendar.", "Afterwards, share what surprised you."]}'::jsonb, 330, 'draft'),
  ('playlist-of-us', 'activity', 'fun', 'Playlist of Us', 'Build a playlist of songs tied to your relationship.', '20 min', 'easy', 'Shared memory and play', '{"instructions": ["Each add five songs that remind you of moments together.", "Listen together and share the story behind each."]}'::jsonb, 340, 'draft'),
  ('would-you-rather', 'conversation_starter', 'fun', 'Would You Rather', 'Playful questions to laugh and learn about each other.', '10 min', 'easy', 'Play and positive affect', '{"instructions": ["Would you rather travel to the past or the future?", "Would you rather live by the beach or in the mountains?", "Would you rather have a quiet night in or a spontaneous adventure?", "Take turns inventing your own."]}'::jsonb, 350, 'draft'),
  ('cook-together', 'challenge', 'fun', 'Cook Something New', 'Cook a recipe neither of you has made before.', '1 hour', 'easy', 'Self-expansion research', '{"instructions": ["Choose a new recipe together.", "Split the tasks and cook side by side.", "Rate the result together — honestly and kindly."]}'::jsonb, 360, 'draft'),
  ('play-date', 'challenge', 'fun', 'Childhood Play Date', 'Play a game you each loved as a kid.', '30 min', 'easy', 'Play and positive affect', '{"instructions": ["Each share a favorite childhood game.", "Play both games together.", "Share one memory the games brought back."]}'::jsonb, 370, 'draft'),
  ('relationship-timeline', 'journal', 'milestones', 'Relationship Timeline', 'Create a timeline of your relationship milestones together.', '20 min', 'easy', 'Gottman Method (oral history)', '{"instructions": ["Mark when you met, your first date, and your first trip.", "Add challenges you overcame together.", "Include moments of joy and growth."]}'::jsonb, 380, 'draft'),
  ('how-we-met', 'conversation_starter', 'milestones', 'Retell How We Met', 'Tell the story of how you met and fell for each other — together.', '20 min', 'easy', 'Gottman Method (oral history)', '{"instructions": ["Take turns telling the story of how you met.", "What did you first notice about each other?", "When did you know this was something special?"]}'::jsonb, 390, 'draft'),
  ('hard-times-we-survived', 'conversation_starter', 'milestones', 'Hard Times We Got Through', 'Remember challenges you faced together and what helped.', '20 min', 'medium', 'We-ness research', '{"instructions": ["Each name a hard time you went through together.", "Talk about what helped you get through it.", "Name one strength as a couple it revealed."]}'::jsonb, 400, 'draft'),
  ('anniversary-letter', 'journal', 'milestones', 'Anniversary Letter', 'Write a letter looking back on the past year together and ahead to the next.', '30 min', 'medium', 'Gottman Method (shared meaning)', '{"instructions": ["Write about three moments from the past year you''re grateful for.", "Write one thing you learned about your partner.", "Write one hope for the coming year.", "Exchange and read the letters."]}'::jsonb, 410, 'draft'),
  ('year-ahead', 'activity', 'milestones', 'Plan the Year Ahead', 'Set a few shared intentions for the coming year.', '45 min', 'medium', 'Goal-setting practice', '{"instructions": ["Each share one hope for yourself and one for your relationship.", "Choose two or three shared intentions.", "Put a check-in on the calendar in three months."]}'::jsonb, 420, 'draft')
ON CONFLICT (activity_key) DO UPDATE SET type = EXCLUDED.type, category = EXCLUDED.category, title = EXCLUDED.title, description = EXCLUDED.description, duration = EXCLUDED.duration, difficulty = EXCLUDED.difficulty, framework = EXCLUDED.framework, content = EXCLUDED.content, sort_order = EXCLUDED.sort_order, review_status = EXCLUDED.review_status;

-- ============ DAILY QUESTIONS (90, in rotation order)
INSERT INTO daily_questions (question, category, depth, priority, sort_order, active, review_status) VALUES
  ('What is one thing I did today that made you feel loved?', 'connection', 'light', 1, 1, TRUE, 'draft'),
  ('What is one thing I could do better at tomorrow?', 'growth', 'medium', 2, 2, TRUE, 'draft'),
  ('What is something you want to talk about but have not brought up?', 'communication', 'deep', 3, 3, TRUE, 'draft'),
  ('What made you laugh or smile today?', 'fun', 'light', 1, 4, TRUE, 'draft'),
  ('If you could change one thing about how we communicate, what would it be?', 'communication', 'medium', 2, 5, TRUE, 'draft'),
  ('What is one thing you are grateful for about us?', 'gratitude', 'light', 1, 6, TRUE, 'draft'),
  ('When did you first feel you could really trust me?', 'memories', 'deep', 3, 7, TRUE, 'draft'),
  ('What is a dream or goal you have that you want us to support?', 'goals', 'medium', 2, 8, TRUE, 'draft'),
  ('What''s one thing that made you feel proud of yourself recently?', 'growth', 'light', 1, 9, TRUE, 'draft'),
  ('What does our relationship need more of right now?', 'connection', 'medium', 2, 10, TRUE, 'draft'),
  ('What''s a part of yourself you''d like me to understand better?', 'connection', 'deep', 3, 11, TRUE, 'draft'),
  ('Which season feels most like "us," and why?', 'memories', 'light', 1, 12, TRUE, 'draft'),
  ('What''s a memory of us that you return to often?', 'memories', 'medium', 2, 13, TRUE, 'draft'),
  ('What''s one thing on your mind that you haven''t mentioned yet today?', 'communication', 'light', 1, 14, TRUE, 'draft'),
  ('What did love look like in the home you grew up in?', 'values', 'deep', 3, 15, TRUE, 'draft'),
  ('What was the best part of your day?', 'connection', 'light', 1, 16, TRUE, 'draft'),
  ('What''s something you''d like us to celebrate more often?', 'gratitude', 'medium', 2, 17, TRUE, 'draft'),
  ('What song has been stuck in your head lately?', 'fun', 'light', 1, 18, TRUE, 'draft'),
  ('What''s a dream you''ve let go of, and how do you feel about it now?', 'goals', 'deep', 3, 19, TRUE, 'draft'),
  ('What''s a value you hope our relationship always reflects?', 'values', 'medium', 2, 20, TRUE, 'draft'),
  ('What''s a small habit of mine that you secretly love?', 'gratitude', 'light', 1, 21, TRUE, 'draft'),
  ('What''s one way I''ve grown since we met?', 'growth', 'medium', 2, 22, TRUE, 'draft'),
  ('What''s one way our relationship has changed you?', 'growth', 'deep', 3, 23, TRUE, 'draft'),
  ('What''s a compliment you received recently that stuck with you?', 'growth', 'light', 1, 24, TRUE, 'draft'),
  ('What''s something about your day that you''d like me to ask about more?', 'communication', 'medium', 2, 25, TRUE, 'draft'),
  ('What was your favorite part of our last weekend?', 'memories', 'light', 1, 26, TRUE, 'draft'),
  ('What''s a fear you have about the future that you''d like to share?', 'communication', 'deep', 3, 27, TRUE, 'draft'),
  ('What''s something you''ve been wanting to try together?', 'goals', 'medium', 2, 28, TRUE, 'draft'),
  ('What''s one thing that made today harder than you expected?', 'communication', 'light', 1, 29, TRUE, 'draft'),
  ('What''s something small you''d love for us to do together this week?', 'connection', 'light', 1, 30, TRUE, 'draft'),
  ('When do you feel most connected to me?', 'connection', 'medium', 2, 31, TRUE, 'draft'),
  ('What''s something hard you went through that shaped who you are?', 'memories', 'deep', 3, 32, TRUE, 'draft'),
  ('If we had a free Saturday with no plans, how would you want to spend it?', 'fun', 'light', 1, 33, TRUE, 'draft'),
  ('What''s a small promise I kept that meant a lot to you?', 'gratitude', 'medium', 2, 34, TRUE, 'draft'),
  ('What helps you feel safe enough to be vulnerable with me?', 'connection', 'deep', 3, 35, TRUE, 'draft'),
  ('What''s one kind thing someone did for you recently?', 'gratitude', 'light', 1, 36, TRUE, 'draft'),
  ('Which of our routines would you never want to give up?', 'values', 'medium', 2, 37, TRUE, 'draft'),
  ('What''s one thing you''d like more of in your daily routine?', 'growth', 'light', 1, 38, TRUE, 'draft'),
  ('What''s a belief about relationships you''ve changed your mind about?', 'values', 'deep', 3, 39, TRUE, 'draft'),
  ('What''s one way you feel you''ve grown since we met?', 'growth', 'medium', 2, 40, TRUE, 'draft'),
  ('What''s a tradition you love from your childhood?', 'memories', 'light', 1, 41, TRUE, 'draft'),
  ('What''s something stressing you out that I might not know about?', 'communication', 'medium', 2, 42, TRUE, 'draft'),
  ('What''s something you''re looking forward to this week?', 'connection', 'light', 1, 43, TRUE, 'draft'),
  ('What would you want our relationship to feel like in ten years?', 'goals', 'deep', 3, 44, TRUE, 'draft'),
  ('What''s a food you could eat every week and never get tired of?', 'fun', 'light', 1, 45, TRUE, 'draft'),
  ('What''s one thing you''d like us to learn together?', 'goals', 'medium', 2, 46, TRUE, 'draft'),
  ('What''s something you''re still learning to accept about yourself?', 'growth', 'deep', 3, 47, TRUE, 'draft'),
  ('What''s something you appreciated about me this week?', 'gratitude', 'light', 1, 48, TRUE, 'draft'),
  ('What''s something I do that helps you feel calm when you''re stressed?', 'connection', 'medium', 2, 49, TRUE, 'draft'),
  ('What''s something you''ve learned recently that surprised you?', 'growth', 'light', 1, 50, TRUE, 'draft'),
  ('What''s something you admire about how I handle hard things?', 'gratitude', 'medium', 2, 51, TRUE, 'draft'),
  ('What''s a moment in our relationship you''d like to revisit or talk through?', 'communication', 'deep', 3, 52, TRUE, 'draft'),
  ('What''s a smell, sound, or taste that reminds you of us?', 'memories', 'light', 1, 53, TRUE, 'draft'),
  ('What part of our home feels most like "us"?', 'values', 'medium', 2, 54, TRUE, 'draft'),
  ('What''s something that always cheers you up on a bad day?', 'connection', 'light', 1, 55, TRUE, 'draft'),
  ('What does feeling loved look like for you on a hard day?', 'connection', 'deep', 3, 56, TRUE, 'draft'),
  ('What''s one thing you''d like to feel more of this month?', 'growth', 'medium', 2, 57, TRUE, 'draft'),
  ('What''s a place nearby you''ve been wanting to try?', 'fun', 'light', 1, 58, TRUE, 'draft'),
  ('What would you like our relationship to stand for?', 'values', 'deep', 3, 59, TRUE, 'draft'),
  ('What''s a question you wish I asked you more often?', 'communication', 'medium', 2, 60, TRUE, 'draft'),
  ('What''s a kind thing you noticed me do recently?', 'gratitude', 'light', 1, 61, TRUE, 'draft'),
  ('What''s your favorite photo of us, and why?', 'memories', 'light', 1, 62, TRUE, 'draft'),
  ('How would you like us to spend our next anniversary?', 'goals', 'medium', 2, 63, TRUE, 'draft'),
  ('What''s a hope you have for us that you haven''t said out loud?', 'goals', 'deep', 3, 64, TRUE, 'draft'),
  ('What moment today would you want to replay?', 'connection', 'light', 1, 65, TRUE, 'draft'),
  ('How do you most like to be comforted when you''re sad?', 'connection', 'medium', 2, 66, TRUE, 'draft'),
  ('What''s a movie or show you''d happily rewatch with me?', 'fun', 'light', 1, 67, TRUE, 'draft'),
  ('How would you like us to support each other''s individual growth?', 'growth', 'deep', 3, 68, TRUE, 'draft'),
  ('What''s something you''re proud of us for?', 'gratitude', 'medium', 2, 69, TRUE, 'draft'),
  ('What''s your favorite way for me to greet you when we see each other?', 'connection', 'light', 1, 70, TRUE, 'draft'),
  ('What''s something from your family you''d like us to do differently?', 'values', 'medium', 2, 71, TRUE, 'draft'),
  ('Is there a conversation we keep avoiding that you''d like to have gently?', 'communication', 'deep', 3, 72, TRUE, 'draft'),
  ('If you could have any skill instantly, what would it be?', 'fun', 'light', 1, 73, TRUE, 'draft'),
  ('What''s one boundary that helps you feel respected?', 'communication', 'medium', 2, 74, TRUE, 'draft'),
  ('What''s a way I could make tomorrow morning easier for you?', 'connection', 'light', 1, 75, TRUE, 'draft'),
  ('What do you need from me when you''re overwhelmed?', 'connection', 'deep', 3, 76, TRUE, 'draft'),
  ('What would your perfect breakfast together look like?', 'fun', 'light', 1, 77, TRUE, 'draft'),
  ('What''s a goal for our home or life together this year?', 'goals', 'medium', 2, 78, TRUE, 'draft'),
  ('If we took a trip tomorrow, where would you want to go?', 'fun', 'light', 1, 79, TRUE, 'draft'),
  ('What makes you feel most respected by me?', 'values', 'deep', 3, 80, TRUE, 'draft'),
  ('What does a really good week look like for you?', 'connection', 'medium', 2, 81, TRUE, 'draft'),
  ('What small luxury makes your day better?', 'fun', 'light', 1, 82, TRUE, 'draft'),
  ('When have you felt most like a team with me?', 'connection', 'medium', 2, 83, TRUE, 'draft'),
  ('How can I better support your dreams?', 'goals', 'deep', 3, 84, TRUE, 'draft'),
  ('What''s something you did as a kid that you''d love to try again?', 'fun', 'light', 1, 85, TRUE, 'draft'),
  ('What''s a way I show love that you''d like to see more often?', 'connection', 'medium', 2, 86, TRUE, 'draft'),
  ('What''s a new thing you''d like to try this month?', 'fun', 'light', 1, 87, TRUE, 'draft'),
  ('When do you feel most alone in our relationship, and what would help?', 'connection', 'deep', 3, 88, TRUE, 'draft'),
  ('What''s a moment you felt really understood by me?', 'connection', 'medium', 2, 89, TRUE, 'draft'),
  ('If our relationship had a theme song, what would it be?', 'fun', 'light', 1, 90, TRUE, 'draft')
ON CONFLICT (question) DO UPDATE SET category = EXCLUDED.category, depth = EXCLUDED.depth, priority = EXCLUDED.priority, sort_order = EXCLUDED.sort_order, active = TRUE, review_status = EXCLUDED.review_status;
UPDATE daily_questions SET active = FALSE WHERE question NOT IN (
  'What is one thing I did today that made you feel loved?',
  'What is one thing I could do better at tomorrow?',
  'What is something you want to talk about but have not brought up?',
  'What made you laugh or smile today?',
  'If you could change one thing about how we communicate, what would it be?',
  'What is one thing you are grateful for about us?',
  'When did you first feel you could really trust me?',
  'What is a dream or goal you have that you want us to support?',
  'What''s one thing that made you feel proud of yourself recently?',
  'What does our relationship need more of right now?',
  'What''s a part of yourself you''d like me to understand better?',
  'Which season feels most like "us," and why?',
  'What''s a memory of us that you return to often?',
  'What''s one thing on your mind that you haven''t mentioned yet today?',
  'What did love look like in the home you grew up in?',
  'What was the best part of your day?',
  'What''s something you''d like us to celebrate more often?',
  'What song has been stuck in your head lately?',
  'What''s a dream you''ve let go of, and how do you feel about it now?',
  'What''s a value you hope our relationship always reflects?',
  'What''s a small habit of mine that you secretly love?',
  'What''s one way I''ve grown since we met?',
  'What''s one way our relationship has changed you?',
  'What''s a compliment you received recently that stuck with you?',
  'What''s something about your day that you''d like me to ask about more?',
  'What was your favorite part of our last weekend?',
  'What''s a fear you have about the future that you''d like to share?',
  'What''s something you''ve been wanting to try together?',
  'What''s one thing that made today harder than you expected?',
  'What''s something small you''d love for us to do together this week?',
  'When do you feel most connected to me?',
  'What''s something hard you went through that shaped who you are?',
  'If we had a free Saturday with no plans, how would you want to spend it?',
  'What''s a small promise I kept that meant a lot to you?',
  'What helps you feel safe enough to be vulnerable with me?',
  'What''s one kind thing someone did for you recently?',
  'Which of our routines would you never want to give up?',
  'What''s one thing you''d like more of in your daily routine?',
  'What''s a belief about relationships you''ve changed your mind about?',
  'What''s one way you feel you''ve grown since we met?',
  'What''s a tradition you love from your childhood?',
  'What''s something stressing you out that I might not know about?',
  'What''s something you''re looking forward to this week?',
  'What would you want our relationship to feel like in ten years?',
  'What''s a food you could eat every week and never get tired of?',
  'What''s one thing you''d like us to learn together?',
  'What''s something you''re still learning to accept about yourself?',
  'What''s something you appreciated about me this week?',
  'What''s something I do that helps you feel calm when you''re stressed?',
  'What''s something you''ve learned recently that surprised you?',
  'What''s something you admire about how I handle hard things?',
  'What''s a moment in our relationship you''d like to revisit or talk through?',
  'What''s a smell, sound, or taste that reminds you of us?',
  'What part of our home feels most like "us"?',
  'What''s something that always cheers you up on a bad day?',
  'What does feeling loved look like for you on a hard day?',
  'What''s one thing you''d like to feel more of this month?',
  'What''s a place nearby you''ve been wanting to try?',
  'What would you like our relationship to stand for?',
  'What''s a question you wish I asked you more often?',
  'What''s a kind thing you noticed me do recently?',
  'What''s your favorite photo of us, and why?',
  'How would you like us to spend our next anniversary?',
  'What''s a hope you have for us that you haven''t said out loud?',
  'What moment today would you want to replay?',
  'How do you most like to be comforted when you''re sad?',
  'What''s a movie or show you''d happily rewatch with me?',
  'How would you like us to support each other''s individual growth?',
  'What''s something you''re proud of us for?',
  'What''s your favorite way for me to greet you when we see each other?',
  'What''s something from your family you''d like us to do differently?',
  'Is there a conversation we keep avoiding that you''d like to have gently?',
  'If you could have any skill instantly, what would it be?',
  'What''s one boundary that helps you feel respected?',
  'What''s a way I could make tomorrow morning easier for you?',
  'What do you need from me when you''re overwhelmed?',
  'What would your perfect breakfast together look like?',
  'What''s a goal for our home or life together this year?',
  'If we took a trip tomorrow, where would you want to go?',
  'What makes you feel most respected by me?',
  'What does a really good week look like for you?',
  'What small luxury makes your day better?',
  'When have you felt most like a team with me?',
  'How can I better support your dreams?',
  'What''s something you did as a kid that you''d love to try again?',
  'What''s a way I show love that you''d like to see more often?',
  'What''s a new thing you''d like to try this month?',
  'When do you feel most alone in our relationship, and what would help?',
  'What''s a moment you felt really understood by me?',
  'If our relationship had a theme song, what would it be?'
);

-- ============ CHECK-IN TOPICS (20)
UPDATE check_in_topics SET topic_key = 'communication' WHERE topic_key IS NULL AND topic_name = 'Communication Check-in';
UPDATE check_in_topics SET topic_key = 'quality-time' WHERE topic_key IS NULL AND topic_name = 'Quality Time';
UPDATE check_in_topics SET topic_key = 'money' WHERE topic_key IS NULL AND topic_name = 'Financial Alignment';
UPDATE check_in_topics SET topic_key = 'intimacy' WHERE topic_key IS NULL AND topic_name = 'Intimacy and Affection';
UPDATE check_in_topics SET topic_key = 'conflict' WHERE topic_key IS NULL AND topic_name = 'Conflict Resolution';
UPDATE check_in_topics SET topic_key = 'future-goals' WHERE topic_key IS NULL AND topic_name = 'Future Goals';
INSERT INTO check_in_topics (topic_key, topic_name, description, category, depth_level, framework, prompt_questions, sort_order, review_status) VALUES
  ('communication', 'Communication Check-in', 'How well are you and your partner communicating lately?', 'communication', 1, 'Gottman Method', ARRAY['How has our communication been this week?', 'Is there anything unsaid that you would like to share?', 'What could we do to feel more heard by each other?']::text[], 10, 'draft'),
  ('quality-time', 'Quality Time', 'Are you spending enough meaningful time together?', 'fun', 1, 'Rituals of connection', ARRAY['How much quality time have we spent together recently?', 'What activities bring us the most joy?', 'Do we need to schedule more time together?']::text[], 20, 'draft'),
  ('money', 'Financial Alignment', 'Are you and your partner on the same page about money?', 'finances', 2, 'Financial relationship research', ARRAY['Do we have any financial stresses to talk about?', 'Are we aligned on our spending priorities?', 'What financial goal would we like to work toward together?']::text[], 30, 'draft'),
  ('intimacy', 'Intimacy and Affection', 'How is your physical and emotional closeness?', 'intimacy', 2, 'Intimacy process research', ARRAY['How connected have you felt to me lately?', 'Is there anything you''d like more or less of?', 'What''s one way we could nurture our closeness this week?']::text[], 40, 'draft'),
  ('conflict', 'Conflict Resolution', 'How are disagreements being handled in your relationship?', 'conflict', 2, 'Gottman Method', ARRAY['Have we had any disagreements that still feel unresolved?', 'How have we handled disagreements recently?', 'What would help us argue more kindly?']::text[], 50, 'draft'),
  ('future-goals', 'Future Goals', 'Are you both working toward common goals?', 'goals', 2, 'Gottman Method (shared meaning)', ARRAY['What goals are we working toward together?', 'Are our individual goals supporting each other?', 'What support do you need from me?']::text[], 60, 'draft'),
  ('stress-support', 'Stress and Support', 'How is stress from outside the relationship affecting you both?', 'wellbeing', 1, 'Dyadic coping research', ARRAY['What''s been the biggest source of stress for you lately?', 'What kind of support helps you most right now: listening, practical help, or space?', 'Is there anything I could take off your plate this week?']::text[], 70, 'draft'),
  ('appreciation', 'Appreciation', 'Are you noticing and naming what you value in each other?', 'appreciation', 1, 'Gottman Method (fondness and admiration)', ARRAY['What''s something I did recently that you appreciated?', 'Do you feel noticed for the things you do?', 'How could we make appreciation part of our routine?']::text[], 80, 'draft'),
  ('household-load', 'Household Load', 'Does the work of running your life feel fairly shared?', 'home', 2, 'Household labor research', ARRAY['Which tasks feel heaviest for you right now?', 'Is there any invisible work — planning, remembering — you''d like me to notice?', 'What''s one area we could rebalance?']::text[], 90, 'draft'),
  ('family', 'Family and In-Laws', 'How are you handling relationships with extended family?', 'family', 2, 'Family systems practice', ARRAY['Are there any family situations coming up that we should plan for?', 'Do you feel supported by me around my family, and I by you around yours?', 'Is there a boundary we''d like to set together?']::text[], 100, 'draft'),
  ('trust', 'Trust and Reliability', 'Do you feel you can count on each other?', 'trust', 2, 'Gottman Method (trust)', ARRAY['Is there a promise, big or small, that''s been slipping?', 'When have you felt most able to rely on me recently?', 'What would help you feel more secure in us?']::text[], 110, 'draft'),
  ('emotional-safety', 'Emotional Safety', 'Does it feel safe to share softer feelings with each other?', 'connection', 3, 'Emotionally Focused Therapy', ARRAY['Is there a feeling you''ve been holding back from sharing?', 'How do you know when I''m really listening?', 'What helps you feel safe to be vulnerable with me?']::text[], 120, 'draft'),
  ('fun', 'Fun and Play', 'Is there enough lightness and laughter in your relationship?', 'fun', 1, 'Self-expansion research', ARRAY['When did we last really laugh together?', 'Is there something new you''d like us to try?', 'What could we do just for fun this month?']::text[], 130, 'draft'),
  ('health', 'Health and Energy', 'How are your energy, sleep, and well-being affecting the relationship?', 'wellbeing', 1, 'Health and relationships research', ARRAY['How has your energy and sleep been lately?', 'Is there a health goal you''d like support with?', 'How can we look after each other''s well-being this week?']::text[], 140, 'draft'),
  ('parenting', 'Parenting Teamwork', 'If you''re parents, are you working together as a team?', 'family', 2, 'Gottman Method (Bringing Baby Home)', ARRAY['Where do we work well together as parents?', 'Is there a parenting decision we need to align on?', 'How can we protect time for just the two of us?']::text[], 150, 'draft'),
  ('screens', 'Screens and Attention', 'Are phones and screens getting in the way of connection?', 'connection', 1, 'Technoference research', ARRAY['Are there times you wish I were less on my phone?', 'Are there times I''d like the same from you?', 'Is there a screen-free time we''d like to protect?']::text[], 160, 'draft'),
  ('personal-growth', 'Personal Growth', 'Are you supporting each other''s individual goals?', 'growth', 2, 'Self-expansion research', ARRAY['What''s something you''re working on for yourself?', 'How can I support it?', 'Is there anything that makes it hard to grow right now?']::text[], 170, 'draft'),
  ('rituals', 'Rituals and Traditions', 'Are your rituals and traditions still meaningful?', 'values', 1, 'Gottman Method (shared meaning)', ARRAY['Which of our rituals do you love most?', 'Is there a ritual that''s slipped away that you miss?', 'Is there a new tradition you''d like to start?']::text[], 180, 'draft'),
  ('repair', 'Repair Check', 'Have recent hurts or disagreements been repaired?', 'conflict', 3, 'Gottman Method (repair)', ARRAY['Is there a recent moment that still stings?', 'Is there something you''d like to apologize for, or hear an apology for?', 'What would help us feel fully back on track?']::text[], 190, 'draft'),
  ('needs', 'Needs and Requests', 'Are you each able to ask for what you need?', 'communication', 2, 'Nonviolent Communication', ARRAY['Is there a need of yours that isn''t being met right now?', 'How could you phrase it as a request?', 'Is there anything that makes asking hard?']::text[], 200, 'draft')
ON CONFLICT (topic_key) DO UPDATE SET topic_name = EXCLUDED.topic_name, description = EXCLUDED.description, category = EXCLUDED.category, depth_level = EXCLUDED.depth_level, framework = EXCLUDED.framework, prompt_questions = EXCLUDED.prompt_questions, sort_order = EXCLUDED.sort_order, review_status = EXCLUDED.review_status;

-- ============ MONTHLY DEEP-DIVE THEMES (8)
INSERT INTO deep_dive_themes (theme_key, title, summary, framework, focus_questions, weekly_activities, sort_order, review_status) VALUES
  ('communication', 'Communication', 'A month of listening better and speaking more gently.', 'Gottman Method; Nonviolent Communication', '["When do you feel most heard by me?", "What topics feel hardest for us to talk about?", "How do you like to be approached with a concern?", "What''s one communication habit we''d like to build?"]'::jsonb, '[{"week": 1, "title": "Notice your patterns", "description": "Each week, notice one moment of great communication and one moment that went sideways."}, {"week": 2, "title": "Gentle start-ups", "description": "Practice raising one small concern with \"I feel… about… I need…\"."}, {"week": 3, "title": "Listening deeply", "description": "Try the Speaker–Listener practice on a low-stakes topic."}, {"week": 4, "title": "State of the union", "description": "Hold a weekly meeting: appreciations, what went well, and one issue."}]'::jsonb, 10, 'draft'),
  ('appreciation', 'Appreciation and Fondness', 'A month of noticing and naming what you value in each other.', 'Gottman Method (fondness and admiration)', '["What first drew you to me?", "What quality of mine do you admire most?", "When do you feel most appreciated?", "How can we make appreciation a daily habit?"]'::jsonb, '[{"week": 1, "title": "Fondness list", "description": "Each write three qualities you admire in the other, with examples."}, {"week": 2, "title": "Appreciation jar", "description": "Add a note of appreciation every day."}, {"week": 3, "title": "Gratitude letter", "description": "Write and share a letter about a time your partner made a difference."}, {"week": 4, "title": "Celebrate each other", "description": "Plan a small celebration of something your partner did this month."}]'::jsonb, 20, 'draft'),
  ('conflict-repair', 'Conflict and Repair', 'A month of handling disagreements with more calm and quicker repair.', 'Gottman Method', '["How do you usually feel during our disagreements?", "What helps you calm down when you''re upset?", "What''s a recurring topic we could understand better?", "How do you like to repair after an argument?"]'::jsonb, '[{"week": 1, "title": "Time-out plan", "description": "Agree on a signal and plan for taking breaks when flooded."}, {"week": 2, "title": "Repair phrase menu", "description": "Choose phrases you''d welcome in tense moments."}, {"week": 3, "title": "Dreams within conflict", "description": "Explore the deeper hopes behind one recurring disagreement."}, {"week": 4, "title": "Process a past argument", "description": "Look back calmly at a past disagreement to understand each other."}]'::jsonb, 30, 'draft'),
  ('intimacy', 'Intimacy and Closeness', 'A month of building emotional and physical closeness.', 'Intimacy process research', '["What makes you feel closest to me?", "Which kind of closeness do you feel is missing?", "What helps you feel relaxed and open with me?", "How can we protect time for intimacy?"]'::jsonb, '[{"week": 1, "title": "Kinds of closeness", "description": "Rank emotional, physical, intellectual, and shared-experience closeness."}, {"week": 2, "title": "Affection menu", "description": "Share everyday affection you each enjoy, and use it."}, {"week": 3, "title": "An appreciative conversation", "description": "Share what you appreciate about your physical connection."}, {"week": 4, "title": "Protected evening", "description": "Plan an evening with no screens and no chores."}]'::jsonb, 40, 'draft'),
  ('trust', 'Trust and Reliability', 'A month of strengthening the everyday trust between you.', 'Gottman Method (trust); attachment research', '["When have you felt you could really count on me?", "Which areas of trust feel strongest?", "Is there a small promise that''s been slipping?", "What helps you feel secure in us?"]'::jsonb, '[{"week": 1, "title": "Trust inventory", "description": "Rate how solid different areas of trust feel, and talk about it."}, {"week": 2, "title": "Promise check", "description": "Review the small promises you''ve made and keep them."}, {"week": 3, "title": "Turning toward", "description": "Notice and respond to each other''s bids for attention."}, {"week": 4, "title": "A softer feeling", "description": "Share a feeling that sits beneath a recent frustration."}]'::jsonb, 50, 'draft'),
  ('shared-dreams', 'Shared Dreams and Meaning', 'A month of exploring what you''re building together.', 'Gottman Method (shared meaning)', '["What are your biggest dreams for our life together?", "What values do we want our relationship to reflect?", "Which rituals make us feel like \"us\"?", "What would you like our life to look like in five years?"]'::jsonb, '[{"week": 1, "title": "Values sort", "description": "Each choose your top five values and compare them."}, {"week": 2, "title": "Our rituals", "description": "Talk about how you want to mark mornings, weekends, and holidays."}, {"week": 3, "title": "Five-year vision", "description": "Each describe an ordinary day five years from now."}, {"week": 4, "title": "Plan the year", "description": "Choose two or three shared intentions for the year ahead."}]'::jsonb, 60, 'draft'),
  ('money', 'Money and Values', 'A month of understanding each other''s money story and working as a team.', 'Financial relationship research', '["What did money mean in your family growing up?", "What does financial security look like to you?", "Where do our spending priorities differ?", "What''s a financial goal we share?"]'::jsonb, '[{"week": 1, "title": "Money stories", "description": "Share what money was like in each of your families."}, {"week": 2, "title": "Spending priorities", "description": "Each list your top three spending priorities and compare."}, {"week": 3, "title": "Money date", "description": "Hold a calm monthly review of spending and goals."}, {"week": 4, "title": "A shared goal", "description": "Choose one financial goal and a first step."}]'::jsonb, 70, 'draft'),
  ('stress-support', 'Stress and Support', 'A month of facing outside stress as a team.', 'Dyadic coping research', '["What''s the biggest stress in your life right now?", "How does stress show up in how we treat each other?", "What kind of support helps you most?", "How can we protect our relationship during busy seasons?"]'::jsonb, '[{"week": 1, "title": "Stress map", "description": "Each name your current stresses and how they affect you."}, {"week": 2, "title": "Stress-reducing conversations", "description": "Hold short daily check-ins about stress outside the relationship."}, {"week": 3, "title": "Support menu", "description": "Each list the kinds of support you find most helpful."}, {"week": 4, "title": "Recharge together", "description": "Plan one restful activity together."}]'::jsonb, 80, 'draft')
ON CONFLICT (theme_key) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, framework = EXCLUDED.framework, focus_questions = EXCLUDED.focus_questions, weekly_activities = EXCLUDED.weekly_activities, sort_order = EXCLUDED.sort_order, review_status = EXCLUDED.review_status;

COMMIT;
