-- 015: content approval.
--
-- The drafted content from migrations 012 and 013 was reviewed and approved on 2026-09-23
-- (review doc: "Bond Content Review (Draft)"). Approves exactly those rows, by key, so content
-- added later (017 onward) stays 'draft' until it has its own review, whatever order this runs in.
--
-- Run after 012 and 013. Safe to re-run.

UPDATE learning_series SET review_status = 'approved' WHERE series_key IN (
  'relationship-foundations',
  'connection-series',
  'communication-series',
  'conflict-repair-series',
  'trust-vulnerability-series',
  'intimacy-series',
  'life-growth-series',
  'health-wellness-series',
  'key-concepts-series',
  'repair-and-communication'
);
UPDATE learning_series_modules SET review_status = 'approved' WHERE (series_key, module_key) IN (
  ('relationship-foundations', 'rf-1'),
  ('relationship-foundations', 'rf-2'),
  ('relationship-foundations', 'rf-3'),
  ('relationship-foundations', 'rf-4'),
  ('relationship-foundations', 'rf-5'),
  ('relationship-foundations', 'rf-6'),
  ('relationship-foundations', 'rf-7'),
  ('relationship-foundations', 'rf-8'),
  ('connection-series', 'daily-moments'),
  ('connection-series', 'love-maps'),
  ('connection-series', 'rituals'),
  ('connection-series', 'good-news'),
  ('connection-series', 'novelty-play'),
  ('connection-series', 'reconnecting'),
  ('communication-series', 'soft-startup'),
  ('communication-series', 'listening'),
  ('communication-series', 'validation'),
  ('communication-series', 'needs-requests'),
  ('communication-series', 'meta-emotions'),
  ('communication-series', 'hard-topics'),
  ('conflict-repair-series', 'perpetual-problems'),
  ('conflict-repair-series', 'flooding'),
  ('conflict-repair-series', 'repair-attempts'),
  ('conflict-repair-series', 'four-horsemen'),
  ('conflict-repair-series', 'accepting-influence'),
  ('conflict-repair-series', 'forgiveness'),
  ('trust-vulnerability-series', 'how-trust-is-built'),
  ('trust-vulnerability-series', 'vulnerability'),
  ('trust-vulnerability-series', 'reliability'),
  ('trust-vulnerability-series', 'rebuilding-trust'),
  ('trust-vulnerability-series', 'attachment-injuries'),
  ('intimacy-series', 'kinds-of-closeness'),
  ('intimacy-series', 'talking-about-sex'),
  ('intimacy-series', 'desire-differences'),
  ('intimacy-series', 'body-image'),
  ('intimacy-series', 'keeping-intimacy-alive'),
  ('life-growth-series', 'expectations-roles'),
  ('life-growth-series', 'in-laws'),
  ('life-growth-series', 'becoming-parents'),
  ('life-growth-series', 'family-culture'),
  ('life-growth-series', 'technology'),
  ('life-growth-series', 'long-distance'),
  ('life-growth-series', 'growing-together'),
  ('health-wellness-series', 'dyadic-coping'),
  ('health-wellness-series', 'anxiety'),
  ('health-wellness-series', 'low-mood'),
  ('health-wellness-series', 'illness-caregiving'),
  ('health-wellness-series', 'transitions'),
  ('health-wellness-series', 'money'),
  ('health-wellness-series', 'acceptance'),
  ('key-concepts-series', 'sentiment-override'),
  ('key-concepts-series', 'five-to-one'),
  ('key-concepts-series', 'we-ness'),
  ('key-concepts-series', 'attunement'),
  ('key-concepts-series', 'interdependence'),
  ('key-concepts-series', 'sacrifice'),
  ('key-concepts-series', 'emotional-intelligence'),
  ('key-concepts-series', 'how-couples-change'),
  ('repair-and-communication', 'rc-1'),
  ('repair-and-communication', 'rc-2'),
  ('repair-and-communication', 'rc-3'),
  ('repair-and-communication', 'rc-4')
);
UPDATE activities SET review_status = 'approved' WHERE activity_key IN (
  'ideal-day',
  'memory-lane-walk',
  'six-second-kiss',
  'stress-reducing-conversation',
  'love-map-questions',
  'reunion-ritual',
  'closeness-questions',
  'tech-free-evening',
  'three-worst-things',
  'speaker-listener',
  'soft-startup-rewrite',
  'needs-and-requests',
  'state-of-the-union',
  'validation-practice',
  'repair-phrase-menu',
  'time-out-plan',
  'processing-a-past-argument',
  'dreams-within-conflict',
  'compromise-circles',
  'yes-and-week',
  'appreciation-jar',
  'gratitude-letter',
  'fondness-list',
  'three-good-things',
  'celebrate-good-news',
  'shared-values-sort',
  'rituals-of-connection',
  'money-stories',
  'five-year-vision',
  'load-audit',
  'closeness-ranking',
  'affection-menu',
  'novelty-date',
  'playlist-of-us',
  'would-you-rather',
  'cook-together',
  'play-date',
  'relationship-timeline',
  'how-we-met',
  'hard-times-we-survived',
  'anniversary-letter',
  'year-ahead'
);
UPDATE daily_questions SET review_status = 'approved' WHERE question IN (
  'What is one thing I did today that made you feel loved?',
  'What is one thing I could do better at tomorrow?',
  'What is something you want to talk about but have not brought up?',
  'What made you laugh or smile today?',
  'If you could change one thing about how we communicate, what would it be?',
  'What is one thing you are grateful for about us?',
  'When did you first feel you could really trust me?',
  'What is a dream or goal you have that you want us to support?',
  'What''s one thing that made you feel proud of yourself recently?',
  'What does our relationship need more of right now?',
  'What''s a part of yourself you''d like me to understand better?',
  'Which season feels most like "us," and why?',
  'What''s a memory of us that you return to often?',
  'What''s one thing on your mind that you haven''t mentioned yet today?',
  'What did love look like in the home you grew up in?',
  'What was the best part of your day?',
  'What''s something you''d like us to celebrate more often?',
  'What song has been stuck in your head lately?',
  'What''s a dream you''ve let go of, and how do you feel about it now?',
  'What''s a value you hope our relationship always reflects?',
  'What''s a small habit of mine that you secretly love?',
  'What''s one way I''ve grown since we met?',
  'What''s one way our relationship has changed you?',
  'What''s a compliment you received recently that stuck with you?',
  'What''s something about your day that you''d like me to ask about more?',
  'What was your favorite part of our last weekend?',
  'What''s a fear you have about the future that you''d like to share?',
  'What''s something you''ve been wanting to try together?',
  'What''s one thing that made today harder than you expected?',
  'What''s something small you''d love for us to do together this week?',
  'When do you feel most connected to me?',
  'What''s something hard you went through that shaped who you are?',
  'If we had a free Saturday with no plans, how would you want to spend it?',
  'What''s a small promise I kept that meant a lot to you?',
  'What helps you feel safe enough to be vulnerable with me?',
  'What''s one kind thing someone did for you recently?',
  'Which of our routines would you never want to give up?',
  'What''s one thing you''d like more of in your daily routine?',
  'What''s a belief about relationships you''ve changed your mind about?',
  'What''s one way you feel you''ve grown since we met?',
  'What''s a tradition you love from your childhood?',
  'What''s something stressing you out that I might not know about?',
  'What''s something you''re looking forward to this week?',
  'What would you want our relationship to feel like in ten years?',
  'What''s a food you could eat every week and never get tired of?',
  'What''s one thing you''d like us to learn together?',
  'What''s something you''re still learning to accept about yourself?',
  'What''s something you appreciated about me this week?',
  'What''s something I do that helps you feel calm when you''re stressed?',
  'What''s something you''ve learned recently that surprised you?',
  'What''s something you admire about how I handle hard things?',
  'What''s a moment in our relationship you''d like to revisit or talk through?',
  'What''s a smell, sound, or taste that reminds you of us?',
  'What part of our home feels most like "us"?',
  'What''s something that always cheers you up on a bad day?',
  'What does feeling loved look like for you on a hard day?',
  'What''s one thing you''d like to feel more of this month?',
  'What''s a place nearby you''ve been wanting to try?',
  'What would you like our relationship to stand for?',
  'What''s a question you wish I asked you more often?',
  'What''s a kind thing you noticed me do recently?',
  'What''s your favorite photo of us, and why?',
  'How would you like us to spend our next anniversary?',
  'What''s a hope you have for us that you haven''t said out loud?',
  'What moment today would you want to replay?',
  'How do you most like to be comforted when you''re sad?',
  'What''s a movie or show you''d happily rewatch with me?',
  'How would you like us to support each other''s individual growth?',
  'What''s something you''re proud of us for?',
  'What''s your favorite way for me to greet you when we see each other?',
  'What''s something from your family you''d like us to do differently?',
  'Is there a conversation we keep avoiding that you''d like to have gently?',
  'If you could have any skill instantly, what would it be?',
  'What''s one boundary that helps you feel respected?',
  'What''s a way I could make tomorrow morning easier for you?',
  'What do you need from me when you''re overwhelmed?',
  'What would your perfect breakfast together look like?',
  'What''s a goal for our home or life together this year?',
  'If we took a trip tomorrow, where would you want to go?',
  'What makes you feel most respected by me?',
  'What does a really good week look like for you?',
  'What small luxury makes your day better?',
  'When have you felt most like a team with me?',
  'How can I better support your dreams?',
  'What''s something you did as a kid that you''d love to try again?',
  'What''s a way I show love that you''d like to see more often?',
  'What''s a new thing you''d like to try this month?',
  'When do you feel most alone in our relationship, and what would help?',
  'What''s a moment you felt really understood by me?',
  'If our relationship had a theme song, what would it be?'
);
UPDATE check_in_topics SET review_status = 'approved' WHERE topic_key IN (
  'communication',
  'quality-time',
  'money',
  'intimacy',
  'conflict',
  'future-goals',
  'stress-support',
  'appreciation',
  'household-load',
  'family',
  'trust',
  'emotional-safety',
  'fun',
  'health',
  'parenting',
  'screens',
  'personal-growth',
  'rituals',
  'repair',
  'needs'
);
UPDATE deep_dive_themes SET review_status = 'approved' WHERE theme_key IN (
  'communication',
  'appreciation',
  'conflict-repair',
  'intimacy',
  'trust',
  'shared-dreams',
  'money',
  'stress-support'
);
