-- 017: round-two content — two new learning series, four more lessons, and more activities,
-- daily questions, check-in topics, and monthly deep-dive themes.
--
-- DRAFT: requires review before launch. Every row is inserted with review_status = 'draft'.
-- Run AFTER 015 (015 approves only the 012/013 content, so these stay draft until reviewed).
-- Note: 012 removes modules it doesn't list from its series; re-running 012 after this would
-- remove the four lessons added here to Trust & Vulnerability and Intimacy — re-run 017 after it.
--
-- Adds: 2 series, 13 lessons, 18 activities, 60 daily questions
-- (rotation slots 91-150), 10 check-in topics, 4 deep-dive themes.
-- Requires 011. Safe to re-run.

BEGIN;

-- ============ LEARNING SERIES
INSERT INTO learning_series (series_key, title, summary, description, icon, sort_order, review_status) VALUES ('getting-started-series', 'Getting Started Together', 'A short first week for new couples: how Bond works, starting from strengths, and building a rhythm.', 'Four short lessons for your first week in Bond. They explain how to use what you learn here as a team, how to talk about results without keeping score, and how to build a small weekly rhythm that lasts.', '🌅', 0, 'draft')
ON CONFLICT (series_key) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, description = EXCLUDED.description, icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order, review_status = EXCLUDED.review_status;
INSERT INTO learning_series (series_key, title, summary, description, icon, sort_order, review_status) VALUES ('hard-seasons-series', 'Hard Seasons', 'Staying close through grief, loss, job loss, caregiving, and the aftermath of a big fight.', 'Every couple goes through seasons that test them. These lessons look at how partners can support each other through grief, fertility and pregnancy loss, job loss, caring for aging parents, and the days after a serious argument — and when to reach for outside support.', '🕯️', 11, 'draft')
ON CONFLICT (series_key) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, description = EXCLUDED.description, icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order, review_status = EXCLUDED.review_status;

-- ============ LESSONS (13)
INSERT INTO learning_series_modules (series_key, module_key, title, summary, description, duration, sort_order, frameworks, content, key_takeaways, exercises, reflection, review_status) VALUES
  ('getting-started-series', 'how-bond-works', 'How Bond Works for the Two of You', 'What relationship education can and can''t do, and how to get the most from it together.', 'What relationship education can and can''t do, and how to get the most from it together.', '5 min', 1, ARRAY['Couple and relationship education research']::text[], '{"introduction": "Bond is a place to learn about your relationship together: assessments that show your patterns, lessons that explain the research behind them, and small practices that turn insight into habit. It works best when you treat it as something you do as a team, not a test either of you can pass or fail.", "sections": [{"title": "Small, steady practice beats big breakthroughs", "body": "Relationship skills grow the same way other skills do: a little practice, repeated. Couples who do small things consistently — a daily check-in, one conversation a week, a lesson now and then — tend to get more from programs like this than couples who try to change everything at once.", "research": {"text": "A meta-analysis of couple and relationship education programs found modest but reliable improvements in relationship quality and communication skills.", "source": "Hawkins, Blanchard, Baldwin & Fawcett, Journal of Consulting and Clinical Psychology", "year": 2008}}, {"title": "What Bond is — and isn''t", "body": "Bond describes patterns and suggests practices. It doesn''t diagnose, decide who''s right, or replace a therapist. If you''re facing something heavy — ongoing conflict that feels unsafe, a serious breach of trust, or mental health struggles — a licensed professional is the right next step, and Bond can sit alongside that support.", "tip": {"title": "Getting the most from your first week", "steps": ["Each take the onboarding assessment.", "Answer the daily question together for seven days.", "Pick one lesson to read, then talk about it for ten minutes."]}}], "conclusion": "Think of Bond as a shared practice space. The two of you set the pace; small, regular steps do the rest."}'::jsonb, '["Bond works best as a shared practice, not a test", "Small, regular steps beat big one-off efforts", "Bond describes patterns; it doesn''t diagnose or pick sides", "For heavy issues, a professional is the right next step"]'::jsonb, '[{"title": "Our first-week plan", "description": "Agree on how you''ll use Bond this week.", "duration": "10 min", "instructions": ["Each say what you hope to get from Bond.", "Choose a time of day for the daily question.", "Pick one assessment you''d both like to take first."]}]'::jsonb, '{"question": "What would make Bond feel worthwhile to you a month from now?", "followUp": "What''s one small habit that would get you there?"}'::jsonb, 'draft'),
  ('getting-started-series', 'starting-from-strengths', 'Starting From Strengths', 'Why noticing what already works gives every other change a stronger footing.', 'Why noticing what already works gives every other change a stronger footing.', '6 min', 2, ARRAY['Gratitude research', 'Gottman Method (fondness and admiration)']::text[], '{"introduction": "It''s tempting to open a relationship app by looking for problems. But couples make changes more easily when they start by noticing what already works. Appreciation isn''t just pleasant — it makes partners more responsive to each other and more willing to work on the harder parts.", "sections": [{"title": "Gratitude binds", "body": "Feeling and expressing gratitude helps people notice a partner''s good qualities, reminds them why the relationship matters, and draws them closer. Small, specific thanks — for something your partner did today — carry more weight than general praise.", "research": {"text": "The find-remind-bind theory proposes that gratitude helps people find good partners, reminds them of the value of existing relationships, and binds them closer together.", "source": "Algoe, Social and Personality Psychology Compass", "year": 2012}}, {"title": "Making strengths visible", "body": "When you look at your results in Bond, start with the strengths before the growth areas. Say them out loud to each other. Growth areas are easier to talk about when you both feel seen for what you already do well.", "tip": {"title": "A strengths-first habit", "steps": ["Before discussing any result, each name one strength it shows.", "Thank your partner for one specific thing each day this week.", "Notice how the tone of harder conversations changes."]}}], "conclusion": "Strengths aren''t a warm-up to the real work — they are part of it. Start there, and the rest gets easier."}'::jsonb, '["Couples change more easily starting from strengths", "Specific gratitude draws partners closer", "Name strengths before growth areas", "Appreciation makes hard conversations easier"]'::jsonb, '[{"title": "Three things that work", "description": "Name what already works in your relationship.", "duration": "10 min", "instructions": ["Each write three things that work well between you.", "Share your lists and notice any overlap.", "Choose one to protect deliberately this month."]}]'::jsonb, '{"question": "What''s something your partner does that you''ve never properly thanked them for?", "followUp": "When could you tell them this week?"}'::jsonb, 'draft'),
  ('getting-started-series', 'talking-about-results', 'Talking About Your Results', 'How to discuss assessment results with curiosity instead of scorekeeping.', 'How to discuss assessment results with curiosity instead of scorekeeping.', '6 min', 3, ARRAY['Implicit theories of relationships', 'Gottman Method (gentle start-up)']::text[], '{"introduction": "Seeing your results side by side can stir up feelings: pride, surprise, worry, or a sense of being judged. How you talk about them matters more than the numbers. Results are a snapshot of how each of you answered on one day — a starting point for a conversation, not a verdict.", "sections": [{"title": "Growth beliefs help", "body": "People who see relationships as something that grows with effort tend to handle differences and difficulties better than people who believe a relationship is simply meant to be or not. A low score in an area is information about where to practice, not proof that something is wrong with you as a couple.", "research": {"text": "Research on implicit theories of relationships found that people with stronger growth beliefs were more likely to work through relationship problems rather than withdraw from them.", "source": "Knee, Journal of Personality and Social Psychology", "year": 1998}}, {"title": "A good results conversation", "body": "Start with curiosity: \"What surprised you?\" Talk about your own results before your partner''s. When you notice a difference, ask what it''s like for your partner rather than explaining why your view is right. And never use a result as evidence in an argument — that turns a tool for understanding into a weapon.", "example": {"scenario": "Your scores differ a lot on Quality Time.", "dialogue": "\"It looks like time together matters more to me than the results show for you. What does quality time look like for you?\"", "analysis": "This names the difference without blame and invites your partner''s perspective."}}], "conclusion": "Results start conversations; they don''t settle them. Curiosity, not scorekeeping, is what turns them into closeness."}'::jsonb, '["Results are a snapshot, not a verdict", "Growth beliefs help couples work through differences", "Talk about your own results first", "Never use a result as evidence in an argument"]'::jsonb, '[{"title": "A curious results conversation", "description": "Talk through one result together.", "duration": "15 min", "instructions": ["Choose one assessment you''ve both completed.", "Each share what surprised you about your own result.", "Ask one curious question about your partner''s result."]}]'::jsonb, '{"question": "Which of your results would you most like your partner to understand?", "followUp": "What would help you share it without feeling judged?"}'::jsonb, 'draft'),
  ('getting-started-series', 'weekly-rhythm', 'Building a Weekly Rhythm', 'Small, repeatable rituals that keep your relationship a priority in busy weeks.', 'Small, repeatable rituals that keep your relationship a priority in busy weeks.', '5 min', 4, ARRAY['Family rituals research', 'Habit formation research']::text[], '{"introduction": "Most couples don''t drift apart because of one big problem. They drift because days fill up and connection keeps getting postponed. A simple weekly rhythm — a few small, predictable moments — protects your relationship from getting squeezed out.", "sections": [{"title": "Intentional rituals", "body": "Rituals are repeated moments with meaning: a Sunday walk, a Friday check-in, a goodnight routine. Because they''re predictable, they don''t depend on remembering or having spare energy. Families and couples who are intentional about rituals tend to feel more connected.", "research": {"text": "Doherty''s work on intentional families argues that deliberate, repeated rituals of connection help families and couples resist the drift of busy modern life.", "source": "Doherty, The Intentional Family", "year": 1997}}, {"title": "A simple starting rhythm", "body": "You don''t need much. One daily touchpoint (the daily question), one weekly conversation (a check-in topic or the weekly State of the Union), and one monthly focus (a deep dive or a date) is enough to keep things moving.", "tip": {"title": "Set your rhythm", "steps": ["Daily: answer the Bond question, ideally at the same time.", "Weekly: one 20-minute check-in on a set day.", "Monthly: one shared focus or date you plan together."]}}], "conclusion": "A rhythm makes connection the default instead of the exception. Start small; you can always add more."}'::jsonb, '["Couples usually drift from postponed connection, not one big problem", "Predictable rituals don''t rely on spare energy", "A daily, weekly and monthly touchpoint is enough to start", "Start small and build"]'::jsonb, '[{"title": "Design your rhythm", "description": "Agree on your daily, weekly and monthly touchpoints.", "duration": "15 min", "instructions": ["Choose a daily time for the Bond question.", "Choose a day and time for a weekly check-in.", "Put one monthly shared focus on the calendar."]}]'::jsonb, '{"question": "Which part of your week most needs a little protected time together?", "followUp": "What would you be willing to move to make room for it?"}'::jsonb, 'draft'),
  ('hard-seasons-series', 'grieving-together', 'Grieving Together', 'Why partners grieve differently, and how to support each other without needing to grieve the same way.', 'Why partners grieve differently, and how to support each other without needing to grieve the same way.', '8 min', 1, ARRAY['Dual process model of grief']::text[], '{"introduction": "When a couple loses someone or something important, each partner grieves in their own way and on their own timeline. One may want to talk and cry; the other may throw themselves into tasks. These differences can feel like distance at the very moment you most need each other.", "sections": [{"title": "Grief moves back and forth", "body": "Healthy grieving tends to move between facing the loss (remembering, crying, talking) and taking breaks from it (working, planning, distraction). Both are normal and needed. A partner who seems \"fine\" may simply be in a break phase, not uncaring.", "research": {"text": "The dual process model describes healthy grieving as oscillating between loss-oriented coping and restoration-oriented coping, rather than steadily working through stages.", "source": "Stroebe & Schut, Death Studies", "year": 1999}}, {"title": "Supporting different styles", "body": "Ask rather than assume: \"Do you want to talk about her today, or would a distraction help?\" Make room for your partner''s way without requiring them to match yours. Grief that stays heavy for a long time, or that makes daily life very hard, is a good reason to talk to a grief counselor.", "tip": {"title": "Gentle grief support", "steps": ["Ask what would help today, not in general.", "Accept that your partner''s grief may look different from yours.", "Mark important dates together, in whatever way feels right."]}}], "conclusion": "You don''t have to grieve the same way to grieve together. Making room for each other''s way is itself a form of closeness."}'::jsonb, '["Partners often grieve in different ways and at different paces", "Healthy grief moves between facing the loss and taking breaks", "Ask what would help today rather than assuming", "Long, heavy grief is a reason to seek a grief counselor"]'::jsonb, '[{"title": "How we grieve", "description": "Share how each of you tends to cope with loss.", "duration": "15 min", "instructions": ["Each describe what helps you most when you''re grieving.", "Each describe what makes it harder.", "Agree on a simple way to ask each other what you need on a hard day."]}]'::jsonb, '{"question": "What does your partner not yet know about how you grieve?", "followUp": "What would you want from them on the hardest days?"}'::jsonb, 'draft'),
  ('hard-seasons-series', 'family-plans-change', 'When Plans for a Family Change', 'Supporting each other through fertility struggles and pregnancy loss.', 'Supporting each other through fertility struggles and pregnancy loss.', '8 min', 2, ARRAY['Dyadic coping research']::text[], '{"introduction": "Fertility struggles and pregnancy loss can be among the loneliest experiences a couple faces. The grief is often invisible to others, and partners may experience it very differently — physically, emotionally, and in how much they want to talk about it.", "sections": [{"title": "Two experiences of the same loss", "body": "The partner who carried a pregnancy, or who goes through treatment, experiences it in their body as well as their heart. The other partner may feel helpless, or feel their grief doesn''t count. Both experiences are real. Naming them — \"this is happening to both of us, differently\" — helps partners stay on the same side."}, {"title": "Getting through it together", "body": "Treatment decisions, waiting, and repeated hope and disappointment can strain even strong couples. It helps to set limits together (how much to talk about it each day, who to tell), to protect some time that isn''t about trying, and to lean on support: specialist counselors, support groups, and trusted friends.", "tip": {"title": "Protecting your relationship", "steps": ["Agree on who you''ll tell and what you''ll share.", "Keep one evening a week that isn''t about fertility or the loss.", "Consider a counselor who specializes in fertility or pregnancy loss."]}}], "conclusion": "These are real losses, even when the world doesn''t see them. Facing them side by side — and with support — helps couples come through them together."}'::jsonb, '["Fertility struggles and pregnancy loss are real, often invisible losses", "Partners experience the same loss differently, and both matter", "Setting shared limits protects the relationship", "Specialist counselors and support groups can help"]'::jsonb, '[{"title": "Our shared limits", "description": "Agree on how you''ll protect each other through this season.", "duration": "15 min", "instructions": ["Each share what feels hardest right now.", "Agree on who you''ll tell and what you''ll share.", "Choose one protected, no-fertility-talk time each week."]}]'::jsonb, '{"question": "What do you most need your partner to understand about how this feels for you?", "followUp": "What would help you feel less alone in it?"}'::jsonb, 'draft'),
  ('hard-seasons-series', 'job-loss', 'When One of You Loses a Job', 'How financial and identity stress spill into a relationship, and how to face it as a team.', 'How financial and identity stress spill into a relationship, and how to face it as a team.', '7 min', 3, ARRAY['Economic stress research']::text[], '{"introduction": "Losing a job is rarely just about money. It can shake a person''s sense of identity, routine, and worth — and the financial pressure lands on both partners. It''s common for tension to rise at home, even in close couples.", "sections": [{"title": "How hardship spills over", "body": "Financial strain can increase low mood and irritability, which can make partners less supportive of each other just when support matters most. Knowing this pattern helps couples notice it early and treat the stress, not each other, as the problem.", "research": {"text": "A study of couples after job loss found that financial strain increased depressive symptoms, which in turn were linked to less support and more undermining between partners.", "source": "Vinokur, Price & Caplan, Journal of Personality and Social Psychology", "year": 1996}}, {"title": "Facing it as a team", "body": "Make a short, shared plan: a realistic budget, a job-search rhythm, and clear ways each partner can help. Just as important, keep the partner who lost their job connected to their strengths and to parts of life that aren''t about work.", "tip": {"title": "A team plan", "steps": ["Review finances together once, calmly, and agree on a budget.", "Ask what kind of support helps with the search — and what doesn''t.", "Keep one shared activity each week that has nothing to do with work."]}}], "conclusion": "Job loss tests a couple, but it doesn''t have to divide one. Naming the stress and facing it together keeps it outside the relationship."}'::jsonb, '["Job loss affects identity and routine, not just money", "Financial strain can lower support between partners", "Treat the stress as the shared problem", "Keep connection and strengths alive beyond work"]'::jsonb, '[{"title": "Our team plan", "description": "Make a calm, shared plan for this season.", "duration": "30 min", "instructions": ["Review the budget together and agree on changes.", "The partner searching shares what support helps most.", "Choose one weekly activity that isn''t about work."]}]'::jsonb, '{"question": "What does support look like to you when you''re under financial stress?", "followUp": "What would you like your partner to stop worrying about for you?"}'::jsonb, 'draft'),
  ('hard-seasons-series', 'aging-parents', 'Caring for Aging Parents', 'Balancing care for a parent with care for your relationship.', 'Balancing care for a parent with care for your relationship.', '7 min', 4, ARRAY['Family systems practice']::text[], '{"introduction": "Many couples reach a season when one or both of their parents need more help. Caregiving can be meaningful, but it takes time, energy and money — and it can quietly crowd out the relationship, especially when one partner carries most of it.", "sections": [{"title": "Naming the load", "body": "The partner whose parent needs care often feels torn between obligations. The other partner may feel sidelined, or feel guilty for resenting the change. Talking openly about how much each of you can give — and what you need to protect — prevents quiet resentment."}, {"title": "Sharing and limiting care", "body": "Couples cope better when caregiving is a shared plan rather than something that happens to one person: who does what, how siblings or other family help, what outside services are available, and which parts of your life together stay protected.", "tip": {"title": "A caregiving plan", "steps": ["List the care tasks and who currently does them.", "Ask siblings or other family for specific help.", "Protect one regular time for just the two of you."]}}], "conclusion": "Caring for a parent is an act of love; so is protecting your relationship while you do it. A shared plan lets you do both."}'::jsonb, '["Caregiving can quietly crowd out the relationship", "Talk openly about how much each of you can give", "Make caregiving a shared plan, including other family", "Protect regular time for the two of you"]'::jsonb, '[{"title": "Care and us", "description": "Plan caregiving so it doesn''t swallow your relationship.", "duration": "20 min", "instructions": ["List current care tasks and who does them.", "Each say how much time and energy you realistically have.", "Choose one protected time for the two of you each week."]}]'::jsonb, '{"question": "What do you need from your partner while you care for your parent?", "followUp": "What does your partner need from you?"}'::jsonb, 'draft'),
  ('hard-seasons-series', 'after-a-big-fight', 'After a Big Fight', 'How to come back together after an argument that shook you both.', 'How to come back together after an argument that shook you both.', '8 min', 5, ARRAY['Gottman Method (processing a regrettable incident)']::text[], '{"introduction": "Sometimes an argument goes further than either of you meant it to. Words are said that hurt, and afterward the air feels heavy. What happens next — how you come back together — shapes how safe the relationship feels far more than the fight itself.\n\nThese tools are for couples who feel safe with each other. If you are afraid of your partner, or conflict involves threats, intimidation, or physical harm, relationship exercises are not the right tool. In the US you can reach the National Domestic Violence Hotline at 1-800-799-7233 (or text START to 88788).", "sections": [{"title": "Calm first, then talk", "body": "Trying to resolve a big fight while either of you is still flooded usually restarts it. Take the time you need to calm down — often at least twenty minutes, sometimes a night — and agree on when you''ll come back to it, so the break doesn''t feel like abandonment.", "research": {"text": "Gottman''s work on repair describes processing a regrettable incident after both partners are calm: sharing feelings, describing each person''s reality, naming triggers, and each owning their part.", "source": "Gottman, The Science of Trust", "year": 2011}}, {"title": "Coming back together", "body": "When you talk, the goal is understanding, not a rematch. Each share what you felt, acknowledge that you each experienced the fight differently, and each own one thing you''d do differently. A sincere, specific apology — without \"but\" — goes a long way.", "tip": {"title": "The repair conversation", "steps": ["Each share what you felt, without debating the facts.", "Each acknowledge that the other''s experience makes sense to them.", "Each own one part and name one thing that would help next time."]}}], "conclusion": "Big fights happen in close relationships. Coming back together calmly and honestly afterward is what rebuilds safety."}'::jsonb, '["Don''t try to resolve a big fight while flooded", "Agree on when you''ll come back to it", "Aim for understanding, not a rematch", "Each own one part; apologize specifically"]'::jsonb, '[{"title": "Our repair agreement", "description": "Agree now on how you''ll repair after future big fights.", "duration": "15 min", "instructions": ["Agree on a signal for ''I need a break''.", "Agree on how long breaks usually last and who restarts.", "Agree on the three steps you''ll use to talk it through."]}]'::jsonb, '{"question": "What helps you feel ready to reconnect after a big argument?", "followUp": "What makes it harder?"}'::jsonb, 'draft'),
  ('trust-vulnerability-series', 'jealousy', 'Jealousy and Insecurity', 'Understanding jealousy as a signal about a need, and talking about it without control.', 'Understanding jealousy as a signal about a need, and talking about it without control.', '7 min', 6, ARRAY['Attachment Theory']::text[], '{"introduction": "Almost everyone feels jealous sometimes. The feeling itself isn''t a problem; it''s a signal that something feels threatened — closeness, attention, or security. What matters is what you do with it: turn it into a request, or into checking, accusing and controlling.", "sections": [{"title": "What jealousy is signalling", "body": "Jealousy often grows from insecurity: a worry about being replaced, left out, or not enough. People with more attachment anxiety tend to feel it more intensely. Understanding that the feeling is about your own need — not proof of what your partner is doing — makes it much easier to talk about.", "research": {"text": "Attachment research links attachment anxiety with stronger jealousy and more monitoring of a partner, and links secure attachment with talking about jealousy more constructively.", "source": "Mikulincer & Shaver, Attachment in Adulthood", "year": 2007}}, {"title": "From control to connection", "body": "Checking a partner''s phone or restricting who they see may bring short-term relief but erodes trust over time. A better path is to name the feeling and the need: \"I felt a bit left out when you went to dinner without me. Could we plan something together this week?\" If jealousy becomes controlling or frightening, that is a safety issue, not a communication problem.", "tip": {"title": "Talking about jealousy", "steps": ["Name the feeling as yours: ''I noticed I felt jealous…''", "Name the need underneath: reassurance, time, inclusion.", "Make one specific request, and accept a counteroffer."]}}], "conclusion": "Jealousy is a signal worth listening to — and a need worth voicing. Shared openly, it can lead to more closeness rather than less trust."}'::jsonb, '["Jealousy is a common signal that something feels threatened", "It often reflects insecurity rather than a partner''s actions", "Checking and controlling erode trust over time", "Name the feeling and the need, then make a request"]'::jsonb, '[{"title": "Needs beneath jealousy", "description": "Talk about what helps each of you feel secure.", "duration": "15 min", "instructions": ["Each share a time you felt a little jealous, and what you needed then.", "Each name one thing that helps you feel secure in the relationship.", "Agree on one reassurance habit to try."]}]'::jsonb, '{"question": "When do you feel most secure in your relationship?", "followUp": "What small thing could your partner do to strengthen that feeling?"}'::jsonb, 'draft'),
  ('trust-vulnerability-series', 'digital-boundaries', 'Digital Boundaries and Privacy', 'Agreeing together on phones, passwords, social media and privacy.', 'Agreeing together on phones, passwords, social media and privacy.', '6 min', 7, ARRAY['Couple agreements practice']::text[], '{"introduction": "Phones and social media raise questions previous generations never faced: Is it okay to look at each other''s phones? What''s fine to post about us? Who can we message privately? Couples often have different, unspoken assumptions — which is where hurt comes from.", "sections": [{"title": "Privacy isn''t secrecy", "body": "Having some personal space — private conversations with friends, a journal, your own accounts — is healthy. Secrecy is different: hiding things that would affect your partner or the relationship. Talking about where each of you draws that line prevents misunderstandings."}, {"title": "Making your own agreements", "body": "There''s no single right answer. Some couples share passwords; others don''t. What matters is that the rules are agreed, not assumed, and that they come from trust rather than surveillance. Revisit them when something changes.", "tip": {"title": "Questions to agree on", "steps": ["What''s okay to post about us or our life?", "How do we feel about looking at each other''s phones?", "What kinds of conversations with others would we want to know about?"]}}], "conclusion": "Digital life is part of your relationship now. Clear, shared agreements keep it from becoming a quiet source of mistrust."}'::jsonb, '["Couples often hold different unspoken digital assumptions", "Privacy is healthy; secrecy that affects the relationship isn''t", "There''s no single right rule — only agreed ones", "Revisit agreements when things change"]'::jsonb, '[{"title": "Our digital agreement", "description": "Agree on your own rules for phones and social media.", "duration": "20 min", "instructions": ["Each answer the three questions above privately.", "Compare answers and notice differences.", "Write down two or three agreements you''re both comfortable with."]}]'::jsonb, '{"question": "Is there a digital habit of yours that your partner might not know bothers them?", "followUp": "How could you ask about it without judgment?"}'::jsonb, 'draft'),
  ('intimacy-series', 'initiating-declining', 'Initiating and Declining With Care', 'How to ask for intimacy, and say not tonight, in ways that protect closeness.', 'How to ask for intimacy, and say not tonight, in ways that protect closeness.', '7 min', 6, ARRAY['Sexual communication research']::text[], '{"introduction": "Few moments feel as vulnerable as reaching for your partner and being turned down. Over time, the way couples initiate and decline intimacy can build warmth — or build a quiet pattern of hurt, pressure and avoidance.", "sections": [{"title": "A kind no protects closeness", "body": "Saying no to sex is always okay. How it''s said matters: a warm no that reassures (\"I''m really tired tonight, but I love that you want me — can we cuddle?\") keeps the connection, while a flat or irritated no can feel like rejection of the person. Research suggests kind declines are linked to better relationship quality than going along reluctantly.", "research": {"text": "Research found that declining sex in a reassuring way was associated with higher relationship quality than having sex reluctantly to avoid disappointing a partner.", "source": "Kim, Muise & Impett, Journal of Social and Personal Relationships", "year": 2018}}, {"title": "Making initiating easier", "body": "Talk about initiating outside the bedroom: what kinds of invitations feel good, what feels like pressure, and how each of you likes to be approached. Some couples use a simple signal or phrase so both asking and declining feel lighter.", "tip": {"title": "A kinder yes-or-no", "steps": ["Initiate with an invitation, not an expectation.", "Decline the moment, not the person — and offer an alternative if you''d like.", "Thank each other for asking and for being honest."]}}], "conclusion": "Every invitation and every no is a chance to show care. Handled kindly, both keep the door open."}'::jsonb, '["Initiating and declining can build warmth or hurt over time", "Saying no is always okay; how it''s said matters", "Kind declines protect closeness", "Talk about initiating outside the bedroom"]'::jsonb, '[{"title": "Invitations that feel good", "description": "Share how you each like to be approached.", "duration": "15 min", "instructions": ["Each describe an invitation to intimacy that would feel good to receive.", "Each describe what feels like pressure.", "Agree on a kind way to say ''not tonight'' that you''d both welcome."]}]'::jsonb, '{"question": "What helps you feel wanted when your partner initiates?", "followUp": "What helps you feel okay when they say not tonight?"}'::jsonb, 'draft'),
  ('intimacy-series', 'through-life-changes', 'Intimacy Through Life Changes', 'Keeping closeness alive after a baby, through illness, and as bodies change.', 'Keeping closeness alive after a baby, through illness, and as bodies change.', '7 min', 7, ARRAY['Couple intimacy practice']::text[], '{"introduction": "New babies, health problems, medications, menopause, and simply getting older all change physical intimacy. Couples often stop talking about it just when it''s changing most, and each partner quietly fills the silence with worry or blame.", "sections": [{"title": "Change is normal", "body": "It''s very common for desire, energy and comfort to shift in these seasons. The change itself isn''t a sign that something is wrong between you. What helps is naming it together, being curious about what''s different now, and widening your idea of intimacy beyond what used to be usual."}, {"title": "Finding new ways to be close", "body": "Closeness can take many forms: touch without expectation, new rhythms, different times of day. Physical changes from illness, childbirth or medication are worth raising with a doctor, and a certified sex therapist can help couples adapt.", "tip": {"title": "Adapting together", "steps": ["Name what has changed, without blame.", "Each share one form of closeness that still feels good.", "Ask a doctor about physical changes; consider a sex therapist if you feel stuck."]}}], "conclusion": "Intimacy doesn''t have to look the same across a lifetime to stay alive. Talking about change keeps you close through it."}'::jsonb, '["Life changes commonly shift desire, energy and comfort", "The change isn''t a sign something is wrong between you", "Widen your idea of intimacy", "Doctors and sex therapists can help couples adapt"]'::jsonb, '[{"title": "Closeness now", "description": "Talk about what intimacy looks like in this season.", "duration": "15 min", "instructions": ["Each name one thing that has changed for you.", "Each share one form of closeness that still feels good.", "Choose one new way to be close to try this month."]}]'::jsonb, '{"question": "What''s changed for you about intimacy in the last year?", "followUp": "What would help you feel close in this season?"}'::jsonb, 'draft')
ON CONFLICT (series_key, module_key) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, description = EXCLUDED.description, duration = EXCLUDED.duration, sort_order = EXCLUDED.sort_order, frameworks = EXCLUDED.frameworks, content = EXCLUDED.content, key_takeaways = EXCLUDED.key_takeaways, exercises = EXCLUDED.exercises, reflection = EXCLUDED.reflection, review_status = EXCLUDED.review_status;

-- ============ ACTIVITIES (18)
INSERT INTO activities (activity_key, type, category, title, description, duration, difficulty, framework, content, sort_order, review_status) VALUES
  ('morning-check-in', 'challenge', 'connection', 'Five-Minute Morning Check-In', 'Start each day with a short, phone-free check-in.', '5 min a day', 'easy', 'Rituals of connection', '{"instructions": ["Before phones, spend five minutes together over coffee or breakfast.", "Each share one thing you''re looking forward to and one thing on your mind.", "Do it every morning for a week."], "followUp": "Did the week feel different?"}'::jsonb, 85, 'draft'),
  ('walk-and-talk', 'activity', 'connection', 'Walk and Talk', 'Some conversations flow more easily side by side than face to face.', '30 min', 'easy', 'Shared activity research', '{"instructions": ["Take a walk together without headphones.", "Let the conversation wander; there''s no agenda.", "Near the end, each share one thing you enjoyed about the walk."]}'::jsonb, 86, 'draft'),
  ('weekend-huddle', 'conversation_starter', 'connection', 'Weekend Planning Huddle', 'Plan the weekend together so both of you get what you need.', '15 min', 'easy', 'Rituals of connection', '{"instructions": ["On Thursday or Friday, each share one thing you''d love to do this weekend.", "Each name one thing you need (rest, time alone, a chore done).", "Build a simple plan that includes something for each of you and one thing together."]}'::jsonb, 87, 'draft'),
  ('two-minute-rule', 'scenario', 'communication', 'The Two-Minute Floor', 'Each partner gets two uninterrupted minutes to speak.', '15 min', 'easy', 'Active listening', '{"prompt": "What''s something on your mind this week?", "instructions": ["Set a timer for two minutes. One partner speaks; the other only listens.", "The listener summarizes what they heard in one or two sentences.", "Switch roles."], "rules": "No interrupting, correcting or solving during the two minutes."}'::jsonb, 145, 'draft'),
  ('mirror-validate-empathize', 'scenario', 'communication', 'Mirror, Validate, Empathize', 'A three-step dialogue for feeling truly heard.', '20 min', 'medium', 'Imago Relationship Therapy (couples dialogue)', '{"instructions": ["The sender shares a feeling or experience in a few sentences.", "Mirror: the receiver repeats it back — \"What I heard is…\"", "Validate: \"That makes sense because…\"", "Empathize: \"I imagine you might feel…\"", "Switch roles."]}'::jsonb, 146, 'draft'),
  ('name-the-cycle', 'conversation_starter', 'conflict', 'Name Our Cycle', 'Describe the pattern you both get caught in, so you can fight the cycle instead of each other.', '25 min', 'medium', 'Emotionally Focused Therapy', '{"instructions": ["Think of a recent disagreement. What did each of you do as it escalated?", "Describe it as a loop: ''When I…, you…, and then I…''", "Give the cycle a name together (e.g. ''the chase'').", "Agree on a phrase to use when you notice it: ''I think the chase is starting.''"], "rules": "Describe the cycle, not who started it."}'::jsonb, 205, 'draft'),
  ('softened-replay', 'scenario', 'conflict', 'The Softened Replay', 'Rewind the first minute of a recent argument and try a gentler opening.', '15 min', 'easy', 'Gottman Method (gentle start-up)', '{"instructions": ["Pick a small recent argument you both feel calm about.", "The partner who raised the issue rewrites their opening line as feeling + need.", "Replay the first minute with the new opening and notice what changes."]}'::jsonb, 206, 'draft'),
  ('admiration-text', 'challenge', 'appreciation', 'The Admiration Text', 'Send your partner an unexpected message about something you admire.', '5 min', 'easy', 'Gottman Method (fondness and admiration)', '{"instructions": ["Think of a quality you admire in your partner.", "Send a short message naming it and a moment you saw it.", "Do it twice this week, at unexpected times."]}'::jsonb, 255, 'draft'),
  ('thank-you-tour', 'conversation_starter', 'appreciation', 'The Thank-You Tour', 'Look back over the past month and thank each other for five specific things.', '15 min', 'easy', 'Gratitude research', '{"instructions": ["Each scroll back through the past month (photos and calendars help).", "Each find five things your partner did that you''re grateful for.", "Take turns sharing them, one at a time."]}'::jsonb, 256, 'draft'),
  ('bucket-list-brainstorm', 'activity', 'values', 'Bucket List Brainstorm', 'Dream big together, then add your favorites to your Bond bucket list.', '30 min', 'easy', 'Self-expansion research', '{"instructions": ["Each list ten things you''d love to do in your lifetime.", "Share lists and star the ones you''d love to do together.", "Add your top three to your Bucket List in Bond."]}'::jsonb, 305, 'draft'),
  ('money-date', 'activity', 'values', 'Monthly Money Date', 'A calm monthly look at money, with something nice built in.', '45 min', 'medium', 'Financial relationship research', '{"instructions": ["Pick a relaxed time and add something enjoyable (a favorite drink or snack).", "Review last month''s spending and progress on shared goals.", "Agree on one thing to adjust and one thing to celebrate."], "rules": "Curiosity, not blame. Money habits come from somewhere."}'::jsonb, 306, 'draft'),
  ('stress-free-touch', 'activity', 'intimacy', 'Touch Without Expectation', 'Relaxed, non-sexual touch that''s only about closeness.', '15 min', 'easy', 'Sensate focus (adapted)', '{"instructions": ["Agree beforehand that this is non-sexual and nothing needs to follow.", "Take turns giving a hand, shoulder or foot massage for five minutes each.", "The receiver says what feels good; the giver just enjoys giving."], "rules": "Either of you can pause or stop at any time."}'::jsonb, 325, 'draft'),
  ('four-minute-gaze', 'challenge', 'intimacy', 'Four Minutes of Eye Contact', 'An unusual, surprisingly moving way to feel close.', '5 min', 'medium', 'Closeness-generating research (Aron et al.)', '{"instructions": ["Sit facing each other and set a timer for four minutes.", "Look into each other''s eyes without talking. Laughing is fine.", "Afterwards, share what you noticed or felt."]}'::jsonb, 326, 'draft'),
  ('recreate-first-date', 'challenge', 'fun', 'Recreate Your First Date', 'Revisit where it started — or your best memory of it.', '1–3 hours', 'easy', 'Shared memory and play', '{"instructions": ["Remember your first date together: where, what you did, what you wore.", "Recreate as much of it as you can.", "Share what''s changed about you both since then, and what hasn''t."]}'::jsonb, 375, 'draft'),
  ('learn-together', 'challenge', 'fun', 'Learn Something New Together', 'Take a class or tutorial together as complete beginners.', '1 hour', 'easy', 'Self-expansion research', '{"instructions": ["Pick something neither of you knows how to do (a dance, a recipe, a language).", "Take one lesson together, online or in person.", "Laugh at the mistakes."]}'::jsonb, 376, 'draft'),
  ('game-night', 'challenge', 'fun', 'Game Night Tournament', 'A friendly best-of-three with a silly prize.', '1 hour', 'easy', 'Play and positive affect', '{"instructions": ["Each choose one game.", "Play best of three.", "The winner picks a small, fun prize from the loser (breakfast in bed, choosing the next movie)."], "rules": "Keep it playful; teasing should be the kind you''d both laugh at."}'::jsonb, 377, 'draft'),
  ('letter-to-future-us', 'journal', 'milestones', 'Letter to Future Us', 'Write a letter together to open in one year.', '30 min', 'medium', 'Gottman Method (shared meaning)', '{"instructions": ["Together, write about where you are now: what you''re proud of, what''s hard.", "Write your hopes for the year ahead.", "Seal it, and put a reminder in your calendar to open it in a year."]}'::jsonb, 425, 'draft'),
  ('photo-memory-hunt', 'activity', 'milestones', 'Photo Memory Hunt', 'Find your favorite photos together and add them to Memory Lane.', '30 min', 'easy', 'Gottman Method (fondness and admiration)', '{"instructions": ["Each pick three favorite photos of the two of you.", "Share the story behind each one.", "Add your favorites to Memory Lane in Bond."]}'::jsonb, 426, 'draft')
ON CONFLICT (activity_key) DO UPDATE SET type = EXCLUDED.type, category = EXCLUDED.category, title = EXCLUDED.title, description = EXCLUDED.description, duration = EXCLUDED.duration, difficulty = EXCLUDED.difficulty, framework = EXCLUDED.framework, content = EXCLUDED.content, sort_order = EXCLUDED.sort_order, review_status = EXCLUDED.review_status;

-- ============ DAILY QUESTIONS (60, appended to the rotation)
INSERT INTO daily_questions (question, category, depth, priority, sort_order, active, review_status) VALUES
  ('What''s the best thing you ate this week?', 'fun', 'light', 1, 91, TRUE, 'draft'),
  ('What''s something you''ve been proud of lately that you haven''t said out loud?', 'growth', 'medium', 2, 92, TRUE, 'draft'),
  ('What''s something you''ve never told anyone that you''d feel okay telling me?', 'connection', 'deep', 3, 93, TRUE, 'draft'),
  ('What''s something that made you feel capable today?', 'growth', 'light', 1, 94, TRUE, 'draft'),
  ('How can I tell when you need space, and how can I tell when you need closeness?', 'communication', 'medium', 2, 95, TRUE, 'draft'),
  ('What''s a small moment from today you''d like to remember?', 'memories', 'light', 1, 96, TRUE, 'draft'),
  ('What''s a fear about our relationship that you''d like us to face together?', 'communication', 'deep', 3, 97, TRUE, 'draft'),
  ('What''s a way we''ve grown as a team this year?', 'connection', 'medium', 2, 98, TRUE, 'draft'),
  ('What''s one thing I did recently that made your day easier?', 'gratitude', 'light', 1, 99, TRUE, 'draft'),
  ('What do you most want to be remembered for?', 'values', 'deep', 3, 100, TRUE, 'draft'),
  ('What''s something about how I grew up that you''d like to understand better?', 'values', 'medium', 2, 101, TRUE, 'draft'),
  ('Where''s somewhere you feel completely relaxed?', 'connection', 'light', 1, 102, TRUE, 'draft'),
  ('What''s a little ritual of ours that you''d miss if it stopped?', 'values', 'light', 1, 103, TRUE, 'draft'),
  ('When do you feel most appreciated by me?', 'gratitude', 'medium', 2, 104, TRUE, 'draft'),
  ('How do you want us to handle it when life gets really hard?', 'goals', 'deep', 3, 105, TRUE, 'draft'),
  ('What''s a skill you''d love us to learn together?', 'goals', 'light', 1, 106, TRUE, 'draft'),
  ('What''s something you''d like to try in our relationship that we''ve never done?', 'goals', 'medium', 2, 107, TRUE, 'draft'),
  ('What''s something you want to tell me about your day that I didn''t ask?', 'communication', 'light', 1, 108, TRUE, 'draft'),
  ('What''s a part of your past that still shapes how you love?', 'memories', 'deep', 3, 109, TRUE, 'draft'),
  ('What''s a moment when you felt really proud to be with me?', 'memories', 'medium', 2, 110, TRUE, 'draft'),
  ('If we had a theme night this week, what would it be?', 'fun', 'light', 1, 111, TRUE, 'draft'),
  ('What kind of partner do you hope to be in ten years?', 'growth', 'deep', 3, 112, TRUE, 'draft'),
  ('What does a perfect Sunday look like for you now, compared with a few years ago?', 'growth', 'medium', 2, 113, TRUE, 'draft'),
  ('What''s one thing you''re curious about lately?', 'growth', 'light', 1, 114, TRUE, 'draft'),
  ('What''s a nickname or inside joke of ours that still makes you smile?', 'memories', 'light', 1, 115, TRUE, 'draft'),
  ('What helps you recharge after a hard day?', 'communication', 'medium', 2, 116, TRUE, 'draft'),
  ('When have you felt most accepted by me, exactly as you are?', 'connection', 'deep', 3, 117, TRUE, 'draft'),
  ('What''s something that made you proud of me recently?', 'gratitude', 'light', 1, 118, TRUE, 'draft'),
  ('What''s one thing you''d like us to do more often as a couple?', 'connection', 'medium', 2, 119, TRUE, 'draft'),
  ('What would make this evening feel really good?', 'connection', 'light', 1, 120, TRUE, 'draft'),
  ('What would you want to change about how we argue?', 'communication', 'deep', 3, 121, TRUE, 'draft'),
  ('What''s a tradition you''d like us to start?', 'values', 'medium', 2, 122, TRUE, 'draft'),
  ('What''s a small thing that would make our home feel cozier?', 'values', 'light', 1, 123, TRUE, 'draft'),
  ('What does commitment mean to you right now?', 'values', 'deep', 3, 124, TRUE, 'draft'),
  ('How do you like to be supported when you''re working toward a goal?', 'goals', 'medium', 2, 125, TRUE, 'draft'),
  ('What''s one thing you''re looking forward to this month?', 'goals', 'light', 1, 126, TRUE, 'draft'),
  ('What''s a book, podcast or show you''d recommend to me right now?', 'fun', 'light', 1, 127, TRUE, 'draft'),
  ('How has the way you show love changed since we met?', 'growth', 'medium', 2, 128, TRUE, 'draft'),
  ('What''s a dream you''re a little scared to say out loud?', 'goals', 'deep', 3, 129, TRUE, 'draft'),
  ('What''s something you did today just for yourself?', 'growth', 'light', 1, 130, TRUE, 'draft'),
  ('What''s a worry you''ve been carrying this week?', 'communication', 'medium', 2, 131, TRUE, 'draft'),
  ('If you could relive one day of our relationship, which would it be?', 'memories', 'light', 1, 132, TRUE, 'draft'),
  ('What''s something you''ve learned about love from us?', 'growth', 'deep', 3, 133, TRUE, 'draft'),
  ('What would you like more of in how we spend our free time?', 'connection', 'medium', 2, 134, TRUE, 'draft'),
  ('What made you feel cared for today, by anyone?', 'gratitude', 'light', 1, 135, TRUE, 'draft'),
  ('When do you feel most like yourself with me?', 'connection', 'deep', 3, 136, TRUE, 'draft'),
  ('What do you think is our biggest strength as a couple?', 'values', 'medium', 2, 137, TRUE, 'draft'),
  ('What was the highlight of your week so far?', 'connection', 'light', 1, 138, TRUE, 'draft'),
  ('What''s your favorite way to spend a rainy day together?', 'fun', 'light', 1, 139, TRUE, 'draft'),
  ('What''s a way you''d like to celebrate our next milestone?', 'goals', 'medium', 2, 140, TRUE, 'draft'),
  ('What''s a wound from the past you''d like help healing?', 'growth', 'deep', 3, 141, TRUE, 'draft'),
  ('What''s one habit you''d like to start this week?', 'growth', 'light', 1, 142, TRUE, 'draft'),
  ('What''s something small that you''d like us to stop doing?', 'communication', 'medium', 2, 143, TRUE, 'draft'),
  ('Which friend would you like us to spend more time with?', 'connection', 'light', 1, 144, TRUE, 'draft'),
  ('How do you want to be comforted when you''re scared?', 'connection', 'deep', 3, 145, TRUE, 'draft'),
  ('What''s one thing I could do this week that would mean a lot to you?', 'connection', 'medium', 2, 146, TRUE, 'draft'),
  ('What''s a meal you''d love me to make — or us to make together?', 'fun', 'light', 1, 147, TRUE, 'draft'),
  ('What''s one thing you wish I understood about how you see yourself?', 'connection', 'deep', 3, 148, TRUE, 'draft'),
  ('What part of our routine feels most like home to you?', 'values', 'medium', 2, 149, TRUE, 'draft'),
  ('What''s a place you''d love to show me?', 'fun', 'light', 1, 150, TRUE, 'draft')
ON CONFLICT (question) DO UPDATE SET category = EXCLUDED.category, depth = EXCLUDED.depth, priority = EXCLUDED.priority, sort_order = EXCLUDED.sort_order, active = TRUE, review_status = EXCLUDED.review_status;

-- ============ CHECK-IN TOPICS (10)
INSERT INTO check_in_topics (topic_key, topic_name, description, category, depth_level, framework, prompt_questions, sort_order, review_status) VALUES
  ('work-life', 'Work and Life Balance', 'Is work leaving enough room for your life together?', 'wellbeing', 1, 'Stress spillover research', ARRAY['How has work been affecting your energy at home?', 'Is there a time work intrudes on us that you''d like to protect?', 'What''s one change that would help this month?']::text[], 210, 'draft'),
  ('friendships', 'Friends and Social Life', 'Are you both getting the social connection you need?', 'connection', 1, 'Social support research', ARRAY['Are you seeing your friends as much as you''d like?', 'Is there a friendship you''d like to invest in more, together or separately?', 'How much social time feels right for each of us right now?']::text[], 220, 'draft'),
  ('faith', 'Faith, Meaning and Beliefs', 'How do your beliefs and sense of meaning fit together?', 'values', 2, 'Gottman Method (shared meaning)', ARRAY['What gives your life meaning right now?', 'Are there beliefs or practices you''d like to share more — or give each other more space for?', 'How do we want our beliefs to show up in our home?']::text[], 230, 'draft'),
  ('family-planning', 'Children and Family Plans', 'Are you on the same page about children and family?', 'family', 3, 'Family planning communication', ARRAY['How are you feeling about children or family plans right now?', 'Has anything changed in what you want?', 'What would you like us to decide, and by when?']::text[], 240, 'draft'),
  ('security', 'Feeling Secure Together', 'Does the relationship feel steady and secure for both of you?', 'trust', 2, 'Attachment Theory', ARRAY['When do you feel most secure in us?', 'Has anything recently made you feel less secure?', 'What''s one reassurance that would help right now?']::text[], 250, 'draft'),
  ('forgiveness', 'Apologies and Forgiveness', 'How are you both at apologizing and letting go?', 'conflict', 3, 'Forgiveness research', ARRAY['Is there anything you''re still holding onto?', 'What makes an apology feel real to you?', 'Is there anything you''d like to apologize for?']::text[], 260, 'draft'),
  ('rest', 'Rest and Downtime', 'Is each of you getting enough rest and time to recharge?', 'wellbeing', 1, 'Dyadic coping research', ARRAY['How rested have you felt lately?', 'What kind of downtime helps you most?', 'How can we make sure we each get some this week?']::text[], 270, 'draft'),
  ('dreams', 'Dreams and Adventures', 'Are you making room for the things you dream of doing?', 'goals', 1, 'Self-expansion research', ARRAY['What''s on your bucket list that we haven''t talked about lately?', 'Is there an adventure we could plan for this year?', 'What''s one small step we could take toward it?']::text[], 280, 'draft'),
  ('hard-times', 'Grief and Hard Times', 'How are you both coping with anything heavy right now?', 'wellbeing', 3, 'Dual process model of grief', ARRAY['Is anything weighing on you that we haven''t talked about?', 'What kind of support helps you most when things are heavy?', 'Is there anyone else who could support us right now?']::text[], 290, 'draft'),
  ('sex-life', 'Our Sex Life', 'How is your physical relationship feeling for each of you?', 'intimacy', 3, 'Sexual communication research', ARRAY['What''s one thing you appreciate about our physical relationship?', 'Is there anything you''d like more of, less of, or to try?', 'What helps you feel relaxed and wanted?']::text[], 300, 'draft')
ON CONFLICT (topic_key) DO UPDATE SET topic_name = EXCLUDED.topic_name, description = EXCLUDED.description, category = EXCLUDED.category, depth_level = EXCLUDED.depth_level, framework = EXCLUDED.framework, prompt_questions = EXCLUDED.prompt_questions, sort_order = EXCLUDED.sort_order, review_status = EXCLUDED.review_status;

-- ============ MONTHLY DEEP-DIVE THEMES (4)
INSERT INTO deep_dive_themes (theme_key, title, summary, framework, focus_questions, weekly_activities, sort_order, review_status) VALUES
  ('play-adventure', 'Play and Adventure', 'A month of doing new things and laughing more together.', 'Self-expansion research', '["When do we laugh the most together?", "What''s something new we''ve always wanted to try?", "What did fun look like when we first met?", "How can we make play a regular part of life?"]'::jsonb, '[{"week": 1, "title": "Something new", "description": "Plan and do one activity neither of you has tried."}, {"week": 2, "title": "Game night", "description": "Hold a best-of-three game night with a silly prize."}, {"week": 3, "title": "Recreate a first", "description": "Recreate your first date or another early memory."}, {"week": 4, "title": "Bucket list", "description": "Brainstorm big dreams and add your favorites to your Bucket List."}]'::jsonb, 90, 'draft'),
  ('family-traditions', 'Family and Traditions', 'A month of shaping the traditions and family culture you want.', 'Family systems practice', '["What traditions from each of our families do we want to keep?", "Which ones would we rather let go?", "How do we want to handle holidays with extended family?", "What''s a new tradition that would feel like ours?"]'::jsonb, '[{"week": 1, "title": "Family stories", "description": "Share a favorite tradition from each of your childhoods."}, {"week": 2, "title": "Keep and let go", "description": "Choose one tradition to keep and one to adapt or drop."}, {"week": 3, "title": "Holiday plan", "description": "Agree on how you''ll handle the next holiday with family."}, {"week": 4, "title": "A new tradition", "description": "Start one brand-new tradition of your own."}]'::jsonb, 100, 'draft'),
  ('growing-together', 'Growing Individually, Together', 'A month of supporting each other''s personal goals.', 'Self-expansion research', '["What''s something each of us is working on for ourselves?", "How do we like to be supported in our goals?", "What gets in the way of personal growth right now?", "How has each of us grown since we met?"]'::jsonb, '[{"week": 1, "title": "Growth goals", "description": "Each share one personal goal for the next six months."}, {"week": 2, "title": "Support plan", "description": "Each say what support would actually help, and agree on it."}, {"week": 3, "title": "Progress check", "description": "Check in on progress and celebrate small steps."}, {"week": 4, "title": "Grown together", "description": "Share how you''ve each seen the other grow."}]'::jsonb, 110, 'draft'),
  ('rest-rhythm', 'Rest and Rhythm', 'A month of protecting rest, balance and unhurried time together.', 'Stress spillover research', '["How rested do we each feel right now?", "Where does work or busyness crowd out our time together?", "What kind of rest helps each of us most?", "What rhythm would feel sustainable?"]'::jsonb, '[{"week": 1, "title": "Energy check", "description": "Each rate your energy and name what drains and restores it."}, {"week": 2, "title": "Protected time", "description": "Choose one screen-free, work-free evening and keep it."}, {"week": 3, "title": "Say no to one thing", "description": "Each drop or postpone one commitment to make room."}, {"week": 4, "title": "Design a rhythm", "description": "Agree on a daily, weekly and monthly rhythm that feels sustainable."}]'::jsonb, 120, 'draft')
ON CONFLICT (theme_key) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, framework = EXCLUDED.framework, focus_questions = EXCLUDED.focus_questions, weekly_activities = EXCLUDED.weekly_activities, sort_order = EXCLUDED.sort_order, review_status = EXCLUDED.review_status;

COMMIT;
